# Generated by Django 6.0.2 on 2026-09-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cleaner",
            fields=[],
            options={
                "verbose_name": "Cleaner",
                "verbose_name_plural": "Cleaners",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.cleaner",),
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.driver",),
        ),
        migrations.CreateModel(
            name="LicenseClass",
            fields=[],
            options={
                "verbose_name": "License class",
                "verbose_name_plural": "License classes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.licenseclass",),
        ),
    ]
