# Generated by Django 5.1.15 on 2026-09-27 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("fleet_contracts", "0003_transportcontract_category_specifications"),
        ("operations", "0009_tripitineraryday"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelConfirmationVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("hotel_name", models.CharField(max_length=255)),
                ("hotel_city", models.CharField(default="Coimbatore", max_length=100)),
                ("hotel_address", models.TextField(blank=True)),
                ("hotel_phone", models.CharField(blank=True, max_length=30)),
                ("hotel_email", models.EmailField(blank=True, max_length=254)),
                ("reservation_contact", models.CharField(blank=True, max_length=100)),
                (
                    "hotel_confirmation_code",
                    models.CharField(
                        blank=True,
                        help_text="Reservation booking ID from hotel CRS",
                        max_length=100,
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_in_time", models.TimeField(default="12:00")),
                ("check_out_date", models.DateField()),
                ("check_out_time", models.TimeField(default="11:00")),
                ("total_nights", models.PositiveIntegerField(default=1)),
                ("lead_guest_name", models.CharField(max_length=200)),
                ("lead_guest_phone", models.CharField(max_length=30)),
                ("total_adults", models.PositiveIntegerField(default=2)),
                ("total_children", models.PositiveIntegerField(default=0)),
                ("total_rooms", models.PositiveIntegerField(default=1)),
                (
                    "room_category",
                    models.CharField(
                        choices=[
                            ("standard", "Standard AC Room"),
                            ("deluxe", "Deluxe Room"),
                            ("super_deluxe", "Super Deluxe Room"),
                            ("executive_suite", "Executive Suite"),
                            ("family_cottage", "Family Cottage / Villa"),
                            ("luxury_tent", "Luxury Glamping Tent / Treehouse"),
                        ],
                        default="deluxe",
                        max_length=30,
                    ),
                ),
                (
                    "meal_plan",
                    models.CharField(
                        choices=[
                            ("EP", "European Plan (Room Only - No Meals)"),
                            ("CP", "Continental Plan (Bed & Breakfast Included)"),
                            (
                                "MAP",
                                "Modified American Plan (Breakfast + Dinner Included)",
                            ),
                            (
                                "AP",
                                "American Plan (All Meals - Breakfast, Lunch, Dinner Included)",
                            ),
                        ],
                        default="MAP",
                        max_length=10,
                    ),
                ),
                (
                    "inclusions_notes",
                    models.TextField(
                        blank=True,
                        default="Welcome Drink, Wi-Fi Access, Complimentary Breakfast and Dinner.",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="e.g. Free driver accommodation/food, Non-smoking room, Interconnecting rooms",
                    ),
                ),
                (
                    "billing_instruction",
                    models.CharField(
                        choices=[
                            (
                                "bill_to_company",
                                "Bill Entire Accommodation to Sivagayathiri Travels (Credit Account)",
                            ),
                            (
                                "direct_payment",
                                "Room Only Billed to Company, Extras Direct by Guest",
                            ),
                            (
                                "guest_direct_all",
                                "All Charges Payable Directly by Guest at Reception",
                            ),
                        ],
                        default="bill_to_company",
                        max_length=30,
                    ),
                ),
                (
                    "agreed_hotel_tariff",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount Sivagayathiri pays the hotel",
                        max_digits=12,
                    ),
                ),
                (
                    "advance_paid_to_hotel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "balance_payable_to_hotel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued / Sent to Hotel"),
                            ("confirmed", "Confirmed by Hotel Reservations"),
                            ("checked_in", "Guests Checked In"),
                            ("checked_out", "Checked Out & Completed"),
                            ("cancelled", "Booking Cancelled"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("whatsapp_dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_vouchers",
                        to="operations.trip",
                    ),
                ),
                (
                    "trip_hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers",
                        to="operations.triphotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Confirmation Voucher",
                "verbose_name_plural": "Hotel Confirmation Vouchers",
                "ordering": ["-check_in_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HotelVoucherGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_label", models.CharField(default="Room 1", max_length=50)),
                ("guest_name", models.CharField(max_length=200)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=15)),
                (
                    "id_proof_type",
                    models.CharField(
                        choices=[
                            ("aadhaar", "Aadhaar Card"),
                            ("passport", "Passport"),
                            ("driving_license", "Driving License"),
                            ("voter_id", "Voter ID Card"),
                            ("other", "Other ID"),
                        ],
                        default="aadhaar",
                        max_length=30,
                    ),
                ),
                ("id_proof_number", models.CharField(blank=True, max_length=50)),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_manifest",
                        to="suppliers.hotelconfirmationvoucher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutsourcedTripSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settlement_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "settlement_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("driver_name", models.CharField(blank=True, max_length=150)),
                ("driver_phone", models.CharField(blank=True, max_length=30)),
                ("odometer_start", models.PositiveIntegerField(blank=True, null=True)),
                ("odometer_end", models.PositiveIntegerField(blank=True, null=True)),
                ("total_km_run", models.PositiveIntegerField(default=0)),
                ("duty_slip_number", models.CharField(blank=True, max_length=50)),
                (
                    "customer_sell_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total customer revenue billed for this trip",
                        max_digits=12,
                    ),
                ),
                (
                    "agreed_buy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Agreed hire charge payable to partner supplier",
                        max_digits=12,
                    ),
                ),
                (
                    "toll_parking_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual toll/parking receipts reimbursable to partner",
                        max_digits=10,
                    ),
                ),
                (
                    "driver_bata_payable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Driver night halt / bata payable to partner driver",
                        max_digits=10,
                    ),
                ),
                (
                    "advance_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cash/UPI advance given to partner before journey",
                        max_digits=10,
                    ),
                ),
                (
                    "fuel_deducted",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fuel filled via Sivagayathiri company card",
                        max_digits=10,
                    ),
                ),
                (
                    "damage_penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Breakdown, delay or passenger dispute penalty",
                        max_digits=10,
                    ),
                ),
                ("tds_applicable", models.BooleanField(default=True)),
                (
                    "tds_section",
                    models.CharField(
                        choices=[
                            (
                                "194C_INDIVIDUAL",
                                "Sec 194C - Individual / HUF Transporter (1.00%)",
                            ),
                            ("194C_COMPANY", "Sec 194C - Company / Firm / LLP (2.00%)"),
                            (
                                "206AA_NO_PAN",
                                "Sec 206AA - Non-Furnishing of PAN (20.00%)",
                            ),
                            (
                                "EXEMPT_DECLARATION",
                                "Exempt - Form 194C(6) <10 Goods/Passenger Vehicles (0.00%)",
                            ),
                            ("CUSTOM", "Custom Deducted Rate"),
                        ],
                        default="194C_INDIVIDUAL",
                        max_length=30,
                    ),
                ),
                ("pan_number", models.CharField(blank=True, max_length=15)),
                (
                    "tds_rate_percent",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "tds_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gross_supplier_payable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_payable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross_margin_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Profit Sivagayathiri earned on outsourcing this trip",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (Pending Verification)"),
                            ("verified", "Verified by Dispatcher"),
                            ("approved", "Approved by Accounts"),
                            ("paid", "Settled & Paid"),
                            ("disputed", "Disputed / On Hold"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("bank_neft", "NEFT / RTGS Transfer"),
                            ("upi", "Instant UPI Transfer"),
                            ("cheque", "Account Payee Cheque"),
                            ("cash", "Cash Disbursement"),
                        ],
                        default="bank_neft",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank NEFT UTR / Cheque No / UPI Transaction ID",
                        max_length=100,
                    ),
                ),
                ("payment_cleared_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outsourced_settlements",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_settlements",
                        to="core.party",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outsourced_settlements",
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outsourced_settlements",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outsourced Trip Settlement",
                "verbose_name_plural": "Outsourced Trip Settlements",
                "ordering": ["-settlement_date", "-id"],
            },
        ),
    ]
