# Generated by Django 6.0.2 on 2026-09-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cleaner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On leave"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "default_daily_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("can_drive", models.BooleanField(default=False)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("aadhar_number", models.CharField(blank=True, max_length=20)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="cleaners/profiles/"
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=50)),
                ("license_validity", models.DateField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("blood_group", models.CharField(blank=True, max_length=10)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("ifsc_code", models.CharField(blank=True, max_length=20)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "driver_type",
                    models.CharField(
                        choices=[
                            ("owned", "Own Driver (Salary)"),
                            ("supplier", "Supplier Driver"),
                            ("temporary", "Temporary Contract Driver"),
                        ],
                        default="owned",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On leave"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "father_or_spouse_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Son/Daughter/Wife of"
                    ),
                ),
                ("aadhar_number", models.CharField(blank=True, max_length=20)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="drivers/profiles/"
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=50)),
                (
                    "licensing_authority",
                    models.CharField(
                        blank=True, help_text="e.g., TN52 SANKARI RTO", max_length=100
                    ),
                ),
                ("license_issue_date", models.DateField(blank=True, null=True)),
                (
                    "license_validity_nt",
                    models.DateField(
                        blank=True, null=True, verbose_name="Validity (NT)"
                    ),
                ),
                (
                    "license_validity_tr",
                    models.DateField(
                        blank=True, null=True, verbose_name="Validity (TR)"
                    ),
                ),
                ("badge_number", models.CharField(blank=True, max_length=50)),
                (
                    "license_document",
                    models.FileField(
                        blank=True, null=True, upload_to="drivers/licenses/"
                    ),
                ),
                (
                    "is_volvo_certified",
                    models.BooleanField(
                        default=False,
                        help_text="Has completed official Volvo multi-axle training",
                        verbose_name="Volvo Multi-Axle Certified",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("blood_group", models.CharField(blank=True, max_length=10)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("ifsc_code", models.CharField(blank=True, max_length=20)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
                (
                    "languages_spoken",
                    models.CharField(
                        blank=True,
                        help_text="e.g., English, Hindi, Tamil",
                        max_length=255,
                    ),
                ),
                ("hill_station_experience", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LicenseClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., LMV-TR", max_length=20, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Light Motor Vehicle - Transport",
                        max_length=100,
                    ),
                ),
                (
                    "example_vehicles",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Taxi, small commercial vehicle",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("travel_agency", "Travel agency"),
                            ("corporate", "Corporate"),
                            ("hotel", "Hotel"),
                            ("individual", "Individual"),
                            ("supplier", "Supplier"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("trip", "Trip-by-trip"),
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("bimonthly", "Bi-monthly (Every 2 Months)"),
                            ("quarterly", "Quarterly (Every 3 Months)"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("credit_period_days", models.PositiveIntegerField(default=30)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                (
                    "state_code",
                    models.CharField(
                        blank=True, help_text="e.g. 33 for TN", max_length=2
                    ),
                ),
                (
                    "tds_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default TDS deduction percentage (e.g. 2.0 for 194C)",
                        max_digits=5,
                    ),
                ),
                (
                    "default_day_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "default_km_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                (
                    "default_day_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "default_km_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "driver_bata",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("seating_capacity", models.PositiveIntegerField(default=4)),
                ("luggage_capacity", models.CharField(blank=True, max_length=100)),
                ("has_ac", models.BooleanField(default=True, verbose_name="AC")),
                ("is_luxury", models.BooleanField(default=False)),
                (
                    "stock_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_types/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CleanerEmploymentPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_on", models.DateField()),
                ("left_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "cleaner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_periods",
                        to="core.cleaner",
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_on"],
            },
        ),
        migrations.CreateModel(
            name="DriverEmploymentPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_on", models.DateField()),
                ("left_on", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_periods",
                        to="core.driver",
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_on"],
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="license_classes",
            field=models.ManyToManyField(blank=True, to="core.licenseclass"),
        ),
        migrations.AddField(
            model_name="driver",
            name="employer_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employed_drivers",
                to="core.party",
            ),
        ),
        migrations.AddField(
            model_name="cleaner",
            name="employer_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employed_cleaners",
                to="core.party",
            ),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.party",),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.party",),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=30, unique=True)),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("owned", "Owned fleet"),
                            ("outsourced", "Outsourced / supplier"),
                        ],
                        default="owned",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("on_trip", "On trip"),
                            ("maintenance", "Maintenance"),
                            ("inactive", "Inactive"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("cng", "CNG"),
                            ("electric", "Electric"),
                        ],
                        default="diesel",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_tank_capacity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Capacity in Liters", null=True
                    ),
                ),
                (
                    "def_capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Capacity in Liters",
                        null=True,
                        verbose_name="DEF (AdBlue) Capacity",
                    ),
                ),
                ("seating_capacity", models.PositiveIntegerField(default=4)),
                ("current_km", models.PositiveIntegerField(default=0)),
                ("has_ac", models.BooleanField(default=False, verbose_name="AC")),
                (
                    "is_sleeper",
                    models.BooleanField(
                        default=False, verbose_name="Sleeper / Pushback"
                    ),
                ),
                (
                    "has_air_suspension",
                    models.BooleanField(default=False, verbose_name="Air Suspension"),
                ),
                (
                    "has_video_coach",
                    models.BooleanField(
                        default=False, verbose_name="Video Coach (TV/Music)"
                    ),
                ),
                (
                    "rc_expiry",
                    models.DateField(blank=True, null=True, verbose_name="RC Expiry"),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("fc_expiry", models.DateField(blank=True, null=True)),
                ("permit_expiry", models.DateField(blank=True, null=True)),
                ("tax_expiry", models.DateField(blank=True, null=True)),
                ("pollution_expiry", models.DateField(blank=True, null=True)),
                (
                    "expected_mileage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected km/litre for fuel theft detection",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("engine_number", models.CharField(blank=True, max_length=100)),
                ("chassis_number", models.CharField(blank=True, max_length=100)),
                (
                    "rc_document",
                    models.FileField(blank=True, null=True, upload_to="vehicles/rc/"),
                ),
                (
                    "gps_imei",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="GPS IMEI Number"
                    ),
                ),
                (
                    "fastag_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="FASTag ID"
                    ),
                ),
                (
                    "default_driver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-assigned to this driver when selected for a trip",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_vehicles",
                        to="core.driver",
                    ),
                ),
                (
                    "owner_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplied_vehicles",
                        to="core.party",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.vehicletype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiclePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="vehicles/gallery/")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Interior view, Front view",
                        max_length=100,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "km_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "extra_km_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "driver_bata",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "night_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "airport_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "permit_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_cards",
                        to="core.party",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_cards",
                        to="core.vehicle",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.vehicletype",
                    ),
                ),
            ],
        ),
    ]
