# Generated by Django 6.0.2 on 2026-09-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="amenities",
            field=models.TextField(
                blank=True, help_text="e.g. WiFi, TV, Reclining Seats"
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short description for customer portal"
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="expected_mileage_kmpl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average expected km/l",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="extra_hour_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="extra_km_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("petrol", "Petrol"),
                    ("diesel", "Diesel"),
                    ("cng", "CNG"),
                    ("electric", "Electric"),
                ],
                default="diesel",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="is_wheelchair_accessible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="minimum_km_per_day",
            field=models.PositiveIntegerField(
                default=250, help_text="Standard daily minimum billing km"
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="night_halt_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="toll_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("car", "Car / Jeep / Van"),
                    ("lcv", "LCV / Mini Bus"),
                    ("bus_2_axle", "Bus (2 Axle)"),
                    ("bus_3_axle", "Bus (3 Axle)"),
                    ("multi_axle", "Multi Axle"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="transmission_type",
            field=models.CharField(
                blank=True,
                choices=[("manual", "Manual"), ("automatic", "Automatic")],
                max_length=20,
            ),
        ),
    ]
