# Generated by Django 6.0.2 on 2026-09-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_vehicletype_amenities_vehicletype_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="current_location",
            field=models.CharField(
                blank=True,
                help_text="Current home depot or parked location",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="emi_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="financier_name",
            field=models.CharField(
                blank=True, help_text="e.g. Cholamandalam Finance", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="insurance_document",
            field=models.FileField(
                blank=True, null=True, upload_to="vehicles/insurance/"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="insurance_provider",
            field=models.CharField(
                blank=True, help_text="e.g. Tata AIG, HDFC Ergo", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_financed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="loan_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="next_service_due_km",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Next Service Due (KM)"
            ),
        ),
    ]
