# Generated by Django 6.0.2 on 2026-09-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_vehicle_current_location_vehicle_emi_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="supplier_contact_person",
            field=models.CharField(
                blank=True,
                help_text="Primary contact at the supplier for this vehicle",
                max_length=100,
                verbose_name="Supplier Contact Person",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_contract_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Contract End Date"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_contract_ref",
            field=models.CharField(
                blank=True,
                help_text="Agreement or contract number",
                max_length=100,
                verbose_name="Contract Reference",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_contract_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Contract Start Date"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="What the supplier charges per day",
                max_digits=10,
                null=True,
                verbose_name="Supplier Daily Rate (₹)",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_driver_bata",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Driver allowance the supplier charges",
                max_digits=10,
                null=True,
                verbose_name="Supplier Driver Bata (₹)",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_driver_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Supplier's Driver Name"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_driver_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Supplier's Driver Phone"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_km_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="What the supplier charges per km",
                max_digits=10,
                null=True,
                verbose_name="Supplier KM Rate (₹)",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_min_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Supplier's minimum commitment in hours",
                null=True,
                verbose_name="Minimum Hours",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_min_km",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Supplier's minimum commitment in km",
                null=True,
                verbose_name="Minimum KM",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_notes",
            field=models.TextField(
                blank=True,
                help_text="Special terms, conditions, or notes about this supplier vehicle",
                verbose_name="Notes / Remarks",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="supplier_payment_terms",
            field=models.CharField(
                choices=[
                    ("advance", "Advance"),
                    ("credit", "Credit"),
                    ("cod", "Cash on Delivery"),
                ],
                default="credit",
                max_length=20,
                verbose_name="Payment Terms",
            ),
        ),
    ]
