# Generated by Django 6.0.2 on 2026-09-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_supplier_fields_to_vehicle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="licenseclass",
            options={
                "ordering": ["code"],
                "verbose_name": "License Class",
                "verbose_name_plural": "License Classes",
            },
        ),
    ]
