# Generated by Django 5.1.15 on 2026-10-08 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "System Director / Super Admin"),
                            ("manager", "General / Branch Manager"),
                            (
                                "sales_executive",
                                "Senior Sales Executive & Tour Designer",
                            ),
                            ("sales", "Corporate Sales Representative"),
                            ("operations", "Fleet & Dispatch Operations Lead"),
                            (
                                "operation_account",
                                "Operations Accounts & Billing Officer",
                            ),
                            ("driver", "Senior Fleet Chauffeur"),
                            (
                                "customer_service",
                                "Guest Experience & Support Specialist",
                            ),
                        ],
                        default="sales_executive",
                        max_length=30,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="e.g. SGT-ADM-01", max_length=30, unique=True
                    ),
                ),
                (
                    "branch",
                    models.CharField(default="Chennai Central HQ", max_length=100),
                ),
                ("department", models.CharField(default="Operations", max_length=100)),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("emergency_contact", models.CharField(blank=True, max_length=20)),
                (
                    "approval_limit_inr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Max discount or expense approval ceiling",
                        max_digits=12,
                    ),
                ),
                (
                    "monthly_sales_target_inr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_on_duty", models.BooleanField(default=True)),
                ("avatar_color", models.CharField(default="#0284c7", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_accounts",
                        to="core.driver",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Profile",
                "verbose_name_plural": "Staff Profiles",
                "ordering": ["employee_id"],
            },
        ),
    ]
