# Generated by Django 5.1.15 on 2026-10-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_staffprofile"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="party",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_day_rate__gte", 0),
                    ("default_km_rate__gte", 0),
                    ("tds_rate__gte", 0),
                ),
                name="party_rates_non_negative",
            ),
        ),
    ]
