# Generated by Django 5.1.15 on 2026-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_party_party_rates_non_negative"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["status", "driver_type"], name="idx_drv_status_type"
            ),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(
                fields=["is_active", "party_type"], name="idx_party_active_type"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["status", "vehicle_type"], name="idx_veh_status_type"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["ownership_type", "status"], name="idx_veh_owner_status"
            ),
        ),
    ]
