# Generated by Django 6.0.2 on 2026-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_name", models.CharField(max_length=255)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("generated_by", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
