# Generated by Django 6.0.2 on 2026-09-24 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("core", "0005_alter_licenseclass_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverScorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="First day of the evaluation period",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Snapshot"),
                            ("custom", "Custom Period"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("total_trips", models.PositiveIntegerField(default=0)),
                ("completed_trips", models.PositiveIntegerField(default=0)),
                ("total_kms_driven", models.PositiveIntegerField(default=0)),
                ("on_time_trips", models.PositiveIntegerField(default=0)),
                ("delayed_trips", models.PositiveIntegerField(default=0)),
                (
                    "punctuality_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("overspeeding_count", models.PositiveIntegerField(default=0)),
                ("harsh_braking_count", models.PositiveIntegerField(default=0)),
                ("traffic_fines_count", models.PositiveIntegerField(default=0)),
                (
                    "total_fine_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "safety_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("feedback_count", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                (
                    "customer_rating_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "expected_fuel_litres",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "actual_fuel_litres",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "fuel_efficiency_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "overall_composite_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A+", "A+ (Elite - Star Captain)"),
                            ("A", "A (Excellent)"),
                            ("B", "B (Good / Standard)"),
                            ("C", "C (Needs Improvement)"),
                            ("D", "D (At Risk / Safety Review)"),
                        ],
                        default="A",
                        max_length=5,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="core.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Performance Scorecard",
                "verbose_name_plural": "Driver Performance Scorecards",
                "ordering": ["-month", "-overall_composite_score"],
                "unique_together": {("driver", "month", "period_type")},
            },
        ),
    ]
