# Generated by Django 6.0.2 on 2026-09-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("fleet_contracts", "0001_initial"),
        ("operations", "0001_initial"),
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateFastagAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="e.g. ICICI Corporate Master Wallet", max_length=255
                    ),
                ),
                ("account_number", models.CharField(max_length=100, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CorporatePetroAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(help_text="e.g. HPCL DriveTrack", max_length=255),
                ),
                ("account_number", models.CharField(max_length=100, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TripProfitReport",
            fields=[],
            options={
                "verbose_name": "Trip P&L Report",
                "verbose_name_plural": "Trip P&L Reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("operations.trip",),
        ),
        migrations.CreateModel(
            name="DriverAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_advances",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advances",
                        to="core.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_advances",
                        to="operations.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver money request",
                "verbose_name_plural": "Driver money requests",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DriverPayslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                ("days_present", models.PositiveIntegerField(default=30)),
                (
                    "basic_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "allowances",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "epf_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "esi_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "traffic_fines_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "advances_recovered",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="core.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverSalaryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("epf_number", models.CharField(blank=True, max_length=50)),
                ("esi_number", models.CharField(blank=True, max_length=50)),
                (
                    "epf_deduction_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=12.0,
                        help_text="Percentage of basic salary",
                        max_digits=5,
                    ),
                ),
                (
                    "esi_deduction_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.75,
                        help_text="Percentage of gross salary",
                        max_digits=5,
                    ),
                ),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_profile",
                        to="core.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_days", models.DecimalField(decimal_places=2, max_digits=5)),
                ("batta", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "advance_adjusted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("settled_on", models.DateField(blank=True, null=True)),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="core.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="operations.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("advance", "Advance"),
                            ("daily_pay", "Daily pay"),
                            ("settlement", "Settlement"),
                            ("salary", "Salary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("bank_transfer", "Bank transfer"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "cleaner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_payments",
                        to="core.cleaner",
                    ),
                ),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_payments",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_payments",
                        to="core.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_payments",
                        to="operations.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FastagRecharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recharges",
                        to="finance.corporatefastagaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FastagTollDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("toll_plaza", models.CharField(blank=True, max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deductions",
                        to="finance.corporatefastagaccount",
                    ),
                ),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="toll_deductions",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="toll_deductions",
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="toll_deductions",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FuelRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("opening_km", models.PositiveIntegerField(blank=True, null=True)),
                ("closing_km", models.PositiveIntegerField(blank=True, null=True)),
                ("api_reference_number", models.CharField(blank=True, max_length=100)),
                ("fuel_quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                ("fuel_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("fuel_station", models.CharField(blank=True, max_length=255)),
                (
                    "receipt",
                    models.FileField(blank=True, null=True, upload_to="fuel_receipts/"),
                ),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_records",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "petro_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_deductions",
                        to="finance.corporatepetroaccount",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_records",
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_records",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(max_length=255)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_adjustments",
                        to="core.party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("customer_receipt", "Customer receipt"),
                            ("supplier_payment", "Supplier payment"),
                            ("advance", "Advance"),
                            ("adjustment", "Adjustment"),
                            ("tds_receivable", "TDS Receivable"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("bank_transfer", "Bank transfer"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "collected_by",
                    models.CharField(
                        choices=[("company", "Company Cashier"), ("driver", "Driver")],
                        default="company",
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("bank", models.CharField(blank=True, max_length=100)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="operations.booking",
                    ),
                ),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.party",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="statements.generatedstatement",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="operations.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetroRecharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recharges",
                        to="finance.corporatepetroaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierTripCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_costs",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_trip_costs",
                        to="core.party",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_costs",
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_costs",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("toll", "Toll"),
                            ("permit", "Permit"),
                            ("parking", "Parking"),
                            ("epass", "E-Pass"),
                            ("border_tax", "Border tax"),
                            ("driver_food", "Driver food"),
                            ("hotel", "Hotel"),
                            ("water", "Water bottles"),
                            ("snacks", "Snacks"),
                            ("repair", "Repair"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("receipt", models.FileField(blank=True, upload_to="receipts/")),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("driver", "Driver"),
                            ("customer", "Customer"),
                        ],
                        default="company",
                        max_length=20,
                    ),
                ),
                ("billable_to_customer", models.BooleanField(default=True)),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="operations.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financier_name",
                    models.CharField(
                        help_text="e.g. HDFC Bank, Cholamandalam", max_length=255
                    ),
                ),
                ("loan_account_number", models.CharField(max_length=100, unique=True)),
                (
                    "total_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (e.g. 8.5)",
                        max_digits=5,
                    ),
                ),
                ("emi_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "emi_date_of_month",
                    models.PositiveIntegerField(
                        help_text="Day of the month the EMI is deducted (1-31)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverAdvanceAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="finance.driveradvance",
                    ),
                ),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advance_allocations",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advance_allocations",
                        to="operations.trip",
                    ),
                ),
            ],
            options={
                "unique_together": {("advance", "trip")},
            },
        ),
    ]
