# Generated by Django 6.0.2 on 2026-09-25 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. 1010, 1020, 1030, 1100, 2010, 4010, 5010",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("income", "Income"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chart of Account",
                "verbose_name_plural": "Chart of Accounts",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("date", models.DateField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("payment_receipt", "Payment Receipt"),
                            ("invoice_billing", "Invoice Billing"),
                            ("gateway_settlement", "Gateway Settlement"),
                            ("supplier_payout", "Supplier Payout"),
                            ("driver_salary", "Driver Salary"),
                            ("fuel_expense", "Fuel Expense"),
                            ("toll_charge", "Toll Charge"),
                            ("general", "General Journal"),
                        ],
                        default="payment_receipt",
                        max_length=30,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference Booking #, RZP ID, UTR, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "narration",
                    models.TextField(help_text="Detailed transaction narration"),
                ),
                ("is_posted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "General Ledger Journal Entry",
                "verbose_name_plural": "General Ledger Journal Entries",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JournalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("memo", models.CharField(blank=True, max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_items",
                        to="finance.account",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_items",
                        to="core.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Line Item",
                "verbose_name_plural": "Journal Line Items",
            },
        ),
    ]
