# Generated by Django 6.0.2 on 2026-09-25 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("finance", "0002_account_journalentry_journalitem"),
        ("fleet_contracts", "0003_transportcontract_category_specifications"),
        (
            "operations",
            "0006_trip_closing_odometer_photo_trip_driver_handover_at_and_more",
        ),
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateGSTInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("invoice_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("regular_b2b", "Regular B2B Tax Invoice"),
                            ("b2c", "B2C Retail Invoice"),
                            (
                                "sez_with_payment",
                                "SEZ Unit / Developer (With Tax Payment)",
                            ),
                            (
                                "sez_without_payment",
                                "SEZ Unit / Developer (Without Tax Payment / LUT)",
                            ),
                            ("deemed_export", "Deemed Export"),
                        ],
                        default="regular_b2b",
                        max_length=30,
                    ),
                ),
                (
                    "supplier_legal_name",
                    models.CharField(
                        default="Siva Gayathiri Tours & Travels", max_length=255
                    ),
                ),
                (
                    "supplier_trade_name",
                    models.CharField(default="Sivagayathiri Travels", max_length=255),
                ),
                (
                    "supplier_gstin",
                    models.CharField(default="33AAAAA0000A1Z5", max_length=15),
                ),
                (
                    "supplier_state_code",
                    models.CharField(
                        default="33", help_text="e.g. 33 for Tamil Nadu", max_length=2
                    ),
                ),
                (
                    "supplier_address",
                    models.TextField(
                        default="12/4, Gandhi Road, Chennai, Tamil Nadu - 600001"
                    ),
                ),
                ("supplier_pincode", models.CharField(default="600001", max_length=6)),
                ("recipient_legal_name", models.CharField(max_length=255)),
                ("recipient_trade_name", models.CharField(blank=True, max_length=255)),
                (
                    "recipient_gstin",
                    models.CharField(
                        blank=True,
                        help_text="15-character GSTIN. Blank if unregistered / B2C",
                        max_length=15,
                    ),
                ),
                (
                    "recipient_state_code",
                    models.CharField(
                        default="33",
                        help_text="2-digit state code of place of supply",
                        max_length=2,
                    ),
                ),
                ("recipient_address", models.TextField(blank=True)),
                ("recipient_pincode", models.CharField(blank=True, max_length=6)),
                (
                    "place_of_supply",
                    models.CharField(default="33-Tamil Nadu", max_length=100),
                ),
                (
                    "is_reverse_charge",
                    models.BooleanField(
                        default=False,
                        help_text="Tax payable under Reverse Charge (RCM)",
                    ),
                ),
                (
                    "sac_code",
                    models.CharField(
                        default="996601",
                        help_text="Transport Service Accounting Code (SAC)",
                        max_length=10,
                    ),
                ),
                (
                    "supply_type",
                    models.CharField(
                        choices=[
                            ("intra_state", "Intra-State (CGST + SGST)"),
                            ("inter_state", "Inter-State (IGST)"),
                        ],
                        default="intra_state",
                        max_length=20,
                    ),
                ),
                (
                    "taxable_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gst_rate_percent",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "igst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cess_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_invoice_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "qr_code_data",
                    models.TextField(
                        blank=True, help_text="B2B digital verification payload"
                    ),
                ),
                (
                    "qr_code_svg",
                    models.TextField(
                        blank=True, help_text="Vector SVG QR code representation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gl_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gst_invoices",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corporate_invoices",
                        to="core.party",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gst_invoices",
                        to="statements.generatedstatement",
                    ),
                ),
                (
                    "transport_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gst_invoices",
                        to="fleet_contracts.transportcontract",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gst_invoices",
                        to="operations.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate GST B2B Invoice",
                "verbose_name_plural": "Corporate GST B2B Invoices",
                "ordering": ["-invoice_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EWayBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eway_bill_number",
                    models.CharField(
                        blank=True,
                        help_text="12-digit NIC E-Way Bill Number",
                        max_length=12,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "eway_bill_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft / Generated"),
                            ("active", "Active & Valid"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "supply_type",
                    models.CharField(
                        default="O", help_text="O - Outward, I - Inward", max_length=10
                    ),
                ),
                (
                    "sub_supply_type",
                    models.CharField(default="1", help_text="1 - Supply", max_length=5),
                ),
                (
                    "doc_type",
                    models.CharField(
                        default="INV", help_text="INV - Tax Invoice", max_length=5
                    ),
                ),
                (
                    "transporter_id",
                    models.CharField(
                        blank=True, default="33AAAAA0000A1Z5", max_length=15
                    ),
                ),
                (
                    "transporter_name",
                    models.CharField(
                        default="Siva Gayathiri Tours & Travels", max_length=100
                    ),
                ),
                (
                    "trans_distance_km",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Approximate transportation distance in KM",
                    ),
                ),
                (
                    "trans_mode",
                    models.CharField(default="1", help_text="1 - Road", max_length=2),
                ),
                ("vehicle_number", models.CharField(max_length=20)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("R", "Regular"), ("O", "Over Dimensional Cargo")],
                        default="R",
                        max_length=2,
                    ),
                ),
                (
                    "nic_payload_json",
                    models.JSONField(
                        default=dict, help_text="NIC E-Way Bill Schema v1.04 JSON"
                    ),
                ),
                ("nic_response_json", models.JSONField(blank=True, default=dict)),
                ("qr_code_svg", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eway_bill",
                        to="finance.corporategstinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "NIC E-Way Bill",
                "verbose_name_plural": "NIC E-Way Bills",
                "ordering": ["-eway_bill_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_description", models.CharField(max_length=255)),
                ("sac_code", models.CharField(default="996601", max_length=10)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit", models.CharField(default="TRIP", max_length=10)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="finance.corporategstinvoice",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line Item",
                "verbose_name_plural": "Invoice Line Items",
            },
        ),
    ]
