# Generated by Django 6.0.2 on 2026-09-26 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("finance", "0003_corporategstinvoice_ewaybill_invoicelineitem"),
        ("operations", "0009_tripitineraryday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PettyCashAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="e.g. Coimbatore Main Depot Float or Driver Karthik Murugan",
                        max_length=255,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("branch", "🏢 Branch / Garage Float"),
                            ("driver", "🧑\u200d✈️ Driver / Tour Pilot Float"),
                            ("tour_manager", "🧭 Tour Manager / Guide Float"),
                            ("dispatcher", "📡 Dispatcher Emergency Float"),
                        ],
                        default="driver",
                        max_length=30,
                    ),
                ),
                (
                    "allocated_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        help_text="Maximum sanctioned float cap (₹)",
                        max_digits=12,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Live running available cash balance (₹)",
                        max_digits=12,
                    ),
                ),
                (
                    "warning_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=1500,
                        help_text="Low cash balance alert trigger (₹)",
                        max_digits=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "holder_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_petty_cash_accounts",
                        to="core.driver",
                    ),
                ),
                (
                    "holder_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_petty_cash_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Petty Cash Account",
                "verbose_name_plural": "Petty Cash Accounts (Floats)",
                "ordering": ["account_type", "account_name"],
            },
        ),
        migrations.CreateModel(
            name="PettyCashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(
                        blank=True,
                        help_text="e.g. PCV-2026-0001",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("top_up", "📥 Cash Top-Up / Replenishment (Inflow)"),
                            ("expense", "📤 Out-of-Pocket Expense (Outflow)"),
                            ("trip_advance", "🛣️ Trip Cash Advance Issued (Outflow)"),
                            (
                                "settlement_refund",
                                "🔁 Cash Surrender / Return (Inflow)",
                            ),
                            ("adjustment", "⚖️ Audit Balance Adjustment"),
                        ],
                        default="expense",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fuel", "⛽ Emergency Fuel / Diesel"),
                            (
                                "toll_parking",
                                "🛣️ Highway Toll & Airport/Station Parking",
                            ),
                            ("police_challan", "🚨 Spot Traffic Police Challan / Fine"),
                            (
                                "vehicle_repair",
                                "🔧 Emergency Tyre Puncture / Bulb / Breakdown",
                            ),
                            (
                                "driver_food",
                                "🍱 Driver Food / Batta / Night Halt Refreshment",
                            ),
                            (
                                "hotel_misc",
                                "🏨 Guest Porterage / Emergency Lodging / Tea",
                            ),
                            (
                                "office_supplies",
                                "📎 Stationery / Garage Cleaning / Consumables",
                            ),
                            ("client_entertain", "☕ Client Courtesy / Welcome Drinks"),
                            (
                                "top_up_receipt",
                                "💵 Cash Handover / Float Replenishment",
                            ),
                            ("other", "📝 Other Discretionary Expense"),
                        ],
                        default="toll_parking",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in ₹", max_digits=12
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Running float balance after transaction",
                        max_digits=12,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "recipient_or_vendor",
                    models.CharField(
                        blank=True,
                        help_text="Vendor or person paid/received e.g. NHAI Fastag Cash, Tyre Works",
                        max_length=255,
                    ),
                ),
                (
                    "receipt_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Bill receipt or voucher photograph",
                        null=True,
                        upload_to="petty_cash_receipts/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of purchase / reason",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Entry"),
                            ("submitted", "Pending Audit Review"),
                            ("approved", "✅ Audit Approved"),
                            ("rejected", "❌ Rejected"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("audit_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance.pettycashaccount",
                    ),
                ),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_petty_cash_txns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petty_cash_expenses",
                        to="operations.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Petty Cash Voucher Transaction",
                "verbose_name_plural": "Petty Cash Voucher Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
