# Generated by Django 6.0.2 on 2026-09-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_pettycashaccount_pettycashtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="pettycashaccount",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Initial float deposit (₹)",
                max_digits=12,
            ),
        ),
    ]
