# Generated by Django 5.1.15 on 2026-10-10 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_staffprofile"),
        ("finance", "0005_pettycashaccount_opening_balance"),
        ("operations", "0011_trip_driver_bata_breakdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatementUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[
                            ("generic", "Generic CSV Bank Feed"),
                            ("sbi", "State Bank of India (SBI)"),
                            ("hdfc", "HDFC Bank"),
                            ("icici", "ICICI Bank"),
                            ("axis", "Axis Bank"),
                            ("canara", "Canara Bank"),
                            ("kotak", "Kotak Mahindra Bank"),
                        ],
                        default="generic",
                        max_length=50,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                (
                    "statement_file",
                    models.FileField(
                        blank=True, null=True, upload_to="bank_statements/"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Company Bank Account or Virtual IBAN",
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("total_transactions", models.PositiveIntegerField(default=0)),
                ("auto_matched_count", models.PositiveIntegerField(default=0)),
                ("reconciled_count", models.PositiveIntegerField(default=0)),
                (
                    "total_deposits",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total credit inflows in ₹",
                        max_digits=14,
                    ),
                ),
                (
                    "total_withdrawals",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total debit outflows in ₹",
                        max_digits=14,
                    ),
                ),
                (
                    "reconciled_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount reconciled in ₹",
                        max_digits=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "📥 Uploaded / Pending Parse"),
                            ("analyzed", "🔍 Auto-Matched & Reviewed"),
                            ("partially_reconciled", "⚡ Partially Reconciled"),
                            ("reconciled", "✅ Fully Reconciled"),
                            ("archived", "📦 Archived"),
                        ],
                        default="uploaded",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_bank_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Statement Upload",
                "verbose_name_plural": "Bank Statement Uploads",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="BankStatementEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField(db_index=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                (
                    "narration",
                    models.TextField(help_text="Raw bank transaction narration string"),
                ),
                (
                    "reference_or_utr",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Extracted 12-digit UTR, IMPS, or UPI Ref No",
                        max_length=100,
                    ),
                ),
                (
                    "withdrawal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Debit / Outflow ₹",
                        max_digits=12,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Credit / Inflow ₹",
                        max_digits=12,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Running bank balance ₹",
                        max_digits=14,
                    ),
                ),
                (
                    "match_confidence",
                    models.PositiveIntegerField(
                        default=0, help_text="Confidence Score 0-100"
                    ),
                ),
                (
                    "match_reason",
                    models.CharField(
                        blank=True,
                        help_text="Rule that matched e.g. Exact 12-digit UTR, Amount + Customer Name",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unmatched", "⏳ Unmatched / Pending Review"),
                            ("matched", "🎯 Confirmed Match Ready"),
                            ("reconciled", "✅ Reconciled & Posted"),
                            ("ignored", "🚫 Ignored / Internal Transfer"),
                        ],
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("audit_notes", models.CharField(blank=True, max_length=255)),
                (
                    "matched_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_bank_entries",
                        to="operations.booking",
                    ),
                ),
                (
                    "matched_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_bank_entries",
                        to="finance.corporategstinvoice",
                    ),
                ),
                (
                    "matched_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_bank_entries",
                        to="core.party",
                    ),
                ),
                (
                    "matched_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_statement_entry",
                        to="finance.payment",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_bank_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="finance.bankstatementupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Statement Entry",
                "verbose_name_plural": "Bank Statement Entries",
                "ordering": ["-transaction_date", "-id"],
            },
        ),
    ]
