# Generated by Django 5.1.15 on 2026-10-10 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_party_party_rates_non_negative"),
        ("finance", "0006_bankstatementupload_bankstatemententry"),
        (
            "fleet_contracts",
            "0005_contracttriplog_contract_trip_closing_km_gte_opening_km_and_more",
        ),
        ("operations", "0012_alter_emergencyincidentalert_incident_type_and_more"),
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliertripcost",
            name="contract_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_costs",
                to="fleet_contracts.contracttriplog",
            ),
        ),
        migrations.AlterField(
            model_name="suppliertripcost",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_costs",
                to="operations.trip",
            ),
        ),
        migrations.AlterField(
            model_name="tripexpense",
            name="contract_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="fleet_contracts.contracttriplog",
            ),
        ),
        migrations.AlterField(
            model_name="tripexpense",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="operations.trip",
            ),
        ),
        migrations.AddConstraint(
            model_name="fuelrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("fuel_quantity__gte", 0), ("fuel_price__gte", 0)),
                name="fuel_record_qty_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fuelrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closing_km__isnull", True),
                    ("opening_km__isnull", True),
                    ("closing_km__gte", models.F("opening_km")),
                    _connector="OR",
                ),
                name="fuel_record_closing_km_gte_opening_km",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliertripcost",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="supplier_trip_cost_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="tripexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="trip_expense_amount_non_negative",
            ),
        ),
    ]
