# Generated by Django 5.1.15 on 2026-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_driver_idx_drv_status_type_and_more"),
        ("finance", "0007_alter_suppliertripcost_contract_trip_and_more"),
        (
            "fleet_contracts",
            "0005_contracttriplog_contract_trip_closing_km_gte_opening_km_and_more",
        ),
        ("operations", "0013_booking_booking_drop_date_gte_pickup_date_and_more"),
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fuelrecord",
            index=models.Index(
                fields=["vehicle", "date"], name="idx_fuel_vehicle_date"
            ),
        ),
        migrations.AddIndex(
            model_name="fuelrecord",
            index=models.Index(fields=["trip", "date"], name="idx_fuel_trip_date"),
        ),
        migrations.AddIndex(
            model_name="fuelrecord",
            index=models.Index(fields=["date"], name="idx_fuel_date"),
        ),
        migrations.AddIndex(
            model_name="ledgeradjustment",
            index=models.Index(fields=["party", "date"], name="idx_ladj_party_date"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["party", "payment_type"], name="idx_pmt_party_type"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["booking", "payment_type"], name="idx_pmt_booking_type"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["trip", "payment_type"], name="idx_pmt_trip_type"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["date", "payment_type"], name="idx_pmt_date_type"
            ),
        ),
    ]
