# Generated by Django 6.0.2 on 2026-09-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceDocument",
            fields=[],
            options={
                "verbose_name": "Compliance Document",
                "verbose_name_plural": "Compliance Documents",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("maintenance.compliancedocument",),
        ),
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[],
            options={
                "verbose_name": "Insurance Claim",
                "verbose_name_plural": "Insurance Claims",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("maintenance.insuranceclaim",),
        ),
    ]
