# Generated by Django 6.0.2 on 2026-09-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.client",),
        ),
        migrations.CreateModel(
            name="RateCard",
            fields=[],
            options={
                "verbose_name": "Rate card",
                "verbose_name_plural": "Rate cards",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.ratecard",),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.supplier",),
        ),
    ]
