# Generated by Django 6.0.2 on 2026-09-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverPayslip",
            fields=[],
            options={
                "verbose_name": "Driver Payslip",
                "verbose_name_plural": "Driver Payslips",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.driverpayslip",),
        ),
        migrations.CreateModel(
            name="DriverSalaryProfile",
            fields=[],
            options={
                "verbose_name": "Driver Salary Profile",
                "verbose_name_plural": "Driver Salary Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.driversalaryprofile",),
        ),
        migrations.CreateModel(
            name="EmployeePayment",
            fields=[],
            options={
                "verbose_name": "Staff Payment Voucher",
                "verbose_name_plural": "Staff Payment Vouchers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.employeepayment",),
        ),
    ]
