# Generated by Django 6.0.2 on 2026-09-25 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("finance", "0002_account_journalentry_journalitem"),
        ("operations", "0005_trip_tracking_token"),
        ("payments_gateway", "0001_initial"),
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGatewayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay Payments"),
                            ("cashfree", "Cashfree Payments"),
                            ("direct_upi", "Direct Dynamic UPI"),
                            ("offline", "Offline / Cash Desk"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_sandbox",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle between Sandbox/Test and Production Live mode",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, help_text="Key ID / App ID", max_length=150
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, help_text="Key Secret / Secret Key", max_length=150
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Shared secret for HMAC verification",
                        max_length=150,
                    ),
                ),
                (
                    "upi_vpa",
                    models.CharField(
                        default="sivagayathiritravels@icici",
                        help_text="Virtual Payment Address / UPI ID",
                        max_length=100,
                    ),
                ),
                (
                    "merchant_name",
                    models.CharField(
                        default="Sivagayathiri Travels",
                        help_text="Merchant Name displayed on UPI checkout apps",
                        max_length=150,
                    ),
                ),
                (
                    "mcc_code",
                    models.CharField(
                        default="4121",
                        help_text="Merchant Category Code (4121 = Passenger Transport)",
                        max_length=10,
                    ),
                ),
                (
                    "gateway_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.75,
                        help_text="Default MDR fee percentage (e.g. 1.75%)",
                        max_digits=5,
                    ),
                ),
                (
                    "gst_on_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="GST percentage on gateway fee (usually 18%)",
                        max_digits=5,
                    ),
                ),
                (
                    "auto_post_to_gl",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically post balanced Journal Entry to General Ledger on successful capture",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Gateway Configuration",
                "verbose_name_plural": "Payment Gateway Configurations",
            },
        ),
        migrations.CreateModel(
            name="GatewayTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("cashfree", "Cashfree"),
                            ("direct_upi", "Direct Dynamic UPI"),
                        ],
                        max_length=30,
                    ),
                ),
                ("gateway_order_id", models.CharField(blank=True, max_length=100)),
                (
                    "gateway_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="External payment ID or UPI 12-digit UTR/RRN",
                        max_length=100,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending Verification"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured & Cleared"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "upi_intent_url",
                    models.TextField(
                        blank=True, help_text="Indian NPCI UPI intent URL"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gateway_transactions",
                        to="operations.booking",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gateway_transaction",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gateway_transactions",
                        to="core.party",
                    ),
                ),
                (
                    "payment_record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gateway_transaction",
                        to="finance.payment",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gateway_transactions",
                        to="statements.generatedstatement",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gateway_transactions",
                        to="operations.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gateway Transaction",
                "verbose_name_plural": "Gateway Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
