# Generated by Django 6.0.2 on 2026-09-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packageinventory",
            options={
                "verbose_name": "Tour Bus Departure Batch",
                "verbose_name_plural": "Tour Bus Departure Batches",
            },
        ),
        migrations.AddField(
            model_name="itineraryday",
            name="evening_night_activity",
            field=models.TextField(
                blank=True, help_text="e.g. Proceed to Coorg, dinner, DJ with Campfire"
            ),
        ),
        migrations.AddField(
            model_name="itineraryday",
            name="morning_activity",
            field=models.TextField(
                blank=True, help_text="e.g. Check in to hotel, refreshment"
            ),
        ),
        migrations.AddField(
            model_name="itineraryday",
            name="night_stay_location",
            field=models.CharField(
                blank=True, help_text="e.g. Hotel / Resort in Coorg", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="itineraryday",
            name="route_segment",
            field=models.CharField(
                blank=True,
                help_text="e.g. Coimbatore to Mysore by luxurious bus",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="itineraryday",
            name="sightseeing_spots",
            field=models.TextField(
                blank=True,
                help_text="e.g. Mysore Palace, Brindavan Garden, KRS Dam, St. Philomena's Cathedral",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="bus_amenities_desc",
            field=models.CharField(
                default="52/54 seated bus, 1 Driver & 1 cleaner, Laser Light, JBL Sound systems, First aid kit",
                help_text="Bus amenities shown on quote",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="category",
            field=models.CharField(
                choices=[
                    ("college_iv", "🎓 College / School Industrial Visit (IV)"),
                    ("local_tour", "🚗 Local 1-Day Sightseeing / Temple Tour"),
                    (
                        "hill_station",
                        "⛰️ Hill Station Getaway (Ooty, Kodaikanal, Coorg)",
                    ),
                    ("fixed_departure", "🚌 Fixed Departure Tour Bus Trip"),
                    ("pilgrimage", "🕉️ Pilgrimage & Spiritual Circuit"),
                    ("corporate_offsite", "🏢 Corporate Outing / Team Offsite"),
                    ("family_vacation", "💐 Family & Custom Vacation Package"),
                ],
                default="college_iv",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="complementary_staff_count",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Number of complimentary faculty/staff traveling free (e.g. 50 + 2 staffs)",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="contact_persons_footer",
            field=models.TextField(
                default="MohanRaj.P (967 7707 912), DHARUN (8072676975), VIKRANT (9994018140)",
                help_text="Staff names and mobile numbers printed in quotation sign-off",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="default_vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_packages",
                to="core.vehicletype",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="exclusions",
            field=models.TextField(
                default="Natural disturbance if any.\nAny damages or breakages.\nOptional tours if any.\nFirst aid kit.\nPersonal expenses.\nCompany expenses.",
                help_text="Items excluded from tour cost (one per line)",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="has_boating",
            field=models.BooleanField(
                default=False, verbose_name="Boating / Trekking Included"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="has_campfire_dj",
            field=models.BooleanField(
                default=True, verbose_name="DJ with Campfire Included"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="has_industrial_visit",
            field=models.BooleanField(
                default=True, verbose_name="College IV Clearance Included"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="has_jeep_safari",
            field=models.BooleanField(
                default=True,
                verbose_name="Jeep Safari Included (e.g. Mullayanagiri Peak)",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="hotel_star_category",
            field=models.CharField(
                default="Star Category Hotel & Resort",
                help_text="e.g. Star Category / 3-Star Resort",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="inclusions",
            field=models.TextField(
                default="Tamilnadu-Karnataka-by bus.\nAll parking, toll gate & permit charges.\nAccommodation on sharing basis in hotel and resort.\nAll transfer & transportation.\nAll sightseeing as per the itinerary based on time.\nTour in charge from Sivagayathiri Travels / Holiday Planerz.\nGuide service.\nLocal entrances.\nDJ with campfire.\nJeep safari.",
                help_text="Items covered in tour cost (one per line)",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="meal_plan",
            field=models.CharField(
                choices=[
                    ("AP", "AP Plan (All Meals: Breakfast, Lunch, Dinner)"),
                    ("MAP", "MAP Plan (Modified: Breakfast + Dinner)"),
                    ("CP", "CP Plan (Continental: Bed & Breakfast Only)"),
                    ("EP", "EP Plan (European: Room Only / Without Food)"),
                ],
                default="AP",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="min_pax",
            field=models.PositiveIntegerField(
                default=50, help_text="Standard group size (e.g. 50 members)"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="package_code",
            field=models.CharField(
                blank=True, help_text="e.g. PKG-MY-CRG-03D", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="price_with_food",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tour cost per person WITH food / AP Plan (e.g. ₹5,700)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="price_without_food",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tour cost per person WITHOUT food / EP Plan (e.g. ₹4,600)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("per_person", "Per Person / Head Rate (with/without food)"),
                    ("vehicle_rate", "Per Vehicle Hire Rate (Local 1-N Day)"),
                    ("lump_sum", "Lump Sum Group Contract Rate"),
                ],
                default="per_person",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="room_sharing_type",
            field=models.CharField(
                choices=[
                    ("4_sharing", "4 Sharing (Quad) - Standard for Students & IV"),
                    ("3_sharing", "3 Sharing (Triple)"),
                    ("twin_sharing", "Twin Sharing (2 Pax)"),
                    ("single", "Single Occupancy"),
                ],
                default="4_sharing",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="terms_and_conditions",
            field=models.TextField(
                default="Camp Fire & Boating Subject to weather Conditions.\nPlaying in Sea / Pool is at Customers Own risk.\nPayment - 50% advance while confirming the Trip & rest 50% before starting the trip.\nAny damages caused by the tour members to the vehicle or to any of the properties at the resort should be paid before the end of the trip.\nAll sightseeing can be seen only according to the road and other situation during the trip.\nITINERARY can be changed to customer's interest and comfort.\nTour members are requested to co-operate with us to maintain the timings of Itinerary to serve you better.\nCustomers drunk will not be allowed for Trekking.",
                help_text="Terms & Conditions for quotation sheet",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="vehicle_seating_desc",
            field=models.CharField(
                default="Non AC 54 seated Luxurious Bus",
                help_text="e.g. Non AC 54 seated / 52 Seated AC Coach",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="packageinventory",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tour_inventories",
                to="core.driver",
            ),
        ),
        migrations.AddField(
            model_name="packageinventory",
            name="assigned_vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tour_inventories",
                to="core.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="packageinventory",
            name="booked_seats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="packageinventory",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("college_iv", "🎓 College / School Industrial Visit (IV)"),
                    ("local_tour", "🚗 Local 1-Day Sightseeing / Temple Tour"),
                    (
                        "hill_station",
                        "⛰️ Hill Station Getaway (Ooty, Kodaikanal, Coorg)",
                    ),
                    ("fixed_departure", "🚌 Fixed Departure Tour Bus Trip"),
                    ("pilgrimage", "🕉️ Pilgrimage & Spiritual Circuit"),
                    ("corporate_offsite", "🏢 Corporate Outing / Team Offsite"),
                    ("family_vacation", "💐 Family & Custom Vacation Package"),
                ],
                default="hill_station",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="itineraryday",
            name="activities",
            field=models.TextField(blank=True, help_text="Full day plan description"),
        ),
        migrations.AlterField(
            model_name="itineraryday",
            name="day_number",
            field=models.IntegerField(
                default=1, help_text="0 for overnight journey (Day 00), 1, 2, 3..."
            ),
        ),
        migrations.AlterField(
            model_name="itineraryday",
            name="hotel_info",
            field=models.CharField(
                blank=True, help_text="Suggested hotel or resort name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="itineraryday",
            name="meals_included",
            field=models.CharField(
                default="Breakfast, Lunch, Dinner",
                help_text="e.g. Breakfast, Lunch, Dinner",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="itineraryday",
            name="title",
            field=models.CharField(
                help_text="e.g. Arriving Mysore - KRS Dam - Proceed Coorg",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="itineraryday",
            name="transport_info",
            field=models.CharField(
                blank=True,
                help_text="e.g. 54-Seated Bus Transfer / 4x4 Jeep Safari",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Default display rate",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="destination",
            field=models.CharField(
                help_text="e.g. TAMILNADU/KARNATAKA", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=3, help_text="Number of Days (e.g. 3 days)"
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="duration_nights",
            field=models.PositiveIntegerField(
                default=2, help_text="Number of Nights (e.g. 2 nights)"
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(
                help_text="e.g. 2 NIGHTS 3 DAYS MYSORE-COORG-CHIKMANGALUR",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="packageinventory",
            name="available_seats",
            field=models.PositiveIntegerField(default=52),
        ),
        migrations.AlterField(
            model_name="packageinventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "🟢 Open for Booking"),
                    ("fast_filling", "🟡 Fast Filling (Few Seats Left)"),
                    ("sold_out", "🔴 Sold Out / Full"),
                    ("departed", "🚍 Departed / On Route"),
                    ("completed", "✅ Tour Completed"),
                    ("cancelled", "❌ Cancelled"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="packageinventory",
            name="total_seats",
            field=models.PositiveIntegerField(default=52),
        ),
        migrations.AlterField(
            model_name="packagetemplate",
            name="destination",
            field=models.CharField(
                help_text="e.g. Tamilnadu / Karnataka", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="packagetemplate",
            name="duration_days",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="packagetemplate",
            name="duration_nights",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="packagetemplate",
            name="name",
            field=models.CharField(
                help_text="e.g. Mysore - Coorg - Chikmagalur Circuit", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="BoardingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_order", models.PositiveIntegerField(default=1)),
                (
                    "stop_name",
                    models.CharField(
                        help_text="e.g. Coimbatore Gandhipuram Bus Stand",
                        max_length=200,
                    ),
                ),
                ("pickup_time", models.TimeField(help_text="e.g. 05:30 AM")),
                (
                    "landmark",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Opposite SETC Bus Stand",
                        max_length=255,
                    ),
                ),
                (
                    "coordinator_phone",
                    models.CharField(
                        blank=True, help_text="Pickup coordinator mobile", max_length=30
                    ),
                ),
                (
                    "departure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_points",
                        to="packages.packageinventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour Boarding Point",
                "verbose_name_plural": "Tour Boarding Points",
                "ordering": ["departure", "stop_order"],
            },
        ),
        migrations.CreateModel(
            name="CollegeIVExpedition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "college_name",
                    models.CharField(
                        help_text="e.g. PSG College of Technology", max_length=255
                    ),
                ),
                (
                    "department_and_batch",
                    models.CharField(
                        help_text="e.g. B.E. Mechanical Engineering (Batch 2023-27)",
                        max_length=200,
                    ),
                ),
                (
                    "faculty_incharge_name",
                    models.CharField(
                        help_text="HOD / Faculty Coordinator Name", max_length=150
                    ),
                ),
                (
                    "faculty_incharge_phone",
                    models.CharField(help_text="Direct mobile number", max_length=30),
                ),
                ("student_count_male", models.PositiveIntegerField(default=30)),
                ("student_count_female", models.PositiveIntegerField(default=20)),
                (
                    "faculty_count",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Accompanying faculty/staff (Traveling free)",
                    ),
                ),
                (
                    "total_pax",
                    models.PositiveIntegerField(
                        default=52, help_text="Total group size (Students + Faculty)"
                    ),
                ),
                (
                    "industry_visit_targets",
                    models.TextField(
                        help_text="Factories/plants to visit (e.g. Ashok Leyland Hosur, Tea Factory Ooty, ISRO)"
                    ),
                ),
                (
                    "permission_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("letter_submitted", "Letter Submitted to Industry HR"),
                            ("approved", "Official Industry Clearance Approved"),
                            ("completed", "Industrial Visit Completed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "permission_letter_file",
                    models.FileField(
                        blank=True,
                        help_text="Signed college permission letter / company gate pass",
                        null=True,
                        upload_to="college_iv/letters/",
                    ),
                ),
                (
                    "bus_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of buses in the convoy"
                    ),
                ),
                (
                    "tour_manager_assigned",
                    models.CharField(
                        blank=True,
                        default="MohanRaj P.",
                        help_text="Tour manager traveling with the students",
                        max_length=150,
                    ),
                ),
                (
                    "has_dj_campfire",
                    models.BooleanField(
                        default=True, verbose_name="DJ & Campfire Arrangement"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inquiry", "📝 Quotation / Initial Inquiry"),
                            (
                                "letter_submitted",
                                "📄 Industry Permission Letter Submitted",
                            ),
                            ("confirmed", "✅ Confirmed & Booked"),
                            ("on_tour", "🚍 On Tour / Traveling"),
                            ("completed", "🎉 Tour Completed"),
                            ("cancelled", "❌ Cancelled"),
                        ],
                        default="confirmed",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="college_iv_trips",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "verbose_name": "College Industrial Visit (IV) Expedition",
                "verbose_name_plural": "College IV Expeditions",
            },
        ),
        migrations.CreateModel(
            name="TourPassengerManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_name", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("faculty", "Faculty / Staff (Complimentary)"),
                            ("adult", "Adult"),
                            ("child", "Child"),
                            ("senior", "Senior Citizen"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                (
                    "seat_number",
                    models.CharField(
                        blank=True, help_text="e.g. 12A, 12B", max_length=10
                    ),
                ),
                (
                    "room_sharing_number",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Room 204 (4 Sharing)",
                        max_length=100,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        help_text="Parent / Emergency contact number",
                        max_length=150,
                    ),
                ),
                (
                    "boarding_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="packages.boardingpoint",
                    ),
                ),
                (
                    "departure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="packages.packageinventory",
                    ),
                ),
                (
                    "iv_expedition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_manifest",
                        to="packages.collegeivexpedition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour Passenger & Rooming Entry",
                "verbose_name_plural": "Tour Passenger Manifest & Rooming List",
            },
        ),
        migrations.CreateModel(
            name="PackageVehicleTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Full package vehicle hire rate",
                        max_digits=10,
                    ),
                ),
                (
                    "included_km",
                    models.PositiveIntegerField(
                        default=300, help_text="KMs included in this package"
                    ),
                ),
                (
                    "extra_km_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=16.0,
                        help_text="Rate per extra KM beyond package",
                        max_digits=6,
                    ),
                ),
                ("driver_bata_included", models.BooleanField(default=True)),
                ("toll_parking_included", models.BooleanField(default=True)),
                ("interstate_permit_included", models.BooleanField(default=False)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_tariffs",
                        to="packages.package",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_tariffs",
                        to="core.vehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle-Wise Tariff",
                "verbose_name_plural": "Vehicle-Wise Tariffs",
                "unique_together": {("package", "vehicle_type")},
            },
        ),
    ]
