# Generated by Django 6.0.2 on 2026-09-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_alter_packageinventory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packagevehicletariff",
            options={
                "verbose_name": "Vehicle-Wise Tariff",
                "verbose_name_plural": "Vehicle-Wise Tariffs (4 to 60 Seats)",
            },
        ),
        migrations.AddField(
            model_name="package",
            name="currency_code",
            field=models.CharField(
                choices=[
                    ("INR", "₹ INR (Indian Rupee)"),
                    ("AED", "AED (UAE Dirham)"),
                    ("SGD", "SGD (Singapore Dollar)"),
                    ("MYR", "MYR (Malaysian Ringgit)"),
                    ("THB", "THB (Thai Baht)"),
                    ("USD", "$ USD (US Dollar)"),
                    ("EUR", "€ EUR (Euro)"),
                ],
                default="INR",
                help_text="Primary currency for local tour expenses",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="destination_country",
            field=models.CharField(
                blank=True,
                help_text="e.g. Dubai, UAE / Singapore & Malaysia / Thailand / Sri Lanka",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="flight_details_note",
            field=models.CharField(
                blank=True,
                help_text="e.g. Indigo / Air India Express Ex-Coimbatore or Chennai",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="flight_inclusive",
            field=models.BooleanField(
                default=False, verbose_name="Flight Airfare Included in Package"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="is_devotional",
            field=models.BooleanField(
                default=False, verbose_name="🕉️ Devotional / Pilgrimage Circuit"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="is_international",
            field=models.BooleanField(
                default=False, verbose_name="✈️ International Tour Package"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="overseas_dmc_partner",
            field=models.CharField(
                blank=True,
                help_text="Local overseas Destination Management Company (DMC)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="passport_validity_months",
            field=models.PositiveIntegerField(
                default=6,
                help_text="Minimum passport validity required (usually 6 months)",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="satvik_pure_veg_meals",
            field=models.BooleanField(
                default=False,
                verbose_name="100% Pure Vegetarian / Satvik Meals Guaranteed",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="senior_citizen_friendly",
            field=models.BooleanField(
                default=False,
                verbose_name="Senior Citizen Care (Wheelchair / Low-Step Bus)",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="temple_darshan_info",
            field=models.TextField(
                blank=True,
                help_text="Temple darshan procedures, special entry tickets, pooja timings",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="temple_dress_code",
            field=models.CharField(
                default="Traditional Dhoti/Kurta for Men, Saree/Chudidar for Women",
                help_text="Temple dress code requirements",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="visa_guidelines",
            field=models.TextField(
                blank=True,
                help_text="Visa application steps, tourist eVisa, processing duration",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="visa_required",
            field=models.BooleanField(default=False, verbose_name="Visa Required"),
        ),
        migrations.AddField(
            model_name="packagevehicletariff",
            name="double_driver_included",
            field=models.BooleanField(
                default=False,
                verbose_name="Double Driver Assigned (Overnight / Long-Haul > 500 km)",
            ),
        ),
        migrations.AddField(
            model_name="packagevehicletariff",
            name="driver_bata_per_day",
            field=models.DecimalField(
                decimal_places=2,
                default=500,
                help_text="Driver day bata allowance",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="packagevehicletariff",
            name="extra_hour_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Rate per extra hour beyond local package",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="packagevehicletariff",
            name="local_package_hours",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Included hours for 1-Day Local Package (e.g. 8 or 10 hrs)",
            ),
        ),
        migrations.AddField(
            model_name="packagevehicletariff",
            name="night_halt_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Night halt charge (10:00 PM to 06:00 AM)",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="packagevehicletariff",
            name="per_day_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Per day vehicle hire rate for multi-day tours",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="packagevehicletariff",
            name="rate_type",
            field=models.CharField(
                choices=[
                    (
                        "outstation_multiday",
                        "Outstation Multi-Day (Per-Day Rate + Included KMs)",
                    ),
                    (
                        "local_1day",
                        "1-Day Local Package (8 Hr / 80 Km or 10 Hr / 100 Km)",
                    ),
                    ("lumpsum_fixed", "Lump Sum Fixed Route Package Rate"),
                ],
                default="outstation_multiday",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="packagevehicletariff",
            name="seating_tier",
            field=models.CharField(
                choices=[
                    ("4_sedan", "Compact Sedan (4 Seats - Dzire, Etios)"),
                    (
                        "7_crysta",
                        "Premium MPV / SUV (6-7 Seats - Innova Crysta, Hycross)",
                    ),
                    (
                        "17_tt_urbania",
                        "Executive Van (12-17 Seats - Force Urbania, Tempo Traveller)",
                    ),
                    (
                        "26_force_coach",
                        "Maxi Coach (20-26 Seats - Force Traveller, Mini Coach)",
                    ),
                    ("36_mini_bus", "Deluxe Mini Bus (32-36 Seats)"),
                    (
                        "54_luxury_coach",
                        "Luxury Tour Coach (50-54 Seats - Non-AC / AC)",
                    ),
                    (
                        "60_super_coach",
                        "Super Coach (55-60 Seats - Long Distance Convoy)",
                    ),
                ],
                default="4_sedan",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tourpassengermanifest",
            name="passport_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tourpassengermanifest",
            name="passport_number",
            field=models.CharField(
                blank=True,
                help_text="Required for International Packages",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tourpassengermanifest",
            name="senior_assistance_needed",
            field=models.BooleanField(
                default=False,
                verbose_name="Senior Citizen Wheelchair / Special Assistance",
            ),
        ),
        migrations.AddField(
            model_name="tourpassengermanifest",
            name="visa_number",
            field=models.CharField(
                blank=True, help_text="Tourist eVisa / Entry Pass Number", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="collegeivexpedition",
            name="tour_manager_assigned",
            field=models.CharField(
                blank=True,
                default="Rithik CA / Anandh C",
                help_text="Tour manager traveling with the students",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="category",
            field=models.CharField(
                choices=[
                    ("holiday", "🏖️ Holiday & Hill Station Getaway (1-N Days)"),
                    ("devotional", "🕉️ Devotional & Pilgrimage Tour (Temple Circuits)"),
                    ("college_iv", "🎓 College / School Industrial Visit (IV)"),
                    (
                        "international",
                        "✈️ International Tour Package (Passports & Visas)",
                    ),
                    ("local_tour", "🚗 Local 1-Day Sightseeing / Temple Darshan"),
                    ("fixed_departure", "🚌 Fixed Departure Group Tour Bus Trip"),
                    ("corporate_offsite", "🏢 Corporate Outing / Team Offsite"),
                    ("family_vacation", "💐 Family & Custom Vacation Package"),
                    (
                        "hill_station",
                        "⛰️ Hill Station Getaway (Ooty, Kodaikanal, Coorg)",
                    ),
                    ("pilgrimage", "🕉️ Pilgrimage & Spiritual Circuit"),
                ],
                default="college_iv",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="contact_persons_footer",
            field=models.TextField(
                default="Rithik CA (+91 98425 33777), Anandh C (+91 94381 7131 / +91 38209 9979)",
                help_text="Staff names and mobile numbers printed in quotation sign-off",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="inclusions",
            field=models.TextField(
                default="Tamilnadu-Karnataka-by bus.\nAll parking, toll gate & permit charges.\nAccommodation on sharing basis in hotel and resort.\nAll transfer & transportation.\nAll sightseeing as per the itinerary based on time.\nTour in charge from Siva Gayathri Tours and Travels.\nGuide service.\nLocal entrances.\nDJ with campfire.\nJeep safari.",
                help_text="Items covered in tour cost (one per line)",
            ),
        ),
        migrations.AlterField(
            model_name="packagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("holiday", "🏖️ Holiday & Hill Station Getaway (1-N Days)"),
                    ("devotional", "🕉️ Devotional & Pilgrimage Tour (Temple Circuits)"),
                    ("college_iv", "🎓 College / School Industrial Visit (IV)"),
                    (
                        "international",
                        "✈️ International Tour Package (Passports & Visas)",
                    ),
                    ("local_tour", "🚗 Local 1-Day Sightseeing / Temple Darshan"),
                    ("fixed_departure", "🚌 Fixed Departure Group Tour Bus Trip"),
                    ("corporate_offsite", "🏢 Corporate Outing / Team Offsite"),
                    ("family_vacation", "💐 Family & Custom Vacation Package"),
                    (
                        "hill_station",
                        "⛰️ Hill Station Getaway (Ooty, Kodaikanal, Coorg)",
                    ),
                    ("pilgrimage", "🕉️ Pilgrimage & Spiritual Circuit"),
                ],
                default="hill_station",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="packagevehicletariff",
            name="package_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total hire rate (or 1-day package rate)",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="InternationalDocumentChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="e.g. Passport copy (min 6 months validity), 35x45mm white background photo",
                        max_length=150,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "submission_deadline_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Days prior to departure for submission"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Scanned copy in PDF/JPEG under 2MB",
                        max_length=255,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intl_documents",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "verbose_name": "International Document Requirement",
                "verbose_name_plural": "International Document Checklist",
            },
        ),
        migrations.CreateModel(
            name="TempleDarshanSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temple_name",
                    models.CharField(
                        help_text="e.g. Tirumala Venkateswara Temple / Palani Dhandayuthapani / Madurai Meenakshi",
                        max_length=200,
                    ),
                ),
                (
                    "deity_or_circuit",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Lord Balaji / Navagraha Suryanar Kovil / Arupadai Veedu",
                        max_length=150,
                    ),
                ),
                (
                    "darshan_type",
                    models.CharField(
                        choices=[
                            (
                                "special_entry_300",
                                "Special Entry Darshan (₹300 / Fast Track)",
                            ),
                            ("vip_break", "VIP Break / Protocol Darshan"),
                            ("general", "General Sarva Darshanam"),
                            ("abhishekam_seva", "Abhishekam / Archanai Seva"),
                            ("virtual_q", "Virtual Q Token Pass (Sabarimala / Palani)"),
                            ("winch_ropeway", "Ropeway / Winch / Battery Car Pass"),
                        ],
                        default="special_entry_300",
                        max_length=30,
                    ),
                ),
                (
                    "booked_slot_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 09:30 AM - 10:30 AM Slot",
                        max_length=100,
                    ),
                ),
                (
                    "token_ticket_number",
                    models.CharField(
                        blank=True,
                        help_text="e.g. TTD-2025-SE-98421 / Palani Token #44",
                        max_length=100,
                    ),
                ),
                (
                    "reporting_location",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Vaikuntam Queue Complex 1 / North Gate",
                        max_length=200,
                    ),
                ),
                (
                    "dress_code_notes",
                    models.CharField(
                        default="Strict Traditional: Dhoti/Kurta for Men, Saree/Chudidar for Women",
                        max_length=255,
                    ),
                ),
                (
                    "prasad_details",
                    models.CharField(
                        blank=True,
                        default="Special Laddu / Panchamirtham Prasadam Included",
                        max_length=255,
                    ),
                ),
                (
                    "senior_citizen_support",
                    models.BooleanField(
                        default=True,
                        verbose_name="Wheelchair / Battery Buggy Assistance Available",
                    ),
                ),
                (
                    "itinerary_day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temple_slots",
                        to="packages.itineraryday",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temple_slots",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temple Darshan Slot",
                "verbose_name_plural": "Temple & Darshan Slots",
            },
        ),
    ]
