# Generated by Django 6.0.2 on 2026-09-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0003_alter_packagevehicletariff_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="room_sharing_type",
            field=models.CharField(
                choices=[
                    ("twin_sharing", "Twin Sharing (2 Pax) - Couples & Staff"),
                    ("3_sharing", "3 Sharing (Triple) - Standard Family"),
                    ("4_sharing", "4 Sharing (Quad) - Standard IV & Youth Groups"),
                    ("6_sharing", "6 Sharing (Family Suite / 6-Bed Room)"),
                    ("8_sharing", "8 Sharing (Group Cottage / Private Villa)"),
                    ("dormitory", "Dormitory / Bunk Beds / Group Hall (10+ Pax)"),
                    (
                        "mixed_custom",
                        "Custom Mixed Sharing (Twin, Quad, Suites as per Hotel)",
                    ),
                    ("single", "Single Occupancy"),
                ],
                default="4_sharing",
                max_length=50,
            ),
        ),
    ]
