# Generated by Django 6.0.2 on 2026-09-17 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0004_alter_package_room_sharing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourpassengermanifest",
            name="bus_assignment",
            field=models.CharField(
                blank=True, help_text="e.g. Bus 01, Bus 02", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="tourpassengermanifest",
            name="roll_number",
            field=models.CharField(
                blank=True,
                help_text="College Roll Number / Student Register ID",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tourpassengermanifest",
            name="departure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passengers",
                to="packages.packageinventory",
            ),
        ),
    ]
