# Generated by Django 6.0.2 on 2026-09-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_alter_trafficfine_financial_responsibility_and_more"),
        ("packages", "0005_tourpassengermanifest_bus_assignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collegeivexpedition",
            name="aadhaar_id_mandatory",
            field=models.BooleanField(
                default=True,
                verbose_name="Govt Photo ID / Aadhaar Mandatory for Check-in",
            ),
        ),
        migrations.AddField(
            model_name="collegeivexpedition",
            name="baggage_allowance",
            field=models.CharField(
                blank=True,
                default="15 kg Check-in + 7 kg Cabin Baggage per passenger",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="collegeivexpedition",
            name="destination_city",
            field=models.CharField(
                blank=True, default="Delhi / Agra / Jaipur", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="collegeivexpedition",
            name="destination_coach_partner",
            field=models.CharField(
                blank=True,
                help_text="Destination DMC / Coach fleet provider in destination city",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="collegeivexpedition",
            name="linked_trip",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked Operational Trip dispatched for this expedition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="college_iv_expeditions",
                to="operations.trip",
            ),
        ),
        migrations.AddField(
            model_name="collegeivexpedition",
            name="onward_transit_details",
            field=models.CharField(
                blank=True,
                help_text="e.g. IndiGo 6E-241 (CJB 08:30 AM -> DEL 11:20 AM) or Train #12678",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="collegeivexpedition",
            name="reporting_terminal",
            field=models.CharField(
                blank=True,
                default="Coimbatore International Airport (CJB) - Terminal 1",
                help_text="Assembly point for departure",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="collegeivexpedition",
            name="return_transit_details",
            field=models.CharField(
                blank=True,
                help_text="e.g. IndiGo 6E-242 (DEL 07:45 PM -> CJB 10:35 PM) or Return Train details",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="collegeivexpedition",
            name="transit_mode",
            field=models.CharField(
                choices=[
                    ("road_coach", "🚌 All-Way Road Coach (Ex-Garage Convoy)"),
                    ("flight_coach", "✈️ Flight + Destination Coach (Fly-Bus Tour)"),
                    ("train_coach", "🚆 Train + Destination Coach (Rail-Bus Tour)"),
                    (
                        "land_only",
                        "📍 Land Package Only (Ex-Destination Airport/Station)",
                    ),
                ],
                default="road_coach",
                max_length=30,
                verbose_name="Tour Transit Mode",
            ),
        ),
        migrations.AddField(
            model_name="collegeivexpedition",
            name="transit_pnr_or_booking_ref",
            field=models.CharField(
                blank=True,
                help_text="Airline Group PNR / IRCTC PNR (e.g. Q8W9XY)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="flight_estimate_per_pax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated return flight fare per person (e.g. ₹9,500 CJB-DEL-CJB)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="train_estimate_per_pax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated return train fare per person (e.g. ₹2,200 3AC)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="transit_mode",
            field=models.CharField(
                choices=[
                    ("road_coach", "🚌 All-Way Road Coach (Ex-Garage Convoy)"),
                    ("flight_coach", "✈️ Flight + Destination Coach (Fly-Bus Tour)"),
                    ("train_coach", "🚆 Train + Destination Coach (Rail-Bus Tour)"),
                    (
                        "land_only",
                        "📍 Land Package Only (Ex-Destination Airport/Station)",
                    ),
                ],
                default="road_coach",
                max_length=30,
                verbose_name="Tour Transit Mode",
            ),
        ),
        migrations.AddField(
            model_name="tourpassengermanifest",
            name="aadhaar_number",
            field=models.CharField(
                blank=True,
                help_text="Aadhaar / Govt Photo ID number for Flight/Train e-Boarding",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tourpassengermanifest",
            name="ticket_or_pnr_status",
            field=models.CharField(
                blank=True,
                default="Confirmed",
                help_text="Ticket / Group PNR status",
                max_length=50,
            ),
        ),
    ]
