# Generated by Django 6.0.2 on 2026-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0006_collegeivexpedition_aadhaar_id_mandatory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collegeivexpedition",
            name="baggage_allowance",
            field=models.CharField(
                blank=True,
                help_text="e.g. 15 kg Check-in + 7 kg Cabin Baggage per passenger",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="collegeivexpedition",
            name="destination_city",
            field=models.CharField(
                blank=True,
                help_text="Destination city for flight/coach (e.g. Delhi / Agra / Jaipur)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="collegeivexpedition",
            name="reporting_terminal",
            field=models.CharField(
                blank=True,
                help_text="Assembly point for departure (e.g. Coimbatore Airport CJB or CBE Junction)",
                max_length=200,
            ),
        ),
    ]
