# Generated by Django 6.0.2 on 2026-09-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0007_alter_collegeivexpedition_baggage_allowance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="category",
            field=models.CharField(
                choices=[
                    ("devotional", "🕉️ Devotional & Pilgrimage Tour (Temple Circuits)"),
                    ("college_iv", "🎓 College / School Industrial Visit (IV)"),
                    (
                        "international",
                        "✈️ International Tour Package (Passports & Visas)",
                    ),
                    (
                        "hill_station",
                        "⛰️ Hill Station Getaway (Ooty, Kodaikanal, Munnar, Coorg)",
                    ),
                    (
                        "holiday",
                        "🏖️ Leisure & Beach Holiday (Goa, Pondicherry, Kerala)",
                    ),
                    ("local_tour", "🚗 Local 1-Day Sightseeing / Hourly Rental"),
                    ("family_vacation", "💐 Family & Custom Vacation Package"),
                    ("corporate_offsite", "🏢 Corporate Outing & Team Building"),
                    ("fixed_departure", "🚌 Fixed Departure Group Bus Trip"),
                ],
                default="college_iv",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="packagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("devotional", "🕉️ Devotional & Pilgrimage Tour (Temple Circuits)"),
                    ("college_iv", "🎓 College / School Industrial Visit (IV)"),
                    (
                        "international",
                        "✈️ International Tour Package (Passports & Visas)",
                    ),
                    (
                        "hill_station",
                        "⛰️ Hill Station Getaway (Ooty, Kodaikanal, Munnar, Coorg)",
                    ),
                    (
                        "holiday",
                        "🏖️ Leisure & Beach Holiday (Goa, Pondicherry, Kerala)",
                    ),
                    ("local_tour", "🚗 Local 1-Day Sightseeing / Hourly Rental"),
                    ("family_vacation", "💐 Family & Custom Vacation Package"),
                    ("corporate_offsite", "🏢 Corporate Outing & Team Building"),
                    ("fixed_departure", "🚌 Fixed Departure Group Bus Trip"),
                ],
                default="hill_station",
                max_length=50,
            ),
        ),
    ]
