# Generated by Django 6.0.2 on 2026-09-23 10:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("packages", "0008_alter_package_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="cost_activities_per_pax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated entry tickets, jeep safari & permits per person (e.g. ₹450)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="cost_coach_per_pax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated bus transit & fuel cost per person (e.g. ₹1,500)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="cost_hotel_per_pax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated hotel accommodation cost per person (e.g. ₹2,200)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="cost_meals_per_pax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated meal catering cost per person for AP/MAP plan (e.g. ₹1,400)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="cost_misc_per_pax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Guide batta, emergency first aid, parking/toll contingency (e.g. ₹200)",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="PackageAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 4x4 Off-Road Jeep Safari to Mullayanagiri Peak",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "safari_adventure",
                                "🚙 4x4 Jeep Safari / Off-Road Adventure",
                            ),
                            (
                                "sightseeing_entry",
                                "🎟️ Monument / Palace / National Park Entry",
                            ),
                            (
                                "boating_water",
                                "🚤 Speedboat / Houseboat / Scuba Diving",
                            ),
                            (
                                "meal_upgrade",
                                "🍽️ Special Gala Dinner / Barbecue / Seafood",
                            ),
                            ("entertainment_dj", "🎧 DJ Sound System & Campfire Night"),
                            (
                                "insurance_health",
                                "🛡️ Travel Accident & Medical Insurance Cover",
                            ),
                            ("vip_pass", "👑 Fast-Track VIP Temple / Attraction Pass"),
                        ],
                        default="safari_adventure",
                        max_length=40,
                    ),
                ),
                (
                    "pricing_unit",
                    models.CharField(
                        choices=[
                            ("per_person", "Per Person / Head Rate"),
                            ("per_vehicle_group", "Per Vehicle / Jeep (Up to 6-8 Pax)"),
                            ("flat_per_group", "Flat Lump Sum per Tour Group"),
                        ],
                        default="per_person",
                        max_length=30,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Direct procurement/vendor cost",
                        max_digits=10,
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Guest quotation price",
                        max_digits=10,
                    ),
                ),
                (
                    "is_mandatory_inclusion",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mandatory Standard Inclusion (Included in base fare)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What's included in this excursion/activity",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="packages.package",
                    ),
                ),
                (
                    "supplier_partner",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"party_type": "supplier"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_addons",
                        to="core.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience & Safari Add-on",
                "verbose_name_plural": "Experience & Safari Add-ons",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PackageHotelAllotment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hotel_name",
                    models.CharField(
                        help_text="e.g. Sterling Fern Hill Ooty / Royal Orchid Coorg",
                        max_length=255,
                    ),
                ),
                (
                    "room_category",
                    models.CharField(
                        choices=[
                            ("deluxe_ac", "Deluxe AC Room"),
                            ("executive_suite", "Executive Suite / Family Room"),
                            ("standard_non_ac", "Standard Non-AC Room"),
                            (
                                "private_villa",
                                "Private Resort Villa / Cottage (6-8 Pax)",
                            ),
                            ("dormitory", "Group Dormitory / Bunk Beds (10+ Pax)"),
                        ],
                        default="deluxe_ac",
                        max_length=40,
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "rooms_blocked",
                    models.PositiveIntegerField(
                        default=10, help_text="Total rooms contracted from hotelier"
                    ),
                ),
                (
                    "rooms_occupied",
                    models.PositiveIntegerField(
                        default=0, help_text="Rooms allocated to tour guests"
                    ),
                ),
                (
                    "cost_per_room_night",
                    models.DecimalField(
                        decimal_places=2,
                        default=2500,
                        help_text="Contracted rate per room per night",
                        max_digits=10,
                    ),
                ),
                (
                    "cutoff_release_date",
                    models.DateField(
                        blank=True,
                        help_text="Deadline to release unsold rooms without retention charges",
                        null=True,
                    ),
                ),
                (
                    "confirmation_voucher_no",
                    models.CharField(
                        blank=True,
                        help_text="Hotel confirmation voucher number",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("blocked", "🟡 Tentatively Blocked (Awaiting Advance)"),
                            ("confirmed", "🟢 Confirmed with Hotel Voucher"),
                            (
                                "partially_released",
                                "🟠 Partially Released Unsold Rooms",
                            ),
                            ("billed", "✅ Billed & Settled with Hotelier"),
                            ("cancelled", "❌ Cancelled / Released"),
                        ],
                        default="confirmed",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "departure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotel_allotments",
                        to="packages.packageinventory",
                    ),
                ),
                (
                    "hotel_partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hotel supplier ledger in Finance",
                        limit_choices_to={"party_type": "supplier"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_hotel_allotments",
                        to="core.party",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_allotments",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Room Allotment",
                "verbose_name_plural": "Hotel Room Allotments & Block Inventory",
                "ordering": ["check_in_date"],
            },
        ),
        migrations.CreateModel(
            name="PackageSeasonalRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season_name",
                    models.CharField(
                        help_text="e.g. Ooty/Kodaikanal Summer Peak 2025",
                        max_length=200,
                    ),
                ),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            (
                                "peak",
                                "🔥 Peak Season Surcharge (May-June Summer / Dec Holidays)",
                            ),
                            (
                                "festival",
                                "🎉 Festival / Long Weekend Surge (Diwali / Pongal / New Year)",
                            ),
                            (
                                "weekend",
                                "🏖️ Weekend Standard Hike (Fri - Sun Departure)",
                            ),
                            ("off_peak", "❄️ Off-Peak / Monsoon Special Discount"),
                        ],
                        default="peak",
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField(help_text="Season start date")),
                ("end_date", models.DateField(help_text="Season end date")),
                (
                    "surge_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage multiplier on base tour rates (e.g. +20.00% or -10.00%)",
                        max_digits=5,
                    ),
                ),
                (
                    "price_with_food_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Flat rate per person WITH food during this season (overrides base price)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_without_food_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Flat rate per person WITHOUT food during this season",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "vehicle_tariff_surge_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage surge on bus/vehicle hire rates during this season",
                        max_digits=5,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_rates",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seasonal Pricing Tier",
                "verbose_name_plural": "Seasonal Pricing Tiers (Peak / Off-Peak)",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="TourFeedbackLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        help_text="Customer / Faculty / Team lead name", max_length=150
                    ),
                ),
                ("guest_phone", models.CharField(blank=True, max_length=30)),
                ("trip_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "overall_rating",
                    models.PositiveIntegerField(
                        choices=[
                            (5, "⭐⭐⭐⭐⭐ 5 - Excellent"),
                            (4, "⭐⭐⭐⭐ 4 - Good"),
                            (3, "⭐⭐⭐ 3 - Average"),
                            (2, "⭐⭐ 2 - Poor"),
                            (1, "⭐ 1 - Terrible"),
                        ],
                        default=5,
                        verbose_name="Overall Tour Rating",
                    ),
                ),
                (
                    "coach_driver_rating",
                    models.PositiveIntegerField(
                        choices=[
                            (5, "⭐⭐⭐⭐⭐ 5 - Excellent"),
                            (4, "⭐⭐⭐⭐ 4 - Good"),
                            (3, "⭐⭐⭐ 3 - Average"),
                            (2, "⭐⭐ 2 - Poor"),
                            (1, "⭐ 1 - Terrible"),
                        ],
                        default=5,
                        verbose_name="Coach Condition & Driver Punctuality",
                    ),
                ),
                (
                    "hotel_rating",
                    models.PositiveIntegerField(
                        choices=[
                            (5, "⭐⭐⭐⭐⭐ 5 - Excellent"),
                            (4, "⭐⭐⭐⭐ 4 - Good"),
                            (3, "⭐⭐⭐ 3 - Average"),
                            (2, "⭐⭐ 2 - Poor"),
                            (1, "⭐ 1 - Terrible"),
                        ],
                        default=5,
                        verbose_name="Hotel Room & Resort Cleanliness",
                    ),
                ),
                (
                    "food_rating",
                    models.PositiveIntegerField(
                        choices=[
                            (5, "⭐⭐⭐⭐⭐ 5 - Excellent"),
                            (4, "⭐⭐⭐⭐ 4 - Good"),
                            (3, "⭐⭐⭐ 3 - Average"),
                            (2, "⭐⭐ 2 - Poor"),
                            (1, "⭐ 1 - Terrible"),
                        ],
                        default=5,
                        verbose_name="Meal Quality & Dining Experience",
                    ),
                ),
                (
                    "schedule_rating",
                    models.PositiveIntegerField(
                        choices=[
                            (5, "⭐⭐⭐⭐⭐ 5 - Excellent"),
                            (4, "⭐⭐⭐⭐ 4 - Good"),
                            (3, "⭐⭐⭐ 3 - Average"),
                            (2, "⭐⭐ 2 - Poor"),
                            (1, "⭐ 1 - Terrible"),
                        ],
                        default=5,
                        verbose_name="Itinerary Execution & Sightseeing",
                    ),
                ),
                (
                    "nps_score",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Likelihood to recommend to family/friends (0 to 10)",
                    ),
                ),
                (
                    "customer_review_text",
                    models.TextField(
                        blank=True, help_text="Detailed feedback or comments from guest"
                    ),
                ),
                (
                    "flag_status",
                    models.CharField(
                        choices=[
                            ("positive", "🟢 Positive / Brand Ambassador"),
                            ("neutral", "🟡 Neutral / Standard Experience"),
                            (
                                "escalated_complaint",
                                "🔴 Escalated Quality Complaint (Needs Resolution)",
                            ),
                            ("resolved", "✅ Complaint Resolved by Management"),
                        ],
                        default="positive",
                        max_length=30,
                    ),
                ),
                (
                    "manager_resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Root-cause investigation and corrective action taken",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True, verbose_name="Verified Post-Trip Customer"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "departure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_logs",
                        to="packages.packageinventory",
                    ),
                ),
                (
                    "iv_expedition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_logs",
                        to="packages.collegeivexpedition",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_logs",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post-Trip Customer Feedback",
                "verbose_name_plural": "Post-Trip Customer Feedback & Quality Logs",
                "ordering": ["-trip_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageB2BMargin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        choices=[
                            (
                                "silver_agent",
                                "🥈 Silver Travel Agent (Standard Commission)",
                            ),
                            ("gold_agent", "🥇 Gold Preferred Partner (High Volume)"),
                            ("platinum_dmc", "💎 Platinum DMC / Wholesaler"),
                            ("corporate_affiliate", "🏢 Corporate Affinity Partner"),
                        ],
                        default="silver_agent",
                        max_length=40,
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Commission percentage on tour package selling price",
                        max_digits=5,
                    ),
                ),
                (
                    "fixed_discount_per_pax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Alternative flat discount per head for B2B partner",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2b_margins",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "verbose_name": "B2B Sub-Agent Commission Rule",
                "verbose_name_plural": "B2B Sub-Agent Commission Rules",
                "unique_together": {("package", "tier_name")},
            },
        ),
    ]
