# Generated by Django 6.0.2 on 2026-09-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntryProxy",
            fields=[],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("audit.auditlogentry",),
        ),
        migrations.CreateModel(
            name="CommissionRuleProxy",
            fields=[],
            options={
                "verbose_name": "Commission Rule",
                "verbose_name_plural": "Commission Rules",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("suppliers.commissionrule",),
        ),
        migrations.CreateModel(
            name="SupplierContractProxy",
            fields=[],
            options={
                "verbose_name": "Supplier Contract",
                "verbose_name_plural": "Supplier Contracts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("suppliers.suppliercontract",),
        ),
    ]
