# Generated by Django 5.1.15 on 2026-09-27 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp Broadcast"),
                            ("sms", "SMS Broadcast"),
                            ("email", "Email Newsletter"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all_tourists", "All Past Holiday Tour Customers"),
                            (
                                "corporate_clients",
                                "Corporate & Institution Coordinators",
                            ),
                            ("cold_inquiries", "Unconverted CRM Leads (Last 90 Days)"),
                            ("frequent_cabs", "Frequent Outstation Cab Renters"),
                        ],
                        default="all_tourists",
                        max_length=30,
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("message_body", models.TextField()),
                ("target_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Campaign"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active / In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="marketing.coupon",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
