# Generated by Django 6.0.2 on 2026-09-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Route A: Tambaram to OMR Campus", max_length=255
                    ),
                ),
                ("distance_km", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rate_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overrides contract default rate if provided",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup (To Campus)"),
                            ("drop", "Drop (From Campus)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timing", models.TimeField(help_text="e.g. 07:00 AM")),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="fleet_contracts.route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractTripLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("passenger_count", models.PositiveIntegerField(default=0)),
                ("opening_km", models.PositiveIntegerField(blank=True, null=True)),
                ("closing_km", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "driver_bata",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Bata specifically for this trip",
                        max_digits=10,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.vehicle",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="fleet_contracts.shift",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("school", "School / College"),
                            ("corporate", "Corporate / BPO (Staff Commute)"),
                            ("government", "Government Duty"),
                            ("manufacturing", "Manufacturing / Factory"),
                            ("other", "Other Bulk Contract"),
                        ],
                        default="corporate",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "billing_model",
                    models.CharField(
                        choices=[
                            ("per_trip", "Per Trip"),
                            ("per_km", "Per KM"),
                            ("fixed_monthly", "Fixed Monthly"),
                        ],
                        default="per_trip",
                        max_length=20,
                    ),
                ),
                (
                    "default_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default rate for billing (e.g. per trip rate or fixed monthly rent)",
                        max_digits=10,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fleet_contracts",
                        to="core.client",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="route",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="fleet_contracts.transportcontract",
            ),
        ),
    ]
