# Generated by Django 6.0.2 on 2026-09-17 07:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("fleet_contracts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transportcontract",
            name="contract_type",
        ),
        migrations.AddField(
            model_name="contracttriplog",
            name="actual_arrival_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contracttriplog",
            name="actual_departure_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contracttriplog",
            name="delay_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Minutes delayed beyond permissible grace period"
            ),
        ),
        migrations.AddField(
            model_name="contracttriplog",
            name="delay_reason",
            field=models.CharField(
                blank=True,
                help_text="e.g. Heavy highway gridlock, Tyre flat, Route detour",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="contracttriplog",
            name="is_replacement_vehicle",
            field=models.BooleanField(
                default=False,
                help_text="True if dispatched as a standby backup vehicle due to breakdown",
            ),
        ),
        migrations.AddField(
            model_name="contracttriplog",
            name="replaced_vehicle",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary vehicle that broke down",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_trips",
                to="core.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="contracttriplog",
            name="scheduled_departure_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contracttriplog",
            name="toll_parking_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Toll / Parking / Municipal entry incurred on this trip",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="destination",
            field=models.CharField(
                blank=True,
                help_text="Drop Location / Campus Gate (e.g. Sholinganallur Tech Park)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="estimated_travel_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Estimated travel duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="route",
            name="origin",
            field=models.CharField(
                blank=True,
                help_text="Depot / Starting Point (e.g. Tambaram Bus Stand)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="days_of_week",
            field=models.CharField(
                default="Mon-Fri",
                help_text="Operating days (e.g. Mon-Fri, Mon-Sat, All 7 Days)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="escort_guard_required",
            field=models.BooleanField(
                default=False,
                help_text="Security escort guard legally mandatory (e.g. female drops 8 PM - 6 AM)",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="grace_period_minutes",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Permissible delay margin before SLA penalty triggers",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="shift_name",
            field=models.CharField(
                blank=True,
                help_text="e.g. Shift 1 Morning, General 9 AM, Night Drop BPO",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="base_diesel_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Base diesel price per liter at time of signing (e.g. ₹92.50)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("calendar_month", "Calendar Month (1st to Last Day)"),
                    ("custom_cycle", "Custom 30-Day Cycle"),
                ],
                default="calendar_month",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="committed_vehicle_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Committed primary vehicles dedicated exclusively to this contract",
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="contact_person",
            field=models.CharField(
                blank=True,
                help_text="Transport Desk / Admin Manager Name",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="contact_phone",
            field=models.CharField(
                blank=True, help_text="Direct phone / Emergency desk", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="contract_category",
            field=models.CharField(
                choices=[
                    ("corporate", "🏢 Corporate / IT / BPO (Staff Commute)"),
                    ("school", "🎒 School / College Student Transport"),
                    ("factory", "🏭 Manufacturing / Factory Shift Shuttle"),
                    ("hospital", "🏥 Hospital / Healthcare Staff Shuttle"),
                    ("government", "🏛️ Government / PSU Official Duty"),
                    ("other", "📋 Other Long-Duration Bulk Contract"),
                ],
                default="corporate",
                help_text="Operational vertical (Corporate ETS, School Bus, Factory Shift, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="fuel_escalation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Check if contract includes fuel price revision clause",
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="fuel_revision_factor",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Adjustment factor per ₹1 change in diesel (e.g. ₹0.25 per km)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="payment_credit_days",
            field=models.PositiveIntegerField(
                default=30, help_text="Credit period in days (e.g. 30, 45, 60 days)"
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="sla_penalty_cap_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Maximum monthly SLA penalty deduction ceiling as % of monthly billing",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="standby_vehicle_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Guaranteed backup/spare standby vehicles for breakdown cover",
            ),
        ),
        migrations.AlterField(
            model_name="contracttriplog",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "📅 Scheduled"),
                    ("en_route", "🚍 En Route"),
                    ("completed", "✅ Completed"),
                    ("delayed", "⚠️ Completed with Delay"),
                    ("breakdown", "🔴 Vehicle Breakdown"),
                    ("cancelled", "❌ Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance_km",
            field=models.PositiveIntegerField(
                blank=True, help_text="One-way route distance in KMs", null=True
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="rate_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overrides contract default rate specifically for this route",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="direction",
            field=models.CharField(
                choices=[
                    ("pickup", "⬆️ Pickup (To Campus / Plant)"),
                    ("drop", "⬇️ Drop (From Campus / Plant)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="timing",
            field=models.TimeField(
                help_text="Scheduled departure/login time (e.g. 07:00 AM)"
            ),
        ),
        migrations.AlterField(
            model_name="transportcontract",
            name="billing_model",
            field=models.CharField(
                choices=[
                    ("per_trip", "Per Trip Rate"),
                    ("per_km", "Per KM Rate"),
                    ("fixed_monthly", "Fixed Monthly Lump Sum"),
                ],
                default="per_trip",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transportcontract",
            name="customer",
            field=models.ForeignKey(
                help_text="Corporate/School client organization",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fleet_contracts",
                to="core.client",
            ),
        ),
        migrations.AlterField(
            model_name="transportcontract",
            name="default_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Base rate for billing (per trip rate, per km rate, or monthly lumpsum)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="transportcontract",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="GST percentage (e.g. 5% or 12%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="transportcontract",
            name="name",
            field=models.CharField(
                help_text="e.g. Infosys Campus Shuttle 2026-27", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="transportcontract",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Special terms, escort rules, penalty clauses"
            ),
        ),
        migrations.AlterField(
            model_name="transportcontract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft / In Discussion"),
                    ("active", "Active & Operational"),
                    ("completed", "Completed / Expired"),
                    ("cancelled", "Terminated / Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ContractFleetRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_allocations",
                        to="fleet_contracts.transportcontract",
                    ),
                ),
                (
                    "primary_driver",
                    models.ForeignKey(
                        help_text="Regular driver assigned to this route",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_primary",
                        to="core.driver",
                    ),
                ),
                (
                    "primary_vehicle",
                    models.ForeignKey(
                        help_text="Dedicated primary bus/cab assigned to this duty",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_primary",
                        to="core.vehicle",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roster_allocations",
                        to="fleet_contracts.route",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roster_allocations",
                        to="fleet_contracts.shift",
                    ),
                ),
                (
                    "standby_vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Designated backup vehicle in case primary breaks down",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roster_standby",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dedicated Fleet Roster Allocation",
                "verbose_name_plural": "Dedicated Fleet & Crew Roster",
            },
        ),
        migrations.CreateModel(
            name="ContractMonthlyInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="e.g. INV-ETS-2026-09-001", max_length=50, unique=True
                    ),
                ),
                (
                    "billing_month",
                    models.DateField(
                        help_text="First date of billing month (e.g. 2026-09-01)"
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("total_trips_completed", models.PositiveIntegerField(default=0)),
                (
                    "total_kms_run",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "base_contract_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Base billing (Fixed monthly fee or Trips * Per Trip Rate)",
                        max_digits=12,
                    ),
                ),
                (
                    "extra_km_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fuel_escalation_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Net fuel adjustment per escalation formula",
                        max_digits=10,
                    ),
                ),
                (
                    "toll_parking_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sla_penalty_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total SLA penalties deducted",
                        max_digits=10,
                    ),
                ),
                (
                    "net_taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "📝 Draft / Calculating"),
                            ("generated", "📤 Generated / Sent to Client"),
                            ("paid", "✅ Paid in Full"),
                            ("partially_paid", "🟡 Partially Paid"),
                            ("disputed", "⚠️ Disputed by Client"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_invoices",
                        to="fleet_contracts.transportcontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Monthly Invoice",
                "verbose_name_plural": "Contract Monthly Invoices",
            },
        ),
        migrations.CreateModel(
            name="ContractSLAPenalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "penalty_type",
                    models.CharField(
                        choices=[
                            ("late_arrival", "⏱️ Late Arrival (>15 Mins Breach)"),
                            (
                                "breakdown_delay",
                                "🔧 Breakdown Delay / Standby Deployment Failure",
                            ),
                            ("ac_failure", "❄️ AC Failure in Bus / Cab"),
                            (
                                "unauthorized_driver",
                                "👔 Unverified / Ununiformed Driver",
                            ),
                            (
                                "escort_missing",
                                "🛡️ Missing Security Escort on Female Night Drop",
                            ),
                            ("speed_violation", "⚠️ Speed Limit Violation (>50 km/h)"),
                            ("missed_trip", "❌ Completely Missed / Unserved Trip"),
                            ("other", "📋 Other Contractual SLA Infraction"),
                        ],
                        default="late_arrival",
                        max_length=50,
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount deducted in ₹",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Incident details reported by client / supervisor",
                    ),
                ),
                (
                    "waived",
                    models.BooleanField(
                        default=False,
                        help_text="Check if waived by mutual agreement with client",
                    ),
                ),
                ("waiver_reason", models.CharField(blank=True, max_length=255)),
                (
                    "applied_to_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deducted_penalties",
                        to="fleet_contracts.contractmonthlyinvoice",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_penalties",
                        to="fleet_contracts.transportcontract",
                    ),
                ),
                (
                    "trip_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific trip log that incurred this penalty",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sla_penalties",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Penalty & Performance Deduction",
                "verbose_name_plural": "SLA Penalties & Deductions",
            },
        ),
        migrations.CreateModel(
            name="NightSafetyEscortLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "escort_guard_name",
                    models.CharField(
                        help_text="Security Escort Guard Full Name", max_length=150
                    ),
                ),
                (
                    "security_agency",
                    models.CharField(
                        blank=True,
                        help_text="Contracted security agency (e.g. SIS, G4S, Tops Security)",
                        max_length=150,
                    ),
                ),
                (
                    "guard_badge_number",
                    models.CharField(
                        blank=True, help_text="Security Guard ID / Badge", max_length=50
                    ),
                ),
                ("guard_contact_phone", models.CharField(blank=True, max_length=30)),
                ("female_passengers_count", models.PositiveIntegerField(default=1)),
                (
                    "first_pickup_time",
                    models.TimeField(
                        blank=True,
                        help_text="First female employee pickup time",
                        null=True,
                    ),
                ),
                (
                    "last_female_drop_time",
                    models.TimeField(
                        blank=True,
                        help_text="Last female employee drop time",
                        null=True,
                    ),
                ),
                (
                    "last_drop_verification_status",
                    models.CharField(
                        choices=[
                            ("verified_call", "📞 Verified via Phone Call to Employee"),
                            ("verified_sms", "📱 Verified via Safe-Drop SMS / OTP"),
                            ("supervisor_signoff", "✍️ Transport Supervisor Sign-off"),
                            ("pending", "⏳ Verification Pending Confirmation"),
                        ],
                        default="verified_call",
                        max_length=30,
                    ),
                ),
                (
                    "safe_drop_confirmed_by",
                    models.CharField(
                        blank=True,
                        help_text="Employee or supervisor confirmation signature / name",
                        max_length=150,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "trip_log",
                    models.ForeignKey(
                        help_text="Trip log requiring female employee night security",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escort_logs",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Night Escort & Women Safety Log",
                "verbose_name_plural": "Night Safety & Escort Logs",
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_order",
                    models.PositiveIntegerField(
                        default=1, help_text="Stop sequence (1, 2, 3...)"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Stop Name / Pickup Point (e.g. Velachery MRTS Gate)",
                        max_length=255,
                    ),
                ),
                (
                    "scheduled_offset_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minutes from route start time (e.g. 0 for start, 15 for stop 2)",
                    ),
                ),
                (
                    "pickup_landmark",
                    models.CharField(
                        blank=True,
                        help_text="Key landmark / GPS reference",
                        max_length=255,
                    ),
                ),
                (
                    "expected_passenger_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Expected commuters boarding here"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="fleet_contracts.route",
                    ),
                ),
            ],
            options={
                "ordering": ["route", "stop_order"],
                "unique_together": {("route", "stop_order")},
            },
        ),
        migrations.CreateModel(
            name="CommuterManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commuter_type",
                    models.CharField(
                        choices=[
                            ("employee", "🏢 Corporate / IT Employee"),
                            ("student", "🎒 School / College Student"),
                            ("worker", "🏭 Factory / Plant Worker"),
                            ("staff", "👨\u200d🏫 Faculty / Hospital Staff"),
                        ],
                        default="employee",
                        max_length=20,
                    ),
                ),
                (
                    "commuter_id",
                    models.CharField(
                        help_text="Employee ID / Student Roll Number", max_length=50
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                        ],
                        default="female",
                        max_length=10,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Passenger contact number", max_length=30
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Parent / Spouse / Emergency Contact",
                        max_length=100,
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=30),
                ),
                (
                    "department_or_grade",
                    models.CharField(
                        blank=True,
                        help_text="e.g. IT Dept / Grade 8-A / Assembly Line 2",
                        max_length=100,
                    ),
                ),
                (
                    "requires_night_escort",
                    models.BooleanField(
                        default=False,
                        help_text="Flagged for female night drops requiring escort security confirmation",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commuters",
                        to="fleet_contracts.transportcontract",
                    ),
                ),
                (
                    "boarding_stop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Designated pickup/drop stop",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_commuters",
                        to="fleet_contracts.routestop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commuter & Student Passenger",
                "verbose_name_plural": "Commuter & Student Manifest",
            },
        ),
    ]
