# Generated by Django 6.0.2 on 2026-09-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet_contracts", "0002_remove_transportcontract_contract_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportcontract",
            name="category_specifications",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Vertical-specific operational rules, compliance checklists, and SLA parameters",
            ),
        ),
    ]
