# Generated by Django 5.1.15 on 2026-10-10 06:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet_contracts", "0003_transportcontract_category_specifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="commutermanifest",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Home/Pickup GPS Latitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="commutermanifest",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Home/Pickup GPS Longitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="commutermanifest",
            name="pickup_address",
            field=models.CharField(
                blank=True, help_text="Home doorstep or pickup address", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="contracttriplog",
            name="cluster_code",
            field=models.CharField(
                blank=True,
                help_text="AI Route Clustering Code (e.g. CLUS-MORN-V01)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contracttriplog",
            name="cluster_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optimized waypoints, metrics, and TSP sequence",
            ),
        ),
        migrations.AddField(
            model_name="routestop",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS Latitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="routestop",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS Longitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="campus_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=Decimal("11.016800"),
                help_text="Campus / Destination Facility GPS Latitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transportcontract",
            name="campus_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=Decimal("76.955800"),
                help_text="Campus / Destination Facility GPS Longitude",
                max_digits=9,
                null=True,
            ),
        ),
    ]
