# Generated by Django 5.1.15 on 2026-10-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_party_party_rates_non_negative"),
        (
            "fleet_contracts",
            "0004_commutermanifest_latitude_commutermanifest_longitude_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contracttriplog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closing_km__isnull", True),
                    ("opening_km__isnull", True),
                    ("closing_km__gte", models.F("opening_km")),
                    _connector="OR",
                ),
                name="contract_trip_closing_km_gte_opening_km",
            ),
        ),
        migrations.AddConstraint(
            model_name="contracttriplog",
            constraint=models.CheckConstraint(
                condition=models.Q(("driver_bata__gte", 0)),
                name="contract_trip_driver_bata_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="contracttriplog",
            constraint=models.CheckConstraint(
                condition=models.Q(("toll_parking_charges__gte", 0)),
                name="contract_trip_toll_parking_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="transportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="contract_end_date_gte_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="transportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_rate__gte", 0)),
                name="contract_default_rate_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="transportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("committed_vehicle_count__gte", 0)),
                name="contract_committed_vehicles_non_negative",
            ),
        ),
    ]
