# Generated by Django 5.1.15 on 2026-10-10 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "package_itinerary",
                                "🗺️ Tour Packages & Itinerary Guides",
                            ),
                            (
                                "policy_rules",
                                "📜 Booking, Night Bata, Toll & Cancellation Policies",
                            ),
                            (
                                "tourism_guide",
                                "🏛️ Destination Sightseeing, E-Pass & Temple Rules",
                            ),
                            (
                                "fleet_safety",
                                "🛡️ Chauffeur Safety, Emergency & Breakdown Protocols",
                            ),
                            ("faq_general", "💡 General Customer & Agent FAQ"),
                        ],
                        default="package_itinerary",
                        max_length=40,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Operations Manual 2026, Tourism Circular",
                        max_length=150,
                    ),
                ),
                (
                    "raw_content",
                    models.TextField(
                        help_text="Full plaintext content or PDF text extract"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Active for RAG Retrieval"
                    ),
                ),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RAG Knowledge Document",
                "verbose_name_plural": "RAG Knowledge Documents",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField(default=0)),
                ("chunk_title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords for BM25 matching",
                    ),
                ),
                (
                    "vector_tfidf",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Normalized term frequencies for cosine similarity",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.knowledgedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG Knowledge Chunk",
                "verbose_name_plural": "RAG Knowledge Chunks",
                "ordering": ["document", "chunk_index"],
            },
        ),
    ]
