# Generated by Django 6.0.2 on 2026-09-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("packages", "0002_alter_packageinventory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardingPointProxy",
            fields=[],
            options={
                "verbose_name": "Tour Boarding Point",
                "verbose_name_plural": "Boarding Points & Timetable",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("packages.boardingpoint",),
        ),
        migrations.CreateModel(
            name="CollegeIVProxy",
            fields=[],
            options={
                "verbose_name": "College IV Expedition",
                "verbose_name_plural": "College IV Expeditions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("packages.collegeivexpedition",),
        ),
        migrations.CreateModel(
            name="PassengerManifestProxy",
            fields=[],
            options={
                "verbose_name": "Passenger & Rooming List",
                "verbose_name_plural": "Passenger Manifest & Rooming",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("packages.tourpassengermanifest",),
        ),
        migrations.CreateModel(
            name="TourDepartureBatchProxy",
            fields=[],
            options={
                "verbose_name": "Tour Bus Departure Batch",
                "verbose_name_plural": "Tour Bus Departure Batches",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("packages.packageinventory",),
        ),
    ]
