# Generated by Django 6.0.2 on 2026-09-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("package_tours", "0001_initial"),
        ("packages", "0009_package_cost_activities_per_pax_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelAllotmentProxy",
            fields=[],
            options={
                "verbose_name": "Hotel Room Block Allotment",
                "verbose_name_plural": "Hotel Room Block Allotments",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("packages.packagehotelallotment",),
        ),
        migrations.CreateModel(
            name="TourFeedbackProxy",
            fields=[],
            options={
                "verbose_name": "Tour Customer Feedback",
                "verbose_name_plural": "Customer Reviews & NPS Governance",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("packages.tourfeedbacklog",),
        ),
    ]
