# Generated by Django 6.0.2 on 2026-09-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("package_tours", "0002_hotelallotmentproxy_tourfeedbackproxy"),
        ("packages", "0009_package_cost_activities_per_pax_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BMarginProxy",
            fields=[],
            options={
                "verbose_name": "B2B Reseller Tier & Margin",
                "verbose_name_plural": "B2B Reseller Tiers & Margins",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("packages.packageb2bmargin",),
        ),
        migrations.CreateModel(
            name="PackageAddonProxy",
            fields=[],
            options={
                "verbose_name": "Experience & Safari Add-On",
                "verbose_name_plural": "Experience & Safari Add-Ons",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("packages.packageaddon",),
        ),
        migrations.CreateModel(
            name="SeasonalRateProxy",
            fields=[],
            options={
                "verbose_name": "Seasonal Pricing & Peak Tariff",
                "verbose_name_plural": "Seasonal Pricing & Peak Tariffs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("packages.packageseasonalrate",),
        ),
    ]
