# Generated by Django 5.1.15 on 2026-09-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Customer Mobile OTP",
                "verbose_name_plural": "Customer Mobile OTPs",
                "ordering": ["-created_at"],
            },
        ),
    ]
