import datetime
from decimal import Decimal
from typing import Dict, Any, List, Optional
from django.utils import timezone
from django.db import transaction

from core.models import Vehicle
from maintenance.models import (
    VehicleAsset,
    AssetRotationLog,
    TireInspectionLog,
    ServiceReminder,
    DefectTicket,
)


def evaluate_fleet_pm_triggers(vehicle_id: Optional[int] = None, create_tickets: bool = True) -> Dict[str, Any]:
    """
    Fleet Preventative Maintenance (PM) & Tire Safety Evaluation Engine.
    
    1. Evaluates all active vehicles against ServiceReminder scheduled KM intervals.
    2. Auto-generates high-priority DefectTickets for overdue maintenance tasks.
    3. Analyzes tyre tread depth (mm) and life run (km) across all mounted wheel positions.
    4. Flags critical bald tires (<= 2.5 mm legal threshold) and auto-generates safety tickets.
    5. Calculates overall Fleet Maintenance Health Score (0-100%).
    """
    vehicles_qs = Vehicle.objects.filter(status__in=['available', 'assigned', 'on_trip', 'maintenance'])
    if vehicle_id:
        vehicles_qs = vehicles_qs.filter(pk=vehicle_id)

    total_scanned = vehicles_qs.count()
    overdue_services = []
    due_soon_services = []
    critical_tires = []
    warning_tires = []
    tickets_created = []

    # 1. Evaluate Scheduled Service Reminders
    reminders_qs = ServiceReminder.objects.filter(is_active=True).select_related('vehicle')
    if vehicle_id:
        reminders_qs = reminders_qs.filter(vehicle_id=vehicle_id)

    for r in reminders_qs:
        veh = r.vehicle
        due_km = r.due_km
        curr_km = veh.current_km or 0
        km_left = due_km - curr_km

        if km_left <= 0:
            status = 'overdue'
        elif km_left <= 500:
            status = 'due_soon'
        else:
            status = 'upcoming'

        item = {
            'reminder_id': r.id,
            'vehicle_id': veh.id,
            'vehicle_reg': veh.registration_number,
            'task_name': r.service_task,
            'current_km': curr_km,
            'due_km': due_km,
            'km_difference': km_left,
            'status': status,
            'notes': r.notes,
        }

        if status == 'overdue':
            overdue_services.append(item)
            if create_tickets:
                # Deduplicate against existing open/in-progress tickets
                existing = DefectTicket.objects.filter(
                    vehicle=veh,
                    description__icontains=r.service_task,
                    status__in=['open', 'in_progress']
                ).exists()

                if not existing:
                    ticket = DefectTicket.objects.create(
                        vehicle=veh,
                        reported_by='Fleet PM Engine',
                        description=f"Preventive Maintenance Due: {r.service_task} (Overdue by {abs(km_left)} KM)",
                        status='open',
                        notes=f"Auto-generated by Fleet PM Engine. Current KM ({curr_km}) exceeded threshold ({due_km})."
                    )
                    tickets_created.append({
                        'ticket_id': ticket.id,
                        'vehicle_reg': veh.registration_number,
                        'reason': r.service_task,
                        'type': 'pm_service'
                    })
        elif status == 'due_soon':
            due_soon_services.append(item)

    # 2. Evaluate Tyre Tread Depths & Lifespan
    tires_qs = VehicleAsset.objects.filter(asset_type='tyre', status='in_use').select_related('vehicle')
    if vehicle_id:
        tires_qs = tires_qs.filter(vehicle_id=vehicle_id)

    for tire in tires_qs:
        veh = tire.vehicle
        curr_tread = tire.current_tread_depth_mm or Decimal('12.00')
        run_km = tire.current_run_km
        exp_km = tire.expected_life_km or 40000

        tire_info = {
            'asset_id': tire.id,
            'serial_number': tire.serial_number,
            'vehicle_id': veh.id if veh else None,
            'vehicle_reg': veh.registration_number if veh else "Unassigned",
            'position': tire.position,
            'position_display': tire.get_position_display(),
            'brand': tire.brand or "Standard",
            'size': tire.model_or_size or "",
            'tread_depth_mm': float(curr_tread),
            'tread_wear_percent': tire.tread_wear_percent,
            'current_run_km': run_km,
            'expected_life_km': exp_km,
            'retread_count': tire.retread_count,
            'cost_per_km': float(tire.cost_per_km),
            'health_status': tire.health_status,
        }

        if tire.is_critical_tread or tire.needs_replacement:
            critical_tires.append(tire_info)
            if create_tickets and veh:
                # Check deduplication
                existing = DefectTicket.objects.filter(
                    vehicle=veh,
                    description__icontains=tire.serial_number,
                    status__in=['open', 'in_progress']
                ).exists()

                if not existing:
                    ticket = DefectTicket.objects.create(
                        vehicle=veh,
                        reported_by='Tire Safety Engine',
                        description=f"Tyre Safety Alert: {tire.serial_number} at {tire.get_position_display()} has critical tread {curr_tread}mm (<=2.5mm limit)",
                        status='open',
                        notes=f"Auto-generated alert: Tyre {tire.brand} {tire.model_or_size} (SN: {tire.serial_number}) has reached critical wear ({tire.tread_wear_percent}% worn, {run_km} KM run). Requires immediate replacement or retreading."
                    )
                    tickets_created.append({
                        'ticket_id': ticket.id,
                        'vehicle_reg': veh.registration_number,
                        'reason': f"Tyre {tire.serial_number} critical tread",
                        'type': 'tire_safety'
                    })
        elif tire.is_warning_tread or (exp_km and run_km >= (exp_km * 0.75)):
            warning_tires.append(tire_info)

    # 3. Compute Fleet Maintenance Health Score (0-100)
    unhealthy_count = len(overdue_services) + len(critical_tires)
    warning_count = len(due_soon_services) + len(warning_tires)
    deductions = (unhealthy_count * 15) + (warning_count * 5)
    health_score = max(0, min(100, 100 - deductions))

    return {
        'total_scanned_vehicles': total_scanned,
        'overdue_services_count': len(overdue_services),
        'overdue_services': overdue_services,
        'due_soon_services_count': len(due_soon_services),
        'due_soon_services': due_soon_services,
        'critical_tires_count': len(critical_tires),
        'critical_tires': critical_tires,
        'warning_tires_count': len(warning_tires),
        'warning_tires': warning_tires,
        'tickets_created_count': len(tickets_created),
        'tickets_created': tickets_created,
        'fleet_health_score': health_score,
        'evaluated_at': timezone.now().strftime('%Y-%m-%d %H:%M:%S'),
    }


def rotate_tire_asset(asset_id: int, to_position: str, odometer: Optional[int] = None, mechanic_notes: str = "") -> Dict[str, Any]:
    """
    Rotates a tyre from its current position to `to_position`.
    If an existing tyre occupies `to_position`, performs an atomic swap!
    """
    asset = VehicleAsset.objects.get(pk=asset_id)
    from_pos = asset.position
    vehicle = asset.vehicle
    curr_odo = odometer if odometer is not None else (vehicle.current_km if vehicle else 0) or 0

    with transaction.atomic():
        # Check if another asset currently occupies to_position on this vehicle
        occupant = None
        if vehicle and to_position:
            occupant = VehicleAsset.objects.filter(
                vehicle=vehicle,
                position=to_position,
                status='in_use'
            ).exclude(pk=asset.pk).first()

        # Update primary asset
        asset.position = to_position
        asset.save(update_fields=['position'])

        AssetRotationLog.objects.create(
            asset=asset,
            date=timezone.now().date(),
            odometer=curr_odo,
            from_position=from_pos or 'spare',
            to_position=to_position,
            mechanic_notes=mechanic_notes or f"Rotated from {from_pos} to {to_position}"
        )

        # If swapped, move occupant to from_pos
        if occupant:
            occupant.position = from_pos
            occupant.save(update_fields=['position'])
            AssetRotationLog.objects.create(
                asset=occupant,
                date=timezone.now().date(),
                odometer=curr_odo,
                from_position=to_position,
                to_position=from_pos or 'spare',
                mechanic_notes=f"Swapped with {asset.serial_number} from {from_pos}"
            )

    return {
        'status': 'success',
        'asset_id': asset.id,
        'serial_number': asset.serial_number,
        'from_position': from_pos,
        'to_position': to_position,
        'swapped_with': occupant.serial_number if occupant else None,
        'odometer': curr_odo,
    }


def send_tire_for_retread(asset_id: int, vendor_name: Optional[str] = None, notes: str = "") -> Dict[str, Any]:
    """
    Sends a tyre asset for retreading:
    - Increments retread_count.
    - Transitions status to 'retreading'.
    - Clears active wheel position.
    """
    asset = VehicleAsset.objects.get(pk=asset_id)
    if asset.retread_count >= asset.max_retread_cycles:
        raise ValueError(f"Tyre {asset.serial_number} has reached max retread cycles ({asset.max_retread_cycles}). Must be scrapped.")

    with transaction.atomic():
        old_pos = asset.position
        asset.retread_count += 1
        asset.status = 'retreading'
        asset.position = ''
        if vendor_name:
            asset.vendor_name = vendor_name
        asset.save(update_fields=['retread_count', 'status', 'position', 'vendor_name'])

        # Log inspection / action
        TireInspectionLog.objects.create(
            asset=asset,
            inspection_date=timezone.now().date(),
            odometer=asset.vehicle.current_km if asset.vehicle else (asset.installed_odometer or 0),
            tread_depth_mm=asset.current_tread_depth_mm or Decimal('2.00'),
            psi_pressure=asset.psi_pressure,
            inspector_name='Workshop Manager',
            action_taken='sent_retread',
            condition_notes=notes or f"Sent for retread cycle #{asset.retread_count} from position {old_pos}."
        )

    return {
        'status': 'success',
        'asset_id': asset.id,
        'serial_number': asset.serial_number,
        'new_status': asset.status,
        'retread_count': asset.retread_count,
        'notes': notes,
    }


def return_tire_from_retread(asset_id: int, new_tread_depth_mm: Decimal = Decimal('10.00'), cost: Decimal = Decimal('0.00'), notes: str = "") -> Dict[str, Any]:
    """
    Returns tyre from retreading back into spare inventory with restored tread depth.
    """
    asset = VehicleAsset.objects.get(pk=asset_id)
    with transaction.atomic():
        asset.status = 'spare'
        asset.current_tread_depth_mm = new_tread_depth_mm
        if cost > 0:
            asset.purchase_price = (asset.purchase_price or Decimal('0.00')) + cost
        asset.last_inspected_date = timezone.now().date()
        asset.save(update_fields=['status', 'current_tread_depth_mm', 'purchase_price', 'last_inspected_date'])

        TireInspectionLog.objects.create(
            asset=asset,
            inspection_date=timezone.now().date(),
            odometer=asset.vehicle.current_km if asset.vehicle else 0,
            tread_depth_mm=new_tread_depth_mm,
            psi_pressure=asset.psi_pressure,
            inspector_name='Workshop Receiving',
            action_taken='none',
            condition_notes=notes or f"Received from retread cycle #{asset.retread_count}. Restored tread: {new_tread_depth_mm}mm."
        )

    return {
        'status': 'success',
        'asset_id': asset.id,
        'serial_number': asset.serial_number,
        'status_now': asset.status,
        'restored_tread_depth': float(new_tread_depth_mm),
    }


def log_tire_inspection(
    asset_id: int,
    tread_depth_mm: Decimal,
    psi_pressure: Optional[int] = None,
    odometer: Optional[int] = None,
    inspector_name: str = "",
    has_irregular_wear: bool = False,
    action_taken: str = 'none',
    notes: str = ""
) -> Dict[str, Any]:
    """
    Logs an explicit tire physical inspection, updates live asset tread & pressure measurements,
    and executes follow-up actions if required.
    """
    asset = VehicleAsset.objects.get(pk=asset_id)
    curr_odo = odometer if odometer is not None else (asset.vehicle.current_km if asset.vehicle else 0) or 0

    with transaction.atomic():
        log = TireInspectionLog.objects.create(
            asset=asset,
            inspection_date=timezone.now().date(),
            odometer=curr_odo,
            tread_depth_mm=tread_depth_mm,
            psi_pressure=psi_pressure,
            inspector_name=inspector_name or "Workshop Technician",
            has_irregular_wear=has_irregular_wear,
            action_taken=action_taken,
            condition_notes=notes
        )

        asset.current_tread_depth_mm = tread_depth_mm
        if psi_pressure is not None:
            asset.psi_pressure = psi_pressure
        asset.last_inspected_date = timezone.now().date()
        asset.last_inspected_odometer = curr_odo

        if action_taken == 'sent_retread':
            if asset.retread_count < asset.max_retread_cycles:
                asset.status = 'retreading'
                asset.retread_count += 1
                asset.position = ''
        elif action_taken == 'scrapped':
            asset.status = 'scrapped'
            asset.position = ''

        asset.save(update_fields=[
            'current_tread_depth_mm', 'psi_pressure', 'last_inspected_date',
            'last_inspected_odometer', 'status', 'retread_count', 'position'
        ])

    return {
        'status': 'success',
        'log_id': log.id,
        'asset_id': asset.id,
        'serial_number': asset.serial_number,
        'tread_depth_mm': float(tread_depth_mm),
        'health_status': asset.health_status,
        'is_critical': asset.is_critical_tread,
    }
