# Generated by Django 6.0.2 on 2026-09-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer_portal", "0001_initial"),
        ("documents", "0001_initial"),
        ("payments_gateway", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAccountProxy",
            fields=[],
            options={
                "verbose_name": "Customer Account",
                "verbose_name_plural": "Customer Accounts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("customer_portal.customeraccount",),
        ),
        migrations.CreateModel(
            name="CustomerDocumentProxy",
            fields=[],
            options={
                "verbose_name": "Customer Document",
                "verbose_name_plural": "Customer Documents",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("documents.customerdocument",),
        ),
        migrations.CreateModel(
            name="InstallmentPlanProxy",
            fields=[],
            options={
                "verbose_name": "Installment Plan",
                "verbose_name_plural": "Installment Plans",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments_gateway.installmentplan",),
        ),
        migrations.CreateModel(
            name="PaymentLinkProxy",
            fields=[],
            options={
                "verbose_name": "Payment Link",
                "verbose_name_plural": "Payment Links",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments_gateway.paymentlink",),
        ),
        migrations.CreateModel(
            name="PaymentWebhookEventProxy",
            fields=[],
            options={
                "verbose_name": "Payment Webhook Event",
                "verbose_name_plural": "Payment Webhook Events",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments_gateway.paymentwebhookevent",),
        ),
    ]
