# Generated by Django 6.0.2 on 2026-09-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponProxy",
            fields=[],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("marketing.coupon",),
        ),
        migrations.CreateModel(
            name="EmailCampaignProxy",
            fields=[],
            options={
                "verbose_name": "Email Campaign",
                "verbose_name_plural": "Email Campaigns",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("marketing.emailcampaign",),
        ),
        migrations.CreateModel(
            name="UpsellRecommendationProxy",
            fields=[],
            options={
                "verbose_name": "Upsell Recommendation",
                "verbose_name_plural": "Upsell Recommendations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("marketing.upsellrecommendation",),
        ),
    ]
