# Generated by Django 6.0.2 on 2026-09-24 12:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("crm", "0002_couponproxy_emailcampaignproxy_and_more"),
        ("operations", "0005_trip_tracking_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Ooty Lake Boating, Mudumalai Safari, Tea Factory Tour",
                        max_length=255,
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=100)),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("per_person", "Per Person"),
                            ("per_boat_vehicle", "Per Boat / Vehicle"),
                            ("fixed_group", "Fixed Group Contract"),
                        ],
                        default="per_person",
                        max_length=30,
                    ),
                ),
                (
                    "standard_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sightseeing & Activity Master",
                "verbose_name_plural": "Sightseeing & Activity Masters",
                "ordering": ["destination", "name"],
            },
        ),
        migrations.CreateModel(
            name="GuideChargeMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("english", "English Speaking Guide"),
                            ("hindi", "Hindi Speaking Guide"),
                            ("tamil", "Tamil Regional Guide"),
                            ("french", "French Speaking Foreign Escort"),
                            ("german", "German Speaking Foreign Escort"),
                            ("other", "Other Regional/Foreign Language"),
                        ],
                        default="english",
                        max_length=50,
                    ),
                ),
                (
                    "half_day_rate",
                    models.DecimalField(decimal_places=2, default=800, max_digits=10),
                ),
                (
                    "full_day_rate",
                    models.DecimalField(decimal_places=2, default=1500, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Guide Charges Master",
                "verbose_name_plural": "Guide Charges Masters",
                "ordering": ["destination", "language"],
            },
        ),
        migrations.CreateModel(
            name="HotelMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "destination",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. Ooty, Munnar, Kodaikanal",
                        max_length=100,
                    ),
                ),
                (
                    "star_category",
                    models.CharField(
                        choices=[
                            ("budget", "Budget / Standard (2-Star)"),
                            ("3_star", "3-Star Premium"),
                            ("4_star", "4-Star Superior"),
                            ("5_star", "5-Star Luxury"),
                            ("heritage", "Heritage Palace / Boutique"),
                            ("resort", "Scenic Hill Resort / Villa"),
                        ],
                        default="3_star",
                        max_length=30,
                    ),
                ),
                ("room_type", models.CharField(default="Deluxe Room", max_length=100)),
                (
                    "ep_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Room Only (EP)",
                        max_digits=10,
                    ),
                ),
                (
                    "cp_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Bed & Breakfast (CP)",
                        max_digits=10,
                    ),
                ),
                (
                    "map_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Breakfast + Dinner (MAP)",
                        max_digits=10,
                    ),
                ),
                (
                    "ap_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="All Meals (AP)",
                        max_digits=10,
                    ),
                ),
                (
                    "extra_bed_rate",
                    models.DecimalField(decimal_places=2, default=800, max_digits=10),
                ),
                (
                    "peak_surge_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Seasonal surge % (May, Dec)",
                        max_digits=5,
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hotel Master & Tariff Sheet",
                "verbose_name_plural": "Hotel Master & Tariff Sheets",
                "ordering": ["destination", "name"],
            },
        ),
        migrations.CreateModel(
            name="MonumentEntranceMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Botanical Gardens, Rose Garden, Pykara Falls",
                        max_length=255,
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=100)),
                (
                    "domestic_adult_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "domestic_child_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "foreigner_adult_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "foreigner_child_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "camera_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "operating_hours",
                    models.CharField(default="09:00 AM - 05:30 PM", max_length=100),
                ),
                (
                    "closed_days",
                    models.CharField(
                        blank=True, help_text="e.g. Closed on Tuesdays", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Monument & Entrance Ticket Master",
                "verbose_name_plural": "Monument & Entrance Ticket Masters",
                "ordering": ["destination", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="communicationlog",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.AddField(
            model_name="inquiry",
            name="adult_count",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="child_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "🟢 Low Priority"),
                    ("medium", "🟡 Medium Priority"),
                    ("high", "🟠 High Priority"),
                    ("urgent", "🔴 Urgent / VIP"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "🌐 Website Inquiry Form"),
                    ("whatsapp", "💬 WhatsApp Message"),
                    ("phone", "📞 Direct Phone Call"),
                    ("agent_referral", "🤝 B2B / FTO Agent Referral"),
                    ("walk_in", "🏢 Walk-in Front Desk"),
                    ("email", "✉️ Corporate Email"),
                ],
                default="website",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="target_tat_hours",
            field=models.PositiveIntegerField(
                default=24, help_text="Target Turnaround Time in hours"
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="tat_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="journey_type",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("outstation", "Outstation"),
                    ("airport", "Airport"),
                    ("one_way", "One way"),
                    ("round_trip", "Round trip"),
                ],
                default="outstation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New Lead"),
                    ("in_progress", "Under Review"),
                    ("quoted", "Quotation Sent"),
                    ("negotiating", "Negotiating"),
                    ("won", "Won (Converted)"),
                    ("lost", "Lost"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InquiryFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("phone", "📞 Phone Call"),
                            ("whatsapp", "💬 WhatsApp Chat"),
                            ("email", "✉️ Email Follow-up"),
                            ("meeting", "🤝 In-Person Meeting"),
                        ],
                        default="phone",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        help_text="Discussion points, feedback, and customer reaction"
                    ),
                ),
                (
                    "next_action",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Send revised quote with 4-star hotel",
                        max_length=255,
                    ),
                ),
                ("is_done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="crm.inquiry",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Follow-up",
                "verbose_name_plural": "Inquiry Follow-ups",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quotation_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("guest_name", models.CharField(max_length=255)),
                ("guest_phone", models.CharField(blank=True, max_length=30)),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                (
                    "title",
                    models.CharField(
                        default="Custom Tour Itinerary & Cost Proposal", max_length=255
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("pax_count", models.PositiveIntegerField(default=2)),
                ("vehicle_count", models.PositiveIntegerField(default=1)),
                (
                    "transport_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "accommodation_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "monuments_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "activities_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "guide_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "other_services_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "net_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total Cost to Company (Net Supplier Cost)",
                        max_digits=12,
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        help_text="Agency profit margin %",
                        max_digits=5,
                    ),
                ),
                (
                    "markup_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "gross_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Net + Markup",
                        max_digits=12,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="GST % on Tour Package (standard 5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_quoted_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final Client Payable",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (Work in Progress)"),
                            ("sent", "Sent to Client / FTO"),
                            ("negotiating", "Negotiating / Revision Requested"),
                            ("accepted", "Accepted by Customer"),
                            ("rejected", "Declined / Lost"),
                            ("converted", "Converted to Confirmed Booking"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "inclusions",
                    models.TextField(
                        default="• Accommodation on twin sharing basis as per selected meal plan\n• All transfers, excursions, and inter-city drives by dedicated AC vehicle\n• Professional chauffeur, fuel charges, state permits, toll taxes, and driver night bata\n• All monument entrance tickets and activities specified in the itinerary\n• 24x7 control room emergency assistance"
                    ),
                ),
                (
                    "exclusions",
                    models.TextField(
                        default="• Flight / Train tickets to and from originating city\n• Personal expenses such as laundry, telephone calls, room service, alcoholic beverages\n• Meals not explicitly listed under the designated hotel meal plan\n• Any professional camera permits or optional adventure activities"
                    ),
                ),
                (
                    "terms_conditions",
                    models.TextField(
                        default="• 50% advance deposit required upon quotation acceptance to secure hotel rooms\n• Balance payment due 7 days prior to journey date\n• Standard cancellation rules apply: 100% refund >15 days, 50% refund 7-14 days, non-refundable <7 days"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_quotation",
                        to="operations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations",
                        to="crm.inquiry",
                    ),
                ),
                (
                    "parent_quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="crm.quotation",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="core.client",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.vehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Tour Quotation",
                "verbose_name_plural": "Custom Tour Quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField(default=1)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Day 1: Arrival & Sightseeing in Ooty",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed day-by-day narrative for the client"
                    ),
                ),
                (
                    "hotel_meal_plan",
                    models.CharField(
                        choices=[
                            ("EP", "European Plan (Room Only / EP)"),
                            ("CP", "Continental Plan (Bed & Breakfast / CP)"),
                            ("MAP", "Modified Plan (Breakfast + Dinner / MAP)"),
                            ("AP", "American Plan (All Meals / AP)"),
                        ],
                        default="CP",
                        max_length=10,
                    ),
                ),
                (
                    "overnight_destination",
                    models.CharField(default="Ooty", max_length=100),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.hotelmaster",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="crm.quotation",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
                "unique_together": {("quotation", "day_number")},
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transport", "🚗 Transport & Vehicle Hire"),
                            ("hotel", "🏨 Hotel Accommodation"),
                            ("monument", "🏛️ Monument / Entrance Fee"),
                            ("activity", "🚣 Sightseeing & Activity Fee"),
                            ("guide", "👤 Professional Guide / Escort"),
                            ("other", "✨ Other Ancillary Service"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crm.quotationday",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crm.quotation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
