# Generated by Django 6.0.2 on 2026-09-24 12:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("crm", "0003_activitymaster_guidechargemaster_hotelmaster_and_more"),
        ("operations", "0005_trip_tracking_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="B2CCustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("alternate_phone", models.CharField(blank=True, max_length=30)),
                ("nationality", models.CharField(default="Indian", max_length=100)),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        help_text="Required for NRI/Foreign tourist reporting",
                        max_length=50,
                    ),
                ),
                ("passport_expiry", models.DateField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("anniversary_date", models.DateField(blank=True, null=True)),
                (
                    "is_vip",
                    models.BooleanField(
                        default=False, help_text="Priority VIP customer flag"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=20)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_handle", models.CharField(blank=True, max_length=100)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_handle", models.CharField(blank=True, max_length=100)),
                ("refund_bank_name", models.CharField(blank=True, max_length=150)),
                ("refund_account_no", models.CharField(blank=True, max_length=60)),
                ("refund_ifsc", models.CharField(blank=True, max_length=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2c_profile",
                        to="core.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "B2C Customer Profile",
                "verbose_name_plural": "B2C Customer Profiles",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "diamond",
                                "💎 Diamond Tier 1 (Volume FTO / Global Inbound)",
                            ),
                            ("gold", "🥇 Gold Tier 2 (National DMC Partner)"),
                            ("silver", "🥈 Silver Tier 3 (Regional Retail Agency)"),
                            (
                                "corporate_mnc",
                                "🏢 Corporate MNC (Contracted Business Accounts)",
                            ),
                            ("b2b_local", "🤝 Local B2B Operator / Freelancer"),
                        ],
                        default="silver",
                        max_length=30,
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True,
                        help_text="Brand or Doing-Business-As name",
                        max_length=255,
                    ),
                ),
                ("pan_number", models.CharField(blank=True, max_length=20)),
                (
                    "iata_number",
                    models.CharField(
                        blank=True,
                        help_text="IATA / DOT Accreditation Code",
                        max_length=50,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Authorized credit exposure limit",
                        max_digits=12,
                    ),
                ),
                ("bank_beneficiary_name", models.CharField(blank=True, max_length=255)),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("bank_account_number", models.CharField(blank=True, max_length=60)),
                ("bank_ifsc", models.CharField(blank=True, max_length=25)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                (
                    "swift_bic",
                    models.CharField(
                        blank=True,
                        help_text="SWIFT/BIC for foreign inward remittances",
                        max_length=30,
                    ),
                ),
                (
                    "agreement_file",
                    models.FileField(
                        blank=True,
                        help_text="Signed SLA / corporate contract",
                        null=True,
                        upload_to="agreements/partners/",
                    ),
                ),
                ("agreement_valid_from", models.DateField(blank=True, null=True)),
                ("agreement_valid_until", models.DateField(blank=True, null=True)),
                (
                    "contract_notes",
                    models.TextField(
                        blank=True,
                        help_text="Special commission tiers, payment terms, or discounts",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_profile",
                        to="core.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "FTO & Corporate Partner Profile",
                "verbose_name_plural": "FTO & Corporate Partner Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartyContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(blank=True, max_length=100)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("operations", "🛎️ Operations / Booking Desk"),
                            ("accounts", "💰 Accounts & Billing"),
                            ("management", "👔 Management / Director"),
                            ("emergency", "🚨 24x7 Emergency Escalation"),
                            ("sales", "📈 Sales & Contracting"),
                        ],
                        default="operations",
                        max_length=30,
                    ),
                ),
                ("phone", models.CharField(max_length=30)),
                ("mobile", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="core.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Person",
                "verbose_name_plural": "Contact Persons Directory",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("hotelier", "🏨 Hotelier / Resort / Homestay"),
                            ("sightseeing", "🚣 Sightseeing / Activity Vendor"),
                            (
                                "transporter",
                                "🚗 Subcontractor Transporter / Fleet Vendor",
                            ),
                            ("guide_agency", "👤 Guide Agency / Escort Services"),
                            ("restaurant", "🍽️ Restaurant / Catering Vendor"),
                            ("other", "✨ Other Ancillary Supplier"),
                        ],
                        default="hotelier",
                        max_length=30,
                    ),
                ),
                ("trade_name", models.CharField(blank=True, max_length=255)),
                (
                    "destination_city",
                    models.CharField(
                        help_text="e.g. Ooty, Munnar, Kodaikanal, Madurai",
                        max_length=100,
                    ),
                ),
                ("pan_number", models.CharField(blank=True, max_length=20)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("bank_beneficiary_name", models.CharField(blank=True, max_length=255)),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("bank_account_number", models.CharField(blank=True, max_length=60)),
                ("bank_ifsc", models.CharField(blank=True, max_length=25)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                (
                    "contract_document",
                    models.FileField(
                        blank=True, null=True, upload_to="agreements/suppliers/"
                    ),
                ),
                ("contract_valid_from", models.DateField(blank=True, null=True)),
                ("contract_valid_until", models.DateField(blank=True, null=True)),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False, help_text="Preferred DMC partner flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_profile",
                        to="core.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Profile & Master",
                "verbose_name_plural": "Supplier Profiles & Masters",
                "ordering": ["destination_city", "party__name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierContractedRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_category",
                    models.CharField(
                        choices=[
                            ("hotel_room", "🏨 Hotel Room / Villa"),
                            ("activity", "🚣 Sightseeing / Boat / Safari"),
                            ("transport", "🚗 Fleet / Vehicle Rental"),
                            ("guide", "👤 Tour Escort / Guide Service"),
                            ("meal", "🍽️ Buffet / Meal Package"),
                            ("other", "✨ Other Service"),
                        ],
                        default="hotel_room",
                        max_length=30,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="e.g. Deluxe Garden Room, 2-Hr Motorboat, Tempo 14-Seater",
                        max_length=255,
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        blank=True,
                        help_text="For hotels: Deluxe, Premium, Cottage",
                        max_length=100,
                    ),
                ),
                (
                    "meal_plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EP", "European Plan (Room Only / EP)"),
                            ("CP", "Continental Plan (Bed & Breakfast / CP)"),
                            ("MAP", "Modified Plan (Breakfast + Dinner / MAP)"),
                            ("AP", "American Plan (All Meals / AP)"),
                        ],
                        default="CP",
                        max_length=10,
                    ),
                ),
                (
                    "seasonality",
                    models.CharField(
                        choices=[
                            ("peak", "🔥 Peak Season (Summer & Dec-Jan)"),
                            ("regular", "🌤️ Regular Season (Autumn & Spring)"),
                            ("offpeak", "🌧️ Off-Season / Monsoon Special"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "rack_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Published public tariff",
                        max_digits=10,
                    ),
                ),
                (
                    "contracted_buy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Special negotiated DMC net rate",
                        max_digits=10,
                    ),
                ),
                ("tax_inclusive", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracted_rates",
                        to="crm.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Contracted Rate",
                "verbose_name_plural": "Supplier Contracted Rates",
                "ordering": ["supplier", "seasonality", "service_name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierServiceVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("hotel_reservation", "🏨 Hotel Accommodation Voucher"),
                            ("transport_order", "🚗 Chauffeur Transport Service Order"),
                            (
                                "activity_permit",
                                "🚣 Sightseeing & Activity Entry Voucher",
                            ),
                            ("guide_escort", "👤 Guide / Escort Booking Voucher"),
                        ],
                        default="hotel_reservation",
                        max_length=30,
                    ),
                ),
                ("guest_name", models.CharField(max_length=255)),
                ("guest_phone", models.CharField(blank=True, max_length=30)),
                ("pax_count", models.PositiveIntegerField(default=2)),
                (
                    "service_date_start",
                    models.DateField(help_text="Check-in / Service start date"),
                ),
                (
                    "service_date_end",
                    models.DateField(help_text="Check-out / Service end date"),
                ),
                ("duration_nights", models.PositiveIntegerField(default=1)),
                ("hotel_room_type", models.CharField(blank=True, max_length=100)),
                (
                    "hotel_meal_plan",
                    models.CharField(blank=True, default="CP", max_length=10),
                ),
                ("room_count", models.PositiveIntegerField(default=1)),
                ("vehicle_type_name", models.CharField(blank=True, max_length=100)),
                ("pickup_location", models.CharField(blank=True, max_length=255)),
                ("drop_location", models.CharField(blank=True, max_length=255)),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                ("activity_name", models.CharField(blank=True, max_length=255)),
                (
                    "special_instructions",
                    models.TextField(
                        blank=True,
                        help_text="e.g. Late check-in, honeymoon cake, child cot",
                    ),
                ),
                (
                    "contracted_unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_payable_to_supplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        default="Settlement via Direct Bank Transfer as per monthly DMC credit terms",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (Work in Progress)"),
                            ("issued", "Issued to Supplier (Pending Confirmation)"),
                            ("confirmed", "Confirmed by Supplier Desk"),
                            ("amended", "Amended / Re-issued"),
                            ("cancelled", "Cancelled / Released"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_reference",
                    models.CharField(
                        blank=True,
                        help_text="Supplier confirmation ID / Reservation code",
                        max_length=100,
                    ),
                ),
                (
                    "confirmation_token",
                    models.CharField(
                        blank=True,
                        help_text="Secret token for supplier extranet confirmation",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "supplier_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes returned by supplier upon confirmation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_vouchers",
                        to="operations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_vouchers",
                        to="crm.quotation",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="crm.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Service Voucher & Purchase Order",
                "verbose_name_plural": "Supplier Service Vouchers & Purchase Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
