# Generated by Django 6.0.2 on 2026-09-24 12:58

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_dmctask"),
        ("operations", "0005_trip_tracking_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline", models.CharField(max_length=100)),
                ("flight_number", models.CharField(max_length=50, unique=True)),
                (
                    "origin_airport",
                    models.CharField(
                        help_text="e.g. CJB (Coimbatore) or BLR (Bengaluru)",
                        max_length=100,
                    ),
                ),
                (
                    "destination_airport",
                    models.CharField(
                        help_text="e.g. DEL (Delhi) or DXB (Dubai)", max_length=100
                    ),
                ),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                (
                    "operating_days",
                    models.CharField(
                        default="Daily",
                        help_text="e.g. Daily, Mon/Wed/Fri",
                        max_length=100,
                    ),
                ),
                (
                    "cabin_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("premium_economy", "Premium Economy"),
                            ("business", "Business Class"),
                        ],
                        default="economy",
                        max_length=30,
                    ),
                ),
                (
                    "baggage_allowance",
                    models.CharField(
                        default="15 KG Check-in + 7 KG Cabin", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Flight Master",
                "verbose_name_plural": "Flight Master Data",
                "ordering": ["airline", "flight_number"],
            },
        ),
        migrations.CreateModel(
            name="DmcDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("brochure", "🎨 Tour Brochure / Flyer"),
                            ("itinerary_template", "📑 Itinerary Template"),
                            ("rate_sheet", "📊 Supplier Tariff / Rate Sheet"),
                            ("business_agreement", "🤝 Corporate / FTO Agreement"),
                            ("emailer", "📧 Marketing Emailer / Creative"),
                            ("client_kyc_passport", "🪪 Guest ID / Passport / Visa"),
                            ("voucher_invoice", "🧾 Supplier Bill / Tax Invoice"),
                            ("other", "📂 General Document"),
                        ],
                        default="brochure",
                        max_length=50,
                    ),
                ),
                ("document_file", models.FileField(upload_to="dmc_vault/%Y/%m/")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dmc_documents",
                        to="operations.booking",
                    ),
                ),
                (
                    "related_inquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attached_documents",
                        to="crm.inquiry",
                    ),
                ),
                (
                    "related_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="crm.partnerprofile",
                    ),
                ),
                (
                    "related_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="crm.supplierprofile",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DMC Enterprise Document",
                "verbose_name_plural": "DMC Document Vault",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPaymentRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requisition_number",
                    models.CharField(
                        default=crm.models.generate_requisition_number,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Settlement"),
                            ("partial", "Partial / Stage Payment"),
                            ("advance", "Advance Deposit"),
                            ("credit_settlement", "Monthly Credit Bill Settlement"),
                        ],
                        default="full",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Requisition"),
                            ("pending_approval", "Pending Finance Approval"),
                            ("approved", "Approved for Payment"),
                            ("disbursed", "Disbursed / Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_approval",
                        max_length=30,
                    ),
                ),
                (
                    "cost_to_company",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Net Supplier buy cost",
                        max_digits=12,
                    ),
                ),
                (
                    "cost_to_client",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quoted sell price to client for this service component",
                        max_digits=12,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Supplier's bill / tax invoice number",
                        max_length=100,
                    ),
                ),
                (
                    "invoice_attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="supplier_invoices/%Y/%m/"
                    ),
                ),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("ifsc_code", models.CharField(blank=True, max_length=30)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        help_text="NEFT/RTGS/UPI UTR Number upon disbursement",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_requisitions",
                        to="crm.supplierservicevoucher",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_requisitions",
                        to="crm.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Payment Requisition",
                "verbose_name_plural": "Supplier Payment Requisitions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TravelComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_number",
                    models.CharField(
                        default=crm.models.generate_complaint_number,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "complainant_type",
                    models.CharField(
                        choices=[
                            (
                                "fto_agent",
                                "🏢 Foreign Tour Operator (FTO) / Travel Agent",
                            ),
                            ("corporate", "💼 Corporate Account Coordinator"),
                            ("b2c_traveler", "👤 Direct Retail Traveler"),
                        ],
                        default="b2c_traveler",
                        max_length=30,
                    ),
                ),
                ("complainant_name", models.CharField(max_length=255)),
                ("complainant_phone", models.CharField(blank=True, max_length=50)),
                ("complainant_email", models.EmailField(blank=True, max_length=254)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "hotel_quality",
                                "🏨 Hotel Room / Cleanliness / Service Issue",
                            ),
                            (
                                "vehicle_condition",
                                "🚗 Vehicle AC / Cleanliness / Breakdown",
                            ),
                            (
                                "driver_conduct",
                                "👤 Driver Punctuality / Route / Behavior",
                            ),
                            ("guide_behavior", "🗣️ Tour Guide Knowledge / Language"),
                            ("food_meals", "🍲 Meal Quality / Restaurant Service"),
                            (
                                "itinerary_delay",
                                "⏱️ Sightseeing Skipped / Schedule Delay",
                            ),
                            (
                                "billing_dispute",
                                "💰 Unexpected Charges / Billing Dispute",
                            ),
                            ("other", "⚠️ Other Quality Issue"),
                        ],
                        default="hotel_quality",
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "🔴 Critical (VIP / Immediate Escalation)"),
                            ("high", "🟠 High"),
                            ("medium", "🟡 Medium"),
                            ("low", "🟢 Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lodged", "🔴 Lodged (New Complaint)"),
                            ("under_investigation", "🟡 Under Investigation"),
                            ("supplier_escalated", "🟠 Escalated to Supplier"),
                            ("resolved", "🟢 Resolved with Client"),
                            ("closed", "⚪ Closed & Documented"),
                        ],
                        default="lodged",
                        max_length=30,
                    ),
                ),
                (
                    "supplier_rating_awarded",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Supplier evaluation rating (1 = Poor, 5 = Excellent)",
                        null=True,
                    ),
                ),
                (
                    "issue_description",
                    models.TextField(
                        help_text="Detailed description of the incident / complaint"
                    ),
                ),
                (
                    "investigation_remarks",
                    models.TextField(
                        blank=True,
                        help_text="Root-cause analysis and operational investigation findings",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Action taken (apology, room upgrade, discount, compensation, supplier penalty)",
                    ),
                ),
                ("lodged_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints",
                        to="operations.booking",
                    ),
                ),
                (
                    "related_inquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints",
                        to="crm.inquiry",
                    ),
                ),
                (
                    "supplier_involved",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints",
                        to="crm.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "DMC Quality Complaint",
                "verbose_name_plural": "DMC Quality Complaints",
                "ordering": ["-lodged_at"],
            },
        ),
    ]
