# Generated by Django 6.0.2 on 2026-09-24 13:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("crm", "0006_flightmaster_dmcdocument_supplierpaymentrequisition_and_more"),
        ("operations", "0005_trip_tracking_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DmcInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("proforma", "Proforma Invoice / Advance Bill"),
                            ("tax_invoice", "Official Tax Invoice"),
                        ],
                        default="tax_invoice",
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("billing_name", models.CharField(max_length=255)),
                ("billing_address", models.TextField(blank=True)),
                ("client_gstin", models.CharField(blank=True, max_length=20)),
                ("client_pan", models.CharField(blank=True, max_length=20)),
                (
                    "place_of_supply",
                    models.CharField(default="Tamil Nadu (33)", max_length=100),
                ),
                (
                    "sac_code",
                    models.CharField(
                        default="998555",
                        help_text="Tour Operator Services SAC",
                        max_length=20,
                    ),
                ),
                (
                    "description_of_service",
                    models.CharField(
                        default="Tour Package & Ground Handling Operations",
                        max_length=255,
                    ),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "tax_regime",
                    models.CharField(
                        choices=[
                            ("intra_state", "Intra-State (CGST + SGST)"),
                            ("inter_state", "Inter-State (IGST)"),
                            ("exempt", "Exempt / Zero-Rated (SEZ / Inward Remittance)"),
                        ],
                        default="intra_state",
                        max_length=20,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Total GST Rate (e.g. 5.0, 12.0, 18.0)",
                        max_digits=5,
                    ),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "igst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_invoice_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "bank_account_info",
                    models.TextField(
                        blank=True,
                        default="Bank: State Bank of India\nA/C: 38291048201\nIFSC: SBIN0001234\nUPI: travels@sbi\nBranch: Coimbatore Main",
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True,
                        default="1. 100% settlement required 48 hours prior to journey.\n2. Subject to Coimbatore jurisdiction.\n3. Cheques/Transfers subject to realization.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued to Client"),
                            ("paid", "Fully Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="operations.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dmc_invoices",
                        to="core.party",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="crm.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "DMC Commercial Invoice",
                "verbose_name_plural": "DMC Commercial Invoices",
                "ordering": ["-invoice_date", "-id"],
            },
        ),
    ]
