# Generated by Django 6.0.2 on 2026-09-26 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_dmcinvoice"),
        ("operations", "0009_tripitineraryday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inquiry",
            options={
                "ordering": ["kanban_order", "-created_at"],
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
            },
        ),
        migrations.AddField(
            model_name="inquiry",
            name="converted_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_inquiries",
                to="operations.booking",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="converted_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_inquiries",
                to="operations.trip",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="estimated_deal_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Anticipated deal value in ₹",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="kanban_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Card ordering within column"
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="last_followup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="next_followup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
