# Generated by Django 5.1.15 on 2026-09-27 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_alter_inquiry_options_inquiry_converted_booking_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="competitor_name",
            field=models.CharField(
                blank=True,
                help_text="Competitor agency / platform that won the business",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="lost_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("price_too_high", "💸 Price Too High / Better Offer Elsewhere"),
                    ("competitor_won", "🥊 Competitor Won the Deal"),
                    ("client_postponed", "📅 Client Postponed / Will Book Later"),
                    ("budget_cut", "✂️ Budget Cut / Trip Cancelled"),
                    ("no_vehicle", "🚌 Required Vehicle Type Not Available"),
                    ("unresponsive", "📵 Client Became Unresponsive"),
                    ("changed_mind", "🔄 Client Changed Mind / Destination"),
                    ("other", "📝 Other Reason"),
                ],
                help_text="Primary reason the lead was lost",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="objection_notes",
            field=models.TextField(
                blank=True, help_text="Verbatim objection or feedback from the client"
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="win_loss_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Self-assessment: How well did we handle this lead? (1=Poor, 5=Excellent)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StaffNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_booking", "📋 New Booking Received"),
                            ("payment_received", "💰 Payment Received"),
                            ("payment_failed", "❌ Payment Failed"),
                            ("trip_departing", "🚌 Trip Departing Soon"),
                            ("tat_breach", "⏰ SLA / TAT Breach"),
                            ("lead_won", "🎉 Lead Converted — Won!"),
                            ("lead_lost", "😢 Lead Lost"),
                            ("task_due", "📌 Task Due Today"),
                            ("complaint_lodged", "🚨 New Complaint Lodged"),
                            ("voucher_confirmed", "✅ Supplier Voucher Confirmed"),
                            ("system", "⚙️ System Alert"),
                        ],
                        default="system",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "link_url",
                    models.CharField(
                        blank=True, help_text="Clickable action URL", max_length=512
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to broadcast to ALL staff",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Notification",
                "verbose_name_plural": "Staff Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="crm_staffno_recipie_2b6fee_idx",
                    )
                ],
            },
        ),
    ]
