# Generated by Django 5.1.15 on 2026-09-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_phase6_notifications_objections"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="destination_dropdown",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ooty", "🌲 Ooty / Nilgiris, TN"),
                    ("kodaikanal", "🌸 Kodaikanal, TN"),
                    ("munnar", "🍃 Munnar Tea Hills, KL"),
                    ("kochi", "⛵ Kochi / Alleppey Backwaters, KL"),
                    ("wayanad", "🌿 Wayanad Wildlife, KL"),
                    ("madurai", "🛕 Madurai Temple Circuit, TN"),
                    ("rameshwaram", "🌊 Rameshwaram & Dhanushkodi, TN"),
                    ("kanyakumari", "🌅 Kanyakumari Sunset Point, TN"),
                    ("pondicherry", "🏖️ Pondicherry / Auroville"),
                    ("mysore_coorg", "🏰 Mysore Palace & Coorg, KA"),
                    ("bangalore", "🏙️ Bangalore Tech Hub / Transit"),
                    ("chennai", "🏛️ Chennai Metropolitan & Mahabalipuram"),
                    ("goa", "🌴 Goa Coastal Holiday"),
                    ("tirupati", "🙏 Tirupati Balaji Darshan, AP"),
                    ("yercaud", "⛰️ Yercaud Shevaroy Hills, TN"),
                    ("coimbatore", "🏭 Coimbatore Hub / Isha Yoga"),
                    ("golden_triangle", "👑 Delhi - Agra - Jaipur Triangle"),
                    ("shimla_manali", "❄️ Himachal (Shimla / Manali)"),
                    ("other", "📍 Custom / Other Destination"),
                ],
                default="",
                help_text="Quick select from top holiday circuits & travel destinations",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "🌐 Website Inquiry Form"),
                    ("whatsapp", "💬 WhatsApp Message"),
                    ("phone", "📞 Direct Phone Call"),
                    ("agent_referral", "🤝 B2B / FTO Agent Referral"),
                    ("walk_in", "🏢 Walk-in Front Desk"),
                    ("email", "✉️ Corporate Email"),
                    ("facebook", "📱 Facebook Lead Ads / Page"),
                    ("instagram", "📸 Instagram Ads / DM"),
                ],
                default="website",
                max_length=30,
            ),
        ),
    ]
