# Generated by Django 6.0.2 on 2026-09-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=255, unique=True)),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("current_stock", models.PositiveIntegerField(default=0)),
                ("minimum_stock_level", models.PositiveIntegerField(default=5)),
                (
                    "default_unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Part Inventory",
                "verbose_name_plural": "Part Inventories",
                "ordering": ["part_name"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("insurance", "Insurance Policy"),
                            ("fc", "Fitness Certificate (FC)"),
                            ("permit", "National/State Permit"),
                            ("tax", "Road Tax"),
                            ("pollution", "Pollution / Emission (PUC)"),
                            ("other", "Other Document"),
                        ],
                        max_length=50,
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance_docs/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("insurance_provider", models.CharField(blank=True, max_length=255)),
                (
                    "premium_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("comprehensive", "Comprehensive"),
                            ("third_party", "Third-Party"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "permit_states",
                    models.CharField(
                        blank=True, help_text="e.g. TN, KA, KL", max_length=255
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_documents",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Document",
                "verbose_name_plural": "Compliance Documents",
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="DefectTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reported_by",
                    models.CharField(
                        help_text="Driver name or dispatcher who reported it",
                        max_length=255,
                    ),
                ),
                ("date_reported", models.DateField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Describe the issue, e.g., 'AC not cooling'"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open / Unresolved"),
                            ("in_progress", "In Progress (Mechanic Assigned)"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolved_date", models.DateField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Mechanic notes upon resolution"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defect_tickets",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Defect Ticket",
                "verbose_name_plural": "Defect Tickets",
                "ordering": ["-date_reported"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_accident", models.DateField()),
                ("fir_number", models.CharField(blank=True, max_length=255)),
                ("surveyor_name", models.CharField(blank=True, max_length=255)),
                ("surveyor_phone", models.CharField(blank=True, max_length=50)),
                (
                    "estimated_repair_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "claimed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "approved_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Survey"),
                            ("surveyed", "Surveyed"),
                            ("approved", "Approved / Processing"),
                            ("rejected", "Rejected"),
                            ("settled", "Settled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_claims",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine Service"),
                            ("breakdown", "Breakdown Repair"),
                            ("accidental", "Accidental Repair"),
                            ("bodywork", "Bodywork / Tinkering"),
                            ("tyre", "Tyre Replacement/Puncture"),
                            ("other", "Other Maintenance"),
                        ],
                        default="routine",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("in_progress", "In Progress (In Workshop)"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(
                        help_text="KM reading when given for service"
                    ),
                ),
                ("garage_name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Details of complaints and work done"),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "invoice_attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="service_invoices/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_records",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ServiceReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_task",
                    models.CharField(
                        help_text="e.g. Oil Change, General Service", max_length=255
                    ),
                ),
                ("interval_km", models.PositiveIntegerField(help_text="e.g. 10000")),
                ("last_service_km", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_reminders",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_name",
                    models.CharField(
                        blank=True,
                        help_text="Or type name manually if not in inventory",
                        max_length=255,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select from inventory",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="maintenance.partinventory",
                    ),
                ),
                (
                    "service_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_parts",
                        to="maintenance.servicerecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("tyre", "Tyre"), ("battery", "Battery")],
                        max_length=20,
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("front_left", "Front Left"),
                            ("front_right", "Front Right"),
                            ("rear_left_outer", "Rear Left Outer"),
                            ("rear_left_inner", "Rear Left Inner"),
                            ("rear_right_outer", "Rear Right Outer"),
                            ("rear_right_inner", "Rear Right Inner"),
                            ("spare", "Spare / Stepney"),
                            ("engine_bay", "Engine Bay"),
                        ],
                        max_length=50,
                    ),
                ),
                ("installed_date", models.DateField()),
                ("installed_odometer", models.PositiveIntegerField()),
                (
                    "expected_life_km",
                    models.PositiveIntegerField(help_text="e.g., 40000 for tyres"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_use", "In Use"),
                            ("spare", "Spare"),
                            ("retreading", "Sent for Retreading"),
                            ("scrapped", "Scrapped"),
                            ("sold", "Sold"),
                        ],
                        default="in_use",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=255)),
                ("warranty_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "warranty_expiry_km",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Asset",
                "verbose_name_plural": "Vehicle Assets",
            },
        ),
        migrations.CreateModel(
            name="AssetRotationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("odometer", models.PositiveIntegerField()),
                (
                    "from_position",
                    models.CharField(
                        choices=[
                            ("front_left", "Front Left"),
                            ("front_right", "Front Right"),
                            ("rear_left_outer", "Rear Left Outer"),
                            ("rear_left_inner", "Rear Left Inner"),
                            ("rear_right_outer", "Rear Right Outer"),
                            ("rear_right_inner", "Rear Right Inner"),
                            ("spare", "Spare / Stepney"),
                            ("engine_bay", "Engine Bay"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "to_position",
                    models.CharField(
                        choices=[
                            ("front_left", "Front Left"),
                            ("front_right", "Front Right"),
                            ("rear_left_outer", "Rear Left Outer"),
                            ("rear_left_inner", "Rear Left Inner"),
                            ("rear_right_outer", "Rear Right Outer"),
                            ("rear_right_inner", "Rear Right Inner"),
                            ("spare", "Spare / Stepney"),
                            ("engine_bay", "Engine Bay"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mechanic_notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotation_logs",
                        to="maintenance.vehicleasset",
                    ),
                ),
            ],
        ),
    ]
