# Generated by Django 6.0.2 on 2026-09-24 05:18

import django.db.models.deletion
import django.utils.timezone
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("fleet_contracts", "0003_transportcontract_category_specifications"),
        ("maintenance", "0001_initial"),
        ("operations", "0003_alter_trafficfine_financial_responsibility_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreTripInspectionChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_number",
                    models.CharField(
                        default=maintenance.models.generate_inspection_number,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "inspection_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(
                        help_text="Current vehicle odometer (KM)"
                    ),
                ),
                (
                    "odometer_photo",
                    models.FileField(
                        blank=True, null=True, upload_to="inspections/odometer/"
                    ),
                ),
                (
                    "tyres_tread_and_pressure",
                    models.BooleanField(
                        default=True, verbose_name="Tyres Condition & Air Pressure OK"
                    ),
                ),
                (
                    "brakes_functional",
                    models.BooleanField(
                        default=True, verbose_name="Foot Brakes & Handbrake Functional"
                    ),
                ),
                (
                    "engine_oil_level",
                    models.BooleanField(
                        default=True, verbose_name="Engine Oil Level Normal"
                    ),
                ),
                (
                    "coolant_level",
                    models.BooleanField(
                        default=True, verbose_name="Radiator Coolant Level Normal"
                    ),
                ),
                (
                    "brake_fluid_level",
                    models.BooleanField(
                        default=True, verbose_name="Brake Fluid Level Normal"
                    ),
                ),
                (
                    "battery_and_wiring",
                    models.BooleanField(
                        default=True, verbose_name="Battery Terminals & Starting OK"
                    ),
                ),
                (
                    "headlights_and_highbeam",
                    models.BooleanField(
                        default=True, verbose_name="Headlights & High Beam OK"
                    ),
                ),
                (
                    "taillights_and_brakelights",
                    models.BooleanField(
                        default=True, verbose_name="Tail Lights & Brake Lights OK"
                    ),
                ),
                (
                    "indicators_and_hazard",
                    models.BooleanField(
                        default=True, verbose_name="Turn Indicators & Hazard Lights OK"
                    ),
                ),
                (
                    "wipers_and_washer_fluid",
                    models.BooleanField(
                        default=True, verbose_name="Wipers & Washer Fluid OK"
                    ),
                ),
                (
                    "horn_and_mirrors",
                    models.BooleanField(
                        default=True, verbose_name="Horn & Rear-view Mirrors OK"
                    ),
                ),
                (
                    "first_aid_kit_present",
                    models.BooleanField(
                        default=True, verbose_name="First Aid Kit Present & Stocked"
                    ),
                ),
                (
                    "fire_extinguisher_present",
                    models.BooleanField(
                        default=True, verbose_name="Fire Extinguisher Valid & Present"
                    ),
                ),
                (
                    "spare_wheel_and_jack",
                    models.BooleanField(
                        default=True,
                        verbose_name="Spare Wheel, Jack & Tool Kit Present",
                    ),
                ),
                (
                    "ac_or_fans_working",
                    models.BooleanField(
                        default=True, verbose_name="AC / Blower Fans Working"
                    ),
                ),
                (
                    "cabin_cleanliness",
                    models.BooleanField(
                        default=True, verbose_name="Cabin & Passenger Seats Clean"
                    ),
                ),
                (
                    "has_visible_body_scratches",
                    models.BooleanField(
                        default=False, verbose_name="Visible Exterior Scratches/Dents"
                    ),
                ),
                (
                    "exterior_condition_notes",
                    models.TextField(
                        blank=True, help_text="Notes on exterior condition / dents"
                    ),
                ),
                (
                    "defect_notes",
                    models.TextField(
                        blank=True, help_text="Notes on failed safety or fluid items"
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed - Fit for Operation"),
                            (
                                "conditional_pass",
                                "Conditional Pass - Minor Issue Noted",
                            ),
                            ("failed", "Failed - Safety Risk / Vehicle Grounded"),
                        ],
                        default="passed",
                        max_length=30,
                    ),
                ),
                (
                    "driver_signature_name",
                    models.CharField(
                        help_text="Name of driver completing inspection", max_length=150
                    ),
                ),
                ("supervisor_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "defect_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originated_from_inspection",
                        to="maintenance.defectticket",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_trip_inspections",
                        to="core.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_trip_inspections",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Trip Inspection Checklist",
                "verbose_name_plural": "Pre-Trip Inspection Checklists",
                "ordering": ["-inspection_date"],
            },
        ),
    ]
