# Generated by Django 6.0.2 on 2026-09-26 12:41

import django.db.models.deletion
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("maintenance", "0002_pretripinspectionchecklist"),
        ("operations", "0007_alter_emergencyincidentalert_incident_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDamageInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_number",
                    models.CharField(
                        default=maintenance.models.generate_damage_inspection_number,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Guest or self-drive renter name",
                        max_length=150,
                    ),
                ),
                ("customer_phone", models.CharField(blank=True, max_length=30)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("checkout", "Departure / Check-out Handover"),
                            ("checkin", "Return / Check-in Handover"),
                            ("routine", "Depot Routine Inspection / Audit"),
                        ],
                        default="checkout",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_body_style",
                    models.CharField(
                        choices=[
                            ("suv", "SUV (Innova Crysta / Ertiga)"),
                            ("sedan", "Sedan (Dzire / Etios)"),
                            ("tempo", "Tempo Traveller (12/17/26 Seater)"),
                            ("bus", "Coach Bus / Volvo Multi-Axle"),
                        ],
                        default="suv",
                        max_length=20,
                    ),
                ),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(
                        default=0, help_text="Odometer reading in KM"
                    ),
                ),
                (
                    "fuel_level_percent",
                    models.PositiveIntegerField(
                        default=100, help_text="Fuel gauge percentage (0-100%)"
                    ),
                ),
                (
                    "cleanliness_interior",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Interior cleanliness 1-5"
                    ),
                ),
                (
                    "cleanliness_exterior",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Exterior cleanliness 1-5"
                    ),
                ),
                (
                    "security_deposit_held",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Deposit collected before handover (₹)",
                        max_digits=10,
                    ),
                ),
                (
                    "new_damage_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total estimated deductions for new damages (₹)",
                        max_digits=10,
                    ),
                ),
                (
                    "deposit_refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Net refund amount to customer (₹)",
                        max_digits=10,
                    ),
                ),
                (
                    "deposit_status",
                    models.CharField(
                        choices=[
                            ("none", "No Deposit Held"),
                            ("held", "Security Deposit Held"),
                            ("settled_refund", "Settled - Full Refund Issued"),
                            (
                                "settled_deduction",
                                "Settled - Damage Deducted & Balance Refunded",
                            ),
                            ("forfeited", "Forfeited / Unsettled Dispute"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                (
                    "inspector_name",
                    models.CharField(
                        blank=True,
                        help_text="Staff or driver conducting inspection",
                        max_length=150,
                    ),
                ),
                (
                    "customer_signature_data",
                    models.TextField(
                        blank=True, help_text="Base64 canvas signature of customer"
                    ),
                ),
                (
                    "inspector_signature_data",
                    models.TextField(
                        blank=True, help_text="Base64 canvas signature of inspector"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General handover observations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "baseline_checkout",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked checkout inspection to calculate damage diff",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_inspections",
                        to="maintenance.vehicledamageinspection",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="damage_inspections",
                        to="operations.booking",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="damage_inspections",
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_inspections",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Damage Inspection",
                "verbose_name_plural": "Vehicle Damage Inspections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleDamageMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marker_number", models.PositiveIntegerField(default=1)),
                (
                    "damage_type",
                    models.CharField(
                        choices=[
                            ("scratch", "Scratch / Paint Abrasion"),
                            ("dent", "Dent / Body Depression"),
                            ("crack", "Crack / Fracture / Puncture"),
                            ("paint_chip", "Paint Chip / Peeling"),
                            ("broken_glass", "Broken Light / Glass"),
                            ("missing_accessory", "Missing Accessory / Spare Wheel"),
                            ("interior_tear", "Interior Tear / Burn / Stain"),
                            ("other", "Other Exterior Blemish"),
                        ],
                        default="scratch",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor (Surface / Polishable / < 2 in)"),
                            ("moderate", "Moderate (Noticeable Dent / Deep Scratch)"),
                            ("severe", "Severe (Panel Replacement / Structural)"),
                        ],
                        default="minor",
                        max_length=20,
                    ),
                ),
                (
                    "panel_zone",
                    models.CharField(
                        choices=[
                            ("front_bumper", "Front Bumper"),
                            ("rear_bumper", "Rear Bumper"),
                            ("hood", "Engine Hood / Bonnet"),
                            ("roof", "Roof Panel"),
                            ("windshield", "Front Windshield"),
                            ("rear_windshield", "Rear Windshield"),
                            ("door_fl", "Front Left Door"),
                            ("door_fr", "Front Right Door"),
                            ("door_rl", "Rear Left Door"),
                            ("door_rr", "Rear Right Door"),
                            ("quarter_panel_l", "Left Quarter Panel / Fender"),
                            ("quarter_panel_r", "Right Quarter Panel / Fender"),
                            ("mirror_l", "Left Wing Mirror"),
                            ("mirror_r", "Right Wing Mirror"),
                            ("trunk", "Trunk / Boot Lid / Tailgate"),
                            ("wheel_rim", "Wheel Rim / Alloy"),
                            ("interior", "Interior / Seats"),
                        ],
                        default="front_bumper",
                        max_length=30,
                    ),
                ),
                (
                    "x_percent",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "y_percent",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                ("view_angle", models.CharField(default="top", max_length=20)),
                (
                    "is_pre_existing",
                    models.BooleanField(
                        default=False,
                        help_text="True if present prior to customer checkout",
                    ),
                ),
                (
                    "is_new_damage",
                    models.BooleanField(
                        default=False,
                        help_text="True if inflicted during trip / checkout duration",
                    ),
                ),
                (
                    "estimated_repair_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="damage_markers/photos/"
                    ),
                ),
                (
                    "photo_data_url",
                    models.TextField(
                        blank=True, help_text="Base64 captured photo from mobile camera"
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markers",
                        to="maintenance.vehicledamageinspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Damage Marker",
                "verbose_name_plural": "Vehicle Damage Markers",
                "ordering": ["marker_number"],
            },
        ),
    ]
