# Generated by Django 5.1.15 on 2026-10-10 04:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_vehicledamageinspection_vehicledamagemarker"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleasset",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text="e.g. Apollo, MRF, Bridgestone, Michelin, Exide",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="vehicleasset",
            name="current_tread_depth_mm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("12.00"),
                help_text="Latest measured tread depth in mm",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="vehicleasset",
            name="dot_code",
            field=models.CharField(
                blank=True, help_text="DOT manufacture code e.g. 2423", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="vehicleasset",
            name="last_inspected_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleasset",
            name="last_inspected_odometer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleasset",
            name="max_retread_cycles",
            field=models.PositiveIntegerField(
                default=2, help_text="Max retreadings allowed before scrap"
            ),
        ),
        migrations.AddField(
            model_name="vehicleasset",
            name="model_or_size",
            field=models.CharField(
                blank=True,
                help_text="e.g. 215/75 R15, 295/80 R22.5, 12V 100Ah",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="vehicleasset",
            name="original_tread_depth_mm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("12.00"),
                help_text="Brand new tread depth in mm",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="vehicleasset",
            name="psi_pressure",
            field=models.PositiveIntegerField(
                blank=True, help_text="Current cold inflation PSI", null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicleasset",
            name="retread_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of retread cycles completed"
            ),
        ),
        migrations.CreateModel(
            name="TireInspectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "odometer",
                    models.PositiveIntegerField(
                        help_text="Vehicle odometer at inspection"
                    ),
                ),
                (
                    "tread_depth_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Measured tread depth in mm",
                        max_digits=5,
                    ),
                ),
                (
                    "psi_pressure",
                    models.PositiveIntegerField(
                        blank=True, help_text="Cold inflation pressure PSI", null=True
                    ),
                ),
                ("inspector_name", models.CharField(blank=True, max_length=100)),
                (
                    "has_irregular_wear",
                    models.BooleanField(
                        default=False,
                        help_text="Check if feathering, camber, or cupping detected",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("none", "Routine Inspection (No Action)"),
                            ("pressure_adjusted", "Cold Pressure Adjusted"),
                            ("rotated", "Position Rotated"),
                            ("sent_retread", "Sent for Retreading"),
                            ("scrapped", "Condemned & Scrapped"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                ("condition_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="maintenance.vehicleasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tire Inspection Log",
                "verbose_name_plural": "Tire Inspection Logs",
                "ordering": ["-inspection_date", "-id"],
            },
        ),
    ]
