# Generated by Django 5.1.15 on 2026-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_driver_idx_drv_status_type_and_more"),
        ("maintenance", "0004_vehicleasset_brand_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="compliancedocument",
            index=models.Index(
                fields=["vehicle", "document_type", "expiry_date"],
                name="idx_comp_veh_doc_exp",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancedocument",
            index=models.Index(fields=["expiry_date"], name="idx_comp_exp"),
        ),
        migrations.AddIndex(
            model_name="servicerecord",
            index=models.Index(
                fields=["vehicle", "status", "date"], name="idx_srv_veh_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerecord",
            index=models.Index(fields=["vehicle", "date"], name="idx_srv_veh_date"),
        ),
    ]
