# Generated by Django 5.1.15 on 2026-10-04 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("crm", "0010_inquiry_destination_dropdown_alter_inquiry_source"),
        ("operations", "0009_tripitineraryday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(default="smtp.gmail.com", max_length=255),
                ),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                (
                    "smtp_encryption",
                    models.CharField(
                        choices=[
                            ("tls", "TLS (Recommended, Port 587)"),
                            ("ssl", "SSL (Port 465)"),
                            ("none", "None (Unencrypted, Port 25)"),
                        ],
                        default="tls",
                        max_length=10,
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        help_text="e.g. sapnasharma3355@gmail.com",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        help_text="SMTP Application Password",
                        max_length=255,
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        default="notifications@sivagayathiritravels.com", max_length=254
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(default="Customer Support", max_length=255),
                ),
                (
                    "email_active",
                    models.BooleanField(
                        default=True, verbose_name="Email Service Active"
                    ),
                ),
                ("email_daily_limit", models.PositiveIntegerField(default=10000)),
                ("emails_sent_today", models.PositiveIntegerField(default=0)),
                ("last_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("meta_app_id", models.CharField(blank=True, max_length=100)),
                ("meta_app_secret", models.CharField(blank=True, max_length=100)),
                (
                    "meta_verify_token",
                    models.CharField(
                        default="siva_meta_lead_verify_token", max_length=100
                    ),
                ),
                ("meta_page_access_token", models.TextField(blank=True)),
                (
                    "meta_form_id",
                    models.CharField(
                        blank=True, help_text="Target Meta Lead Form ID", max_length=100
                    ),
                ),
                (
                    "meta_active",
                    models.BooleanField(
                        default=True, verbose_name="Meta Lead Ads Active"
                    ),
                ),
                ("meta_leads_imported", models.PositiveIntegerField(default=0)),
                ("last_meta_lead_at", models.DateTimeField(blank=True, null=True)),
                (
                    "google_sheet_url",
                    models.URLField(
                        blank=True,
                        default="https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/export?format=csv",
                        help_text="Google Sheet Published CSV URL or Public Sharing Link",
                    ),
                ),
                (
                    "google_sheet_name",
                    models.CharField(default="Inquiries", max_length=100),
                ),
                ("google_sheet_sync_minutes", models.PositiveIntegerField(default=5)),
                (
                    "google_sheet_active",
                    models.BooleanField(
                        default=True, verbose_name="Google Sheet Sync Active"
                    ),
                ),
                (
                    "google_sheet_last_synced",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("google_sheet_rows_imported", models.PositiveIntegerField(default=0)),
                (
                    "whatsapp_vendor",
                    models.CharField(
                        choices=[
                            ("simulator", "Internal Simulator (Zero Setup Cost)"),
                            (
                                "meta_cloud",
                                "Official WhatsApp Business (Meta Cloud API)",
                            ),
                            (
                                "aisensy",
                                "AiSensy Partner Gateway (https://aisensy.com)",
                            ),
                            ("msg91", "MSG91 Enterprise WhatsApp (https://msg91.com)"),
                            ("wati", "WATI WhatsApp Team Inbox (https://wati.io)"),
                        ],
                        default="simulator",
                        max_length=30,
                    ),
                ),
                ("whatsapp_api_key", models.CharField(blank=True, max_length=255)),
                (
                    "whatsapp_phone_number_id",
                    models.CharField(
                        blank=True,
                        help_text="Meta Phone Number ID or Vendor Sender ID",
                        max_length=100,
                    ),
                ),
                (
                    "whatsapp_business_account_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "whatsapp_active",
                    models.BooleanField(
                        default=True, verbose_name="WhatsApp Gateway Active"
                    ),
                ),
                ("whatsapp_messages_sent", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Integration & Channel Settings",
                "verbose_name_plural": "Integration & Channel Settings",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            (
                                "discount_override",
                                "🏷️ Quotation Discount Override (> 15%)",
                            ),
                            (
                                "credit_limit",
                                "💳 Corporate Credit Extension / Unbilled Booking",
                            ),
                            (
                                "driver_advance",
                                "⛽ Driver Emergency Petty Cash Advance",
                            ),
                            ("rate_override", "📉 Custom Tariff Below Floor Price"),
                        ],
                        default="discount_override",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 18% Special Discount for PSG College IV",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "requested_amount_or_pct",
                    models.CharField(help_text="e.g. 18.5% or ₹15,000", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "🟡 Pending Review"),
                            ("approved", "🟢 Approved by Manager"),
                            ("rejected", "🔴 Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "manager_notes",
                    models.TextField(
                        blank=True,
                        help_text="Justification or conditions for approval/rejection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actioned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actioned_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to="core.party",
                    ),
                ),
                (
                    "related_quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to="crm.quotation",
                    ),
                ),
                (
                    "related_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to="operations.trip",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager Approval Request",
                "verbose_name_plural": "Manager Approvals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadIngestionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "meta_lead_ads",
                                "📱 Meta Lead Ads (Facebook / Instagram)",
                            ),
                            ("google_sheets", "📊 Google Sheets 5-Min Sync"),
                            ("whatsapp_inbound", "💬 WhatsApp Inbound Message"),
                            ("website_form", "🌐 Website Inquiry Form"),
                            ("manual", "🏢 Direct Manual Entry"),
                        ],
                        default="meta_lead_ads",
                        max_length=30,
                    ),
                ),
                (
                    "external_lead_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("lead_name", models.CharField(blank=True, max_length=255)),
                ("lead_phone", models.CharField(blank=True, max_length=30)),
                ("lead_email", models.CharField(blank=True, max_length=150)),
                ("destination", models.CharField(blank=True, max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "🟢 Success (Inquiry Created)"),
                            ("duplicate", "🟡 Duplicate (Merged/Skipped)"),
                            ("failed", "🔴 Failed (Parsing Error)"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_inquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_logs",
                        to="crm.inquiry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Ingestion Log",
                "verbose_name_plural": "Lead Ingestion Logs",
                "ordering": ["-received_at"],
            },
        ),
    ]
