# Generated by Django 5.1.15 on 2026-10-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArattaiMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("outbound", "📤 Outbound (TravelERP -> Arattai User)"),
                            (
                                "inbound",
                                "📥 Inbound (Arattai User -> Rathasārathi Bot)",
                            ),
                        ],
                        default="outbound",
                        max_length=15,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "📋 Booking Confirmation Voucher"),
                            ("driver_assigned", "🚗 Chauffeur & Vehicle Allocation"),
                            ("pickup_pin", "🔐 Guest Pickup Verification PIN"),
                            ("trip_completed", "🏁 Trip Completion & Invoice"),
                            ("emergency_sos", "🚨 Fleet Emergency / SOS Alert"),
                            ("chat_query", "💬 Conversational Chat Query"),
                        ],
                        default="booking_confirmed",
                        max_length=30,
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=30)),
                ("sender_name", models.CharField(blank=True, max_length=150)),
                ("message_text", models.TextField()),
                ("external_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        default="sent",
                        help_text="e.g. sent, delivered, failed, received",
                        max_length=20,
                    ),
                ),
                (
                    "response_text",
                    models.TextField(
                        blank=True, help_text="AI or system reply sent back to user"
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Arattai Message Log",
                "verbose_name_plural": "Arattai Message Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="arattai_active",
            field=models.BooleanField(
                default=True, verbose_name="Arattai Business Gateway Active"
            ),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="arattai_bot_token",
            field=models.CharField(
                blank=True,
                help_text="Zoho Arattai Bot Token or API Key",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="arattai_business_id",
            field=models.CharField(
                blank=True, help_text="Arattai Business Account ID", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="arattai_messages_sent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="integrationsettings",
            name="arattai_webhook_secret",
            field=models.CharField(
                default="arattai_siva_travelerp_verify_2026", max_length=100
            ),
        ),
    ]
