# Generated by Django 6.0.2 on 2026-09-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateFastagAccount",
            fields=[],
            options={
                "verbose_name": "Corporate FASTag Account",
                "verbose_name_plural": "Corporate FASTag Accounts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.corporatefastagaccount",),
        ),
        migrations.CreateModel(
            name="CorporatePetroAccount",
            fields=[],
            options={
                "verbose_name": "Corporate Petro Account",
                "verbose_name_plural": "Corporate Petro Accounts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.corporatepetroaccount",),
        ),
        migrations.CreateModel(
            name="FastagRecharge",
            fields=[],
            options={
                "verbose_name": "FASTag Recharge",
                "verbose_name_plural": "FASTag Recharges",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.fastagrecharge",),
        ),
        migrations.CreateModel(
            name="FastagTollDeduction",
            fields=[],
            options={
                "verbose_name": "FASTag Toll Deduction",
                "verbose_name_plural": "FASTag Toll Deductions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.fastagtolldeduction",),
        ),
        migrations.CreateModel(
            name="FuelRecord",
            fields=[],
            options={
                "verbose_name": "Fuel Record",
                "verbose_name_plural": "Fuel Records",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.fuelrecord",),
        ),
        migrations.CreateModel(
            name="PetroRecharge",
            fields=[],
            options={
                "verbose_name": "Petro Card Recharge",
                "verbose_name_plural": "Petro Card Recharges",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.petrorecharge",),
        ),
    ]
