# Generated by Django 6.0.2 on 2026-09-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet_contracts", "0002_remove_transportcontract_contract_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommuterManifestProxy",
            fields=[],
            options={
                "verbose_name": "Commuter & Student Passenger",
                "verbose_name_plural": "Commuter & Student Manifest",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fleet_contracts.commutermanifest",),
        ),
        migrations.CreateModel(
            name="CommuteRoute",
            fields=[],
            options={
                "verbose_name": "Commute Route",
                "verbose_name_plural": "Routes & Waypoints",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fleet_contracts.route",),
        ),
        migrations.CreateModel(
            name="CommuteShift",
            fields=[],
            options={
                "verbose_name": "Shift & Timetable",
                "verbose_name_plural": "Shifts & Timetables",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fleet_contracts.shift",),
        ),
        migrations.CreateModel(
            name="DailyTripLog",
            fields=[],
            options={
                "verbose_name": "Daily Trip Execution Log",
                "verbose_name_plural": "Daily Trip Logs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fleet_contracts.contracttriplog",),
        ),
        migrations.CreateModel(
            name="NightSafetyEscort",
            fields=[],
            options={
                "verbose_name": "Night Safety & Escort Guard Log",
                "verbose_name_plural": "Night Safety & Escort Logs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fleet_contracts.nightsafetyescortlog",),
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[],
            options={
                "verbose_name": "Route Stop / Pickup Node",
                "verbose_name_plural": "Route Stops & Nodes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fleet_contracts.routestop",),
        ),
    ]
