# Generated by Django 6.0.2 on 2026-09-26 00:27

import django.db.models.deletion
import django.utils.timezone
import fleet_commute.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("fleet_commute", "0001_initial"),
        ("fleet_contracts", "0003_transportcontract_category_specifications"),
        (
            "operations",
            "0006_trip_closing_odometer_photo_trip_driver_handover_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CommuterBoardingPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "boarding_otp",
                    models.CharField(
                        default=fleet_commute.models.generate_4digit_otp,
                        help_text="Dynamic 4-digit verification code",
                        max_length=6,
                    ),
                ),
                (
                    "pass_token",
                    models.CharField(
                        db_index=True,
                        default=fleet_commute.models.generate_pass_token,
                        help_text="Secure unguessable URL token for Mobile Web Pass",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_boarded", models.BooleanField(default=False)),
                ("boarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_isolated_night_drop",
                    models.BooleanField(
                        default=False,
                        help_text="Flagged: Female commuter dropped last on night shift (8 PM - 6 AM)",
                    ),
                ),
                (
                    "escort_assigned",
                    models.BooleanField(
                        default=False,
                        help_text="Physical security guard escort assigned",
                    ),
                ),
                (
                    "ivr_status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ Pending Drop"),
                            ("initiated", "📞 IVR Call Ringing"),
                            ("safe_confirmed", "✅ Safe Drop Confirmed (Key 1)"),
                            (
                                "sos_escalated",
                                "🚨 SOS Escalated to Control Room (Key 2)",
                            ),
                            ("unanswered", "⚠️ Call Unanswered / Auto-Escalated"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("ivr_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("ivr_recording_notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "boarded_by_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.driver",
                    ),
                ),
                (
                    "boarded_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleet_contracts.routestop",
                    ),
                ),
                (
                    "commute_buddy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Designated co-passenger buddy dropping at same or subsequent stop",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buddy_of",
                        to="fleet_commute.commuterboardingpass",
                    ),
                ),
                (
                    "commuter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_passes",
                        to="fleet_contracts.commutermanifest",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passes",
                        to="fleet_contracts.shift",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commute_passes",
                        to="operations.trip",
                    ),
                ),
                (
                    "trip_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commuter_passes",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commuter Boarding Pass & Safety Record",
                "verbose_name_plural": "Commuter Boarding Passes",
                "ordering": ["-date", "commuter__name"],
            },
        ),
        migrations.CreateModel(
            name="ESGCarbonMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "trip_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("passenger_count", models.PositiveIntegerField(default=1)),
                ("fuel_type", models.CharField(default="diesel", max_length=20)),
                (
                    "co2_emitted_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "co2_saved_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "green_efficiency_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("85.00"), max_digits=5
                    ),
                ),
                (
                    "trip_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_metrics",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESG Carbon Footprint Metric",
                "verbose_name_plural": "ESG Carbon Metrics",
                "ordering": ["-date"],
            },
        ),
    ]
