# Generated by Django 6.0.2 on 2026-09-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("guest_name", models.CharField(max_length=255)),
                ("guest_phone", models.CharField(blank=True, max_length=30)),
                ("booking_date", models.DateField(auto_now_add=True)),
                ("pickup_location", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("pickup_date", models.DateField()),
                ("pickup_time", models.TimeField()),
                (
                    "reporting_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time the driver needs to report",
                        null=True,
                    ),
                ),
                ("drop_date", models.DateField(blank=True, null=True)),
                (
                    "travel_pnr",
                    models.CharField(
                        blank=True,
                        help_text="Flight/Train PNR or details",
                        max_length=50,
                    ),
                ),
                (
                    "journey_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("outstation", "Outstation"),
                            ("airport", "Airport"),
                            ("one_way", "One way"),
                            ("round_trip", "Round trip"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pax_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of passengers", null=True
                    ),
                ),
                (
                    "luggage_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of luggage pieces", null=True
                    ),
                ),
                ("special_requirements", models.TextField(blank=True)),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("km", "Per KM"),
                            ("day", "Per Day"),
                            ("package", "Fixed Package"),
                        ],
                        default="package",
                        max_length=20,
                    ),
                ),
                (
                    "quoted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_terms_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("trip", "Trip-by-trip"),
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("bimonthly", "Bi-monthly (Every 2 Months)"),
                            ("quarterly", "Quarterly (Every 3 Months)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "expected_km",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated KMs or Package limit",
                        null=True,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("plan_details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Booking Status",
                    ),
                ),
                (
                    "hotel_confirmation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("changed", "Changed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "hotel_paid_by",
                    models.CharField(
                        choices=[
                            ("company", "Included in Package (We Pay)"),
                            ("customer", "Customer Pays Directly"),
                        ],
                        default="company",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="packages.package",
                    ),
                ),
                (
                    "package_inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="packages.packageinventory",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="core.client",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.vehicletype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BulkContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("cinema", "Cinema / Film Shoot"),
                            ("wedding", "Wedding & Functions"),
                            ("event", "Events & Conferences"),
                            ("government", "Government Duty"),
                            ("other", "Other Bulk Contract"),
                        ],
                        default="cinema",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "billing_model",
                    models.CharField(
                        choices=[
                            ("per_vehicle_day", "Per vehicle day"),
                            ("fixed", "Fixed"),
                            ("custom", "Custom"),
                        ],
                        default="per_vehicle_day",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bulk_contracts",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Contract",
                "verbose_name_plural": "Bulk Contracts",
            },
        ),
        migrations.CreateModel(
            name="BulkContractDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="operations.bulkcontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Contract Day",
                "verbose_name_plural": "Bulk Contract Days",
                "unique_together": {("contract", "date")},
            },
        ),
        migrations.CreateModel(
            name="TrafficFine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_offence", models.DateTimeField()),
                ("challan_number", models.CharField(max_length=100, unique=True)),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("speeding", "Overspeeding"),
                            ("signal", "Signal Jump"),
                            ("parking", "Illegal Parking"),
                            ("documents", "Missing Documents"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fine_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("company", "Paid by Company"),
                            ("driver", "Paid by Driver"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "financial_responsibility",
                    models.CharField(
                        choices=[
                            ("company", "Company Responsibility"),
                            ("driver", "Driver Responsibility"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(blank=True, null=True, upload_to="traffic_fines/"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="traffic_fines",
                        to="core.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_fines",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.CharField(blank=True, max_length=30, unique=True)),
                ("guest_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "travel_pnr",
                    models.CharField(
                        blank=True, help_text="Flight/Train PNR", max_length=50
                    ),
                ),
                (
                    "pax_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of passengers", null=True
                    ),
                ),
                (
                    "luggage_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of luggage pieces", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("assigned", "Assigned"),
                            ("driver_confirmed", "Driver confirmed"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("billed", "Billed"),
                            ("settled", "Settled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="booked",
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("opening_km", models.PositiveIntegerField(blank=True, null=True)),
                ("closing_km", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "billing_model",
                    models.CharField(
                        choices=[
                            ("km", "Kilometre"),
                            ("day", "Day"),
                            ("day_km", "Day + kilometre"),
                            ("fixed", "Fixed"),
                            ("custom", "Custom"),
                        ],
                        default="day_km",
                        max_length=20,
                    ),
                ),
                (
                    "day_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "km_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("days_count", models.PositiveIntegerField(default=1)),
                (
                    "driver_bata",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("partner_handover_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="operations.booking",
                    ),
                ),
                (
                    "bulk_contract_day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="operations.bulkcontractday",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="core.driver",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="packages.package",
                    ),
                ),
                (
                    "package_inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="packages.packageinventory",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="core.party",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripCrewAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("driver", "Driver"),
                            ("cleaner", "Cleaner"),
                            ("driver_cleaner", "Driver + cleaner"),
                            ("additional_driver", "Additional driver"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "cleaner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_crew_assignments",
                        to="core.cleaner",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_crew_assignments",
                        to="core.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_assignments",
                        to="operations.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=255)),
                ("hotel_room_type", models.CharField(blank=True, max_length=100)),
                ("check_in_date", models.DateField(blank=True, null=True)),
                ("check_out_date", models.DateField(blank=True, null=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("changed", "Changed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("company", "Included in Package (We Pay)"),
                            ("customer", "Customer Pays Directly"),
                        ],
                        default="company",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="operations.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripJourney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_location", models.CharField(max_length=255)),
                ("end_location", models.CharField(max_length=255)),
                ("start_km", models.PositiveIntegerField(blank=True, null=True)),
                ("end_km", models.PositiveIntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys",
                        to="operations.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractDayRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "contract_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="operations.bulkcontractday",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.vehicletype",
                    ),
                ),
            ],
            options={
                "unique_together": {("contract_day", "vehicle_type")},
            },
        ),
        migrations.CreateModel(
            name="ContractVehicleRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agreed_day_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_rates",
                        to="operations.bulkcontract",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.vehicletype",
                    ),
                ),
            ],
            options={
                "unique_together": {("contract", "vehicle_type")},
            },
        ),
    ]
