# Generated by Django 6.0.2 on 2026-09-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficfine",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link fine to the specific trip where it occurred",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="traffic_fines",
                to="operations.trip",
            ),
        ),
    ]
