# Generated by Django 6.0.2 on 2026-09-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_trafficfine_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficfine",
            name="financial_responsibility",
            field=models.CharField(
                choices=[
                    ("customer", "👤 Customer (Bill to Customer in Trip Invoice)"),
                    ("driver", "🧑\u200d✈️ Driver (Deduct from Driver Settlement)"),
                    (
                        "supplier",
                        "🏢 Supplier / Vehicle Owner (Outsourced Fleet Issue)",
                    ),
                    ("company", "🏛️ Company Expense (Absorb in Trip P&L)"),
                ],
                default="driver",
                help_text="Select who is financially responsible. 'Customer' adds fine to customer invoice; 'Driver' deducts from driver settlement; 'Supplier' is for outsourced fleet issues; 'Company' absorbs as expense.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trafficfine",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("unpaid", "⏳ Unpaid (Challan Pending)"),
                    ("company", "🏢 Paid by Company"),
                    ("driver", "🧑\u200d✈️ Paid by Driver on Spot"),
                    ("customer", "👤 Paid by Customer on Spot"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trafficfine",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("speeding", "⚡ Overspeeding"),
                    ("seatbelt", "💺 Seatbelt Not Worn (General)"),
                    (
                        "seatbelt_passenger",
                        "💺 Seatbelt Not Worn (Passenger / Customer)",
                    ),
                    ("seatbelt_driver", "💺 Seatbelt Not Worn (Driver)"),
                    ("signal", "🚦 Signal Jump / Red Light"),
                    ("parking", "🅿️ Illegal / No Parking"),
                    ("smoking", "🚭 Smoking in Vehicle (Customer Violation)"),
                    ("documents", "📄 Vehicle Documents (Expired / Missing)"),
                    ("overloading", "👥 Overloading / Extra Passengers"),
                    ("rash_driving", "⚠️ Reckless / Rash Driving"),
                    ("other", "📝 Other Violation"),
                ],
                max_length=50,
            ),
        ),
    ]
