# Generated by Django 6.0.2 on 2026-09-24 05:18

import django.db.models.deletion
import django.utils.timezone
import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("fleet_contracts", "0003_transportcontract_category_specifications"),
        ("operations", "0003_alter_trafficfine_financial_responsibility_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeofenceZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("depot", "Fleet Yard / Garage Depot"),
                            ("airport", "Airport Terminal"),
                            ("school", "School / Educational Campus"),
                            ("client_site", "Corporate Tech Park / Client Office"),
                            ("fuel_station", "Authorized Petro Station"),
                            ("restricted_zone", "Restricted / High-Risk Area"),
                        ],
                        default="depot",
                        max_length=30,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=500, help_text="Circular geofence radius in meters"
                    ),
                ),
                (
                    "speed_limit_kmh",
                    models.PositiveIntegerField(
                        default=40, help_text="Max speed permitted inside zone (km/h)"
                    ),
                ),
                ("alert_on_entry", models.BooleanField(default=True)),
                ("alert_on_exit", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Geofence Zone",
                "verbose_name_plural": "Geofence Zones",
            },
        ),
        migrations.CreateModel(
            name="DriverBehaviorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("overspeeding", "Overspeeding Violation"),
                            ("harsh_braking", "Harsh / Panic Braking"),
                            ("harsh_acceleration", "Harsh / Rapid Acceleration"),
                            ("excessive_idling", "Excessive Engine Idling (>15 min)"),
                            ("sharp_cornering", "Aggressive / Sharp Cornering"),
                            ("geofence_breach", "Geofence Boundary Breach"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical Hazard"),
                            ("high", "High Risk"),
                            ("medium", "Medium Risk"),
                            ("low", "Minor Infraction"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "recorded_speed_kmh",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "speed_limit_kmh",
                    models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("location_address", models.CharField(blank=True, max_length=255)),
                (
                    "penalty_points",
                    models.PositiveIntegerField(
                        default=5, help_text="Points deducted from safety scorecard"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="behavior_events",
                        to="core.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="behavior_events",
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_events",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Behavior Event",
                "verbose_name_plural": "Driver Behavior Events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyIncidentAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_id",
                    models.CharField(
                        default=operations.models.generate_incident_id,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("breakdown", "Mechanical Breakdown"),
                            ("accident", "Road Accident / Collision"),
                            ("tyre_burst", "Tyre Burst / Puncture"),
                            ("engine_overheat", "Engine Overheating"),
                            ("medical", "Medical Emergency"),
                            ("fuel_exhaustion", "Out of Fuel / DEF"),
                            ("other", "Other Incident"),
                        ],
                        default="breakdown",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical (Immediate Dispatch)"),
                            ("high", "High Priority"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="critical",
                        max_length=20,
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "location_address",
                    models.CharField(
                        blank=True,
                        help_text="Highway KM, landmark, or city",
                        max_length=255,
                    ),
                ),
                ("passenger_count", models.PositiveIntegerField(default=0)),
                (
                    "passengers_safety_status",
                    models.CharField(
                        choices=[
                            ("all_safe", "All Passengers Safe & Unharmed"),
                            ("minor_injuries", "Minor First-Aid Required"),
                            ("hospitalized", "Medical Attention / Hospitalized"),
                            ("stranded_safe", "Safe but Stranded Roadside"),
                        ],
                        default="all_safe",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed problem description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported / SOS Triggered"),
                            ("acknowledged", "Acknowledged by Dispatch"),
                            ("standby_dispatched", "Standby Vehicle Dispatched"),
                            ("resolved", "Resolved on Site"),
                            ("closed", "Closed & Completed"),
                        ],
                        default="reported",
                        max_length=30,
                    ),
                ),
                ("standby_dispatched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "standby_eta_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_alerts",
                        to="fleet_contracts.contracttriplog",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_alerts",
                        to="core.driver",
                    ),
                ),
                (
                    "standby_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standby_dispatched_incidents",
                        to="core.driver",
                    ),
                ),
                (
                    "standby_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standby_dispatched_incidents",
                        to="core.vehicle",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_alerts",
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_alerts",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Incident / SOS Alert",
                "verbose_name_plural": "Emergency Incident / SOS Alerts",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleTelematicsPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "speed_kmh",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("heading_degrees", models.FloatField(blank=True, null=True)),
                ("altitude_m", models.FloatField(blank=True, null=True)),
                ("ignition_on", models.BooleanField(default=True)),
                (
                    "fuel_level_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("odometer_km", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "satellite_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("raw_telemetry", models.JSONField(blank=True, default=dict)),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telematics_pings",
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telematics_pings",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Telematics Ping",
                "verbose_name_plural": "Vehicle Telematics Pings",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-timestamp"],
                        name="operations__vehicle_8fc412_idx",
                    )
                ],
            },
        ),
    ]
