# Generated by Django 6.0.2 on 2026-09-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_geofencezone_driverbehaviorlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="tracking_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
    ]
