# Generated by Django 6.0.2 on 2026-09-25 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("operations", "0005_trip_tracking_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="closing_odometer_photo",
            field=models.ImageField(
                blank=True,
                help_text="End duty photo of vehicle odometer",
                null=True,
                upload_to="trip_odometers/closing/",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="driver_handover_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of latest handover action", null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="driver_handover_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Start Handover"),
                    ("started", "Trip Started & Handover Verified"),
                    ("ended", "Trip Ended & Handover Submitted"),
                    ("approved", "Handover Audit Approved"),
                    ("flagged", "Handover Discrepancy Flagged"),
                ],
                default="pending",
                help_text="Digital vehicle handover audit workflow state",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="opening_odometer_photo",
            field=models.ImageField(
                blank=True,
                help_text="Start duty photo of vehicle odometer",
                null=True,
                upload_to="trip_odometers/opening/",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="whatsapp_broadcast_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Count of automated WhatsApp broadcasts sent for this trip",
            ),
        ),
        migrations.CreateModel(
            name="DriverHandoverSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("start", "Start Duty Handover"),
                            ("end", "End Duty Handover"),
                        ],
                        default="start",
                        max_length=10,
                    ),
                ),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(help_text="Odometer reading in KM"),
                ),
                (
                    "odometer_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Dashboard photo verifying odometer",
                        null=True,
                        upload_to="trip_odometers/sessions/",
                    ),
                ),
                (
                    "fuel_level_percent",
                    models.PositiveIntegerField(
                        default=100, help_text="Fuel gauge level percentage (0-100%)"
                    ),
                ),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text="GPS Reverse Geocoded or entered location",
                        max_length=255,
                    ),
                ),
                (
                    "cleanliness_rating",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Vehicle cleanliness score 1-5"
                    ),
                ),
                (
                    "scratch_damage_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on any scratches, dents, or pre-existing marks",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted by Driver"),
                            ("approved", "Audit Approved"),
                            ("flagged", "Flagged Discrepancy"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("audit_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover_sessions",
                        to="core.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handover_sessions",
                        to="operations.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover_sessions",
                        to="core.vehicle",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Handover Session",
                "verbose_name_plural": "Driver Handover Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppBotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_phone", models.CharField(db_index=True, max_length=30)),
                ("recipient_phone", models.CharField(db_index=True, max_length=30)),
                (
                    "message_direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound (Received)"),
                            ("outbound", "Outbound (Sent)"),
                        ],
                        default="inbound",
                        max_length=15,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("dispatch_alert", "Passenger Dispatch Alert"),
                            ("driver_briefing", "Driver Trip Assignment"),
                            ("start_handover", "Start Trip Handover"),
                            ("end_handover", "End Trip Handover"),
                            ("sos_trigger", "Emergency SOS Alert"),
                            ("trip_status", "Trip Status / Live Track"),
                            ("payment_upi", "UPI Payment Link / QR"),
                            ("general_query", "General Bot Chat / Fallback"),
                        ],
                        default="general_query",
                        max_length=30,
                    ),
                ),
                ("message_body", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("simulated", "Simulated"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp wamid or local message UUID",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="core.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="operations.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Bot Message",
                "verbose_name_plural": "WhatsApp Bot Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
