# Generated by Django 6.0.2 on 2026-09-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operations",
            "0006_trip_closing_odometer_photo_trip_driver_handover_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencyincidentalert",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("breakdown", "Mechanical Breakdown"),
                    ("accident", "Road Accident / Collision"),
                    ("tyre_burst", "Tyre Burst / Puncture"),
                    ("engine_overheat", "Engine Overheating"),
                    ("medical", "Medical Emergency"),
                    ("sos_panic", "Women Safety SOS / Panic Trigger"),
                    ("fuel_exhaustion", "Out of Fuel / DEF"),
                    ("other", "Other Incident"),
                ],
                default="breakdown",
                max_length=30,
            ),
        ),
    ]
