# Generated by Django 6.0.2 on 2026-09-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_licenseclass_options"),
        ("operations", "0007_alter_emergencyincidentalert_incident_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="car_drop_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="car_pickup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="current_milestone",
            field=models.CharField(
                choices=[
                    ("car_pickup", "1. Car Pickup"),
                    ("driver_reached", "2. Driver Reached"),
                    ("guest_pickup", "3. Guest Pickup & PIN"),
                    ("on_trip", "4. On Trip"),
                    ("guest_drop", "5. Guest Drop"),
                    ("expenses_photo", "6. Expenses Photo"),
                    ("car_drop", "7. Car Drop"),
                ],
                default="car_pickup",
                help_text="Current stage in the 7-milestone tour lifecycle",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="driver_reached_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="expenses_photo_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="guest_drop_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="guest_pickup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_pin_verified",
            field=models.BooleanField(
                default=False, help_text="True once passenger 4-digit PIN is verified"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="on_trip_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="pickup_pin",
            field=models.CharField(
                blank=True,
                help_text="Secure 4-digit passenger verification PIN",
                max_length=6,
            ),
        ),
        migrations.CreateModel(
            name="TripMilestoneEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone",
                    models.CharField(
                        choices=[
                            ("car_pickup", "1. Car Pickup"),
                            ("driver_reached", "2. Driver Reached"),
                            ("guest_pickup", "3. Guest Pickup & PIN"),
                            ("on_trip", "4. On Trip"),
                            ("guest_drop", "5. Guest Drop"),
                            ("expenses_photo", "6. Expenses Photo"),
                            ("car_drop", "7. Car Drop"),
                        ],
                        max_length=30,
                    ),
                ),
                ("milestone_index", models.PositiveSmallIntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "odometer_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="trip_odometers/milestones/"
                    ),
                ),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("passenger_pin_entered", models.CharField(blank=True, max_length=6)),
                ("is_pin_verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "actor_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestone_events",
                        to="core.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_events",
                        to="operations.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Milestone Event",
                "verbose_name_plural": "Trip Milestone Events",
                "ordering": ["timestamp", "milestone_index"],
            },
        ),
    ]
