# Generated by Django 6.0.2 on 2026-09-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0008_trip_car_drop_at_trip_car_pickup_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripItineraryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Tour Day sequence number (1, 2, 3...)"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Specific calendar date for this itinerary day",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Day headline e.g. Mysore Palace & Brindavan Gardens",
                        max_length=255,
                    ),
                ),
                (
                    "route_segment",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Bangalore -> Mysore -> Coorg",
                        max_length=255,
                    ),
                ),
                (
                    "morning_plan",
                    models.TextField(
                        blank=True,
                        help_text="Morning activity, breakfast stop, departure",
                    ),
                ),
                (
                    "sightseeing_spots",
                    models.TextField(
                        blank=True,
                        help_text="Key sightseeing spots, comma or newline separated",
                    ),
                ),
                (
                    "evening_plan",
                    models.TextField(
                        blank=True,
                        help_text="Evening highlights, dinner, campfire, sunset view",
                    ),
                ),
                (
                    "night_stay_location",
                    models.CharField(
                        blank=True,
                        help_text="City or resort area for overnight stay",
                        max_length=255,
                    ),
                ),
                (
                    "hotel_name",
                    models.CharField(
                        blank=True,
                        help_text="Assigned hotel / resort name",
                        max_length=255,
                    ),
                ),
                (
                    "hotel_booking_status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ Pending Confirmation"),
                            ("confirmed", "✅ Confirmed Voucher"),
                            ("checked_in", "🏨 Checked In"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "hotel_voucher_number",
                    models.CharField(
                        blank=True,
                        help_text="Hotel confirmation voucher/booking ID",
                        max_length=100,
                    ),
                ),
                (
                    "hotel_address",
                    models.CharField(
                        blank=True,
                        help_text="Hotel location or address",
                        max_length=255,
                    ),
                ),
                (
                    "meals_included",
                    models.CharField(
                        default="Breakfast, Lunch, Dinner",
                        help_text="Meals provided e.g. Breakfast, Lunch, Dinner",
                        max_length=255,
                    ),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        blank=True,
                        help_text="e.g. AC Luxury Coach / 4x4 Jeep Safari",
                        max_length=255,
                    ),
                ),
                (
                    "special_notes",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions, timings, entry dress codes",
                    ),
                ),
                (
                    "is_active_today",
                    models.BooleanField(
                        default=False,
                        help_text="Explicit flag for today's active tour day",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_days",
                        to="operations.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Itinerary Day",
                "verbose_name_plural": "Trip Itinerary Days",
                "ordering": ["day_number"],
                "unique_together": {("trip", "day_number")},
            },
        ),
    ]
