# Generated by Django 5.1.15 on 2026-10-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0009_tripitineraryday"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="customer_signature_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when customer signed on driver's mobile device",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="customer_signature_data",
            field=models.TextField(
                blank=True, help_text="Base64 DataURL PNG of customer digital signature"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="guest_feedback",
            field=models.TextField(
                blank=True, help_text="Customer satisfaction feedback remarks"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="guest_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Customer satisfaction rating 1 to 5 stars",
                null=True,
            ),
        ),
    ]
