# Generated by Django 5.1.15 on 2026-10-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0010_trip_customer_signature_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="driver_bata_breakdown",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed itemization of driver allowances: base bata, night halt, early morning, overtime, outstation",
            ),
        ),
    ]
