# Generated by Django 5.1.15 on 2026-10-10 05:41

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0011_trip_driver_bata_breakdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencyincidentalert",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("breakdown", "Mechanical Breakdown"),
                    ("accident", "Road Accident / Collision"),
                    ("tyre_burst", "Tyre Burst / Puncture"),
                    ("engine_overheat", "Engine Overheating"),
                    ("medical", "Medical Emergency"),
                    ("sos_panic", "Women Safety SOS / Panic Trigger"),
                    ("fuel_exhaustion", "Out of Fuel / DEF"),
                    ("geofence_breach", "Geofence Boundary Breach"),
                    ("corridor_deviation", "Route Corridor Deviation"),
                    ("overspeed_violation", "Severe Over-Speeding Violation"),
                    ("other", "Other Incident"),
                ],
                default="breakdown",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="driver_bata_breakdown",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Detailed itemization of driver allowances: base bata, night halt, early morning, overtime, outstation",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappbotmessage",
            name="intent",
            field=models.CharField(
                choices=[
                    ("dispatch_alert", "Passenger Dispatch Alert"),
                    ("driver_briefing", "Driver Trip Assignment"),
                    ("start_handover", "Start Trip Handover"),
                    ("end_handover", "End Trip Handover"),
                    ("sos_trigger", "Emergency SOS Alert"),
                    ("trip_status", "Trip Status / Live Track"),
                    ("payment_upi", "UPI Payment Link / QR"),
                    ("geofence_breach_alert", "Geofence Breach & Safety Alarm"),
                    ("general_query", "General Bot Chat / Fallback"),
                ],
                default="general_query",
                max_length=30,
            ),
        ),
    ]
