# Generated by Django 5.1.15 on 2026-10-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_party_party_rates_non_negative"),
        ("operations", "0012_alter_emergencyincidentalert_incident_type_and_more"),
        ("packages", "0009_package_cost_activities_per_pax_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("drop_date__isnull", True),
                    ("pickup_date__isnull", True),
                    ("drop_date__gte", models.F("pickup_date")),
                    _connector="OR",
                ),
                name="booking_drop_date_gte_pickup_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quoted_price__isnull", True),
                    ("quoted_price__gte", 0),
                    _connector="OR",
                ),
                name="booking_quoted_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("start_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="trip_end_date_gte_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closing_km__isnull", True),
                    ("opening_km__isnull", True),
                    ("closing_km__gte", models.F("opening_km")),
                    _connector="OR",
                ),
                name="trip_closing_km_gte_opening_km",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_rate__gte", 0)),
                name="trip_day_rate_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(("km_rate__gte", 0)),
                name="trip_km_rate_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(("fixed_amount__gte", 0)),
                name="trip_fixed_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(("driver_bata__gte", 0)),
                name="trip_driver_bata_non_negative",
            ),
        ),
    ]
