# Generated by Django 5.1.15 on 2026-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_driver_idx_drv_status_type_and_more"),
        ("operations", "0013_booking_booking_drop_date_gte_pickup_date_and_more"),
        ("packages", "0009_package_cost_activities_per_pax_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trafficfine",
            options={"ordering": ["-date_of_offence"]},
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "pickup_date"], name="idx_bk_status_pickup"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["party", "booking_date"], name="idx_bk_party_date"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["booking_date"], name="idx_bk_date"),
        ),
        migrations.AddIndex(
            model_name="driverbehaviorlog",
            index=models.Index(
                fields=["driver", "timestamp"], name="idx_drv_beh_driver_time"
            ),
        ),
        migrations.AddIndex(
            model_name="driverbehaviorlog",
            index=models.Index(
                fields=["vehicle", "timestamp"], name="idx_drv_beh_veh_time"
            ),
        ),
        migrations.AddIndex(
            model_name="trafficfine",
            index=models.Index(
                fields=["vehicle", "date_of_offence"], name="idx_tf_veh_date"
            ),
        ),
        migrations.AddIndex(
            model_name="trafficfine",
            index=models.Index(
                fields=["driver", "date_of_offence"], name="idx_tf_drv_date"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["status", "start_date"], name="idx_trip_status_start"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["vehicle", "status"], name="idx_trip_vehicle_status"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["driver", "status"], name="idx_trip_driver_status"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["party", "status"], name="idx_trip_party_status"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["start_date", "end_date"], name="idx_trip_date_range"
            ),
        ),
    ]
