"""
Django settings for travelerp project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-travelerp-development-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "testserver",
    ".trycloudflare.com",
    "http://127.0.0.1:8000"
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.dev",
]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'travelerp.apps.TravelERPAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'core_partners',
    'core_crew',
    'integrations',
    'dashboard',
    'operations',
    'finance',
    'finance_fleet',
    'finance_payroll',
    'finance_treasury',
    'statements',
    'fleet_contracts',
    'crm',
    'maintenance',
    'maintenance_compliance',
    'packages',
    'payments_gateway',
    'customer_portal',
    'documents',
    'marketing',
    'suppliers',
    'audit',
    'digital_services',
    'enterprise_governance',
    'fleet_commute',
    'package_tours',
    'analytics',
    'driver_portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'travelerp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travelerp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('ta', 'Tamil'),
    ('hi', 'Hindi'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

COMPANY_NAME = 'Sivagayathiri Tours and Travels'
COMPANY_LOCATION = 'Coimbatore, Tamil Nadu'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Travel ERP",
    "site_header": "Travel ERP Admin",
    "site_brand": "Mission Control",
    "welcome_sign": "Welcome to the Fleet Manager",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "custom_css": "admin/css/custom_admin.css",
    "custom_js": None,
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index"},
        {"name": "Mission Control Dashboard", "url": "/"},
    ],
    "hide_models": [
        "packages.packagetemplate",
        "packages.packagevehicletariff",
        "packages.templedarshanslot",
        "packages.itineraryday",
        "packages.internationaldocumentchecklist",
        "package_tours.boardingpointproxy",
    ],
    "order_with_respect_to": [
        # 1. Sales Pipeline, CRM & Marketing (Lead Inquiries)
        "crm",
        "crm.Inquiry",
        "crm.CustomerPreference",
        "crm.CommunicationLog",
        "crm.CouponProxy",
        "crm.EmailCampaignProxy",
        "crm.UpsellRecommendationProxy",

        # 2. Daily Bookings & Trip Operations
        "operations",
        "operations.Booking",
        "operations.Trip",
        "operations.BulkContract",
        "operations.BulkContractDay",
        "operations.TrafficFine",

        # 3. Tour Packages & Itinerary Catalog
        "packages",
        "packages.Package",

        # 4. College IV & Group Tour Departures
        "package_tours",
        "package_tours.CollegeIVProxy",
        "package_tours.TourDepartureBatchProxy",
        "package_tours.PassengerManifestProxy",

        # 5. Institutional Contracts & SLA Governance
        "fleet_contracts",
        "fleet_contracts.TransportContract",
        "fleet_contracts.ContractFleetRoster",
        "fleet_contracts.ContractSLAPenalty",
        "fleet_contracts.ContractMonthlyInvoice",

        # 6. Commute Routes, Roster & Execution
        "fleet_commute",
        "fleet_commute.CommuteRoute",
        "fleet_commute.RouteStop",
        "fleet_commute.CommuteShift",
        "fleet_commute.CommuterManifestProxy",
        "fleet_commute.DailyTripLog",
        "fleet_commute.NightSafetyEscort",

        # 7. Digital Collections & Guest Portal
        "digital_services",
        "digital_services.InstallmentPlanProxy",
        "digital_services.PaymentLinkProxy",
        "digital_services.PaymentWebhookEventProxy",
        "digital_services.CustomerAccountProxy",
        "digital_services.CustomerDocumentProxy",

        # 8. Trip Cash Desk & Advances
        "finance",
        "finance.TripExpense",
        "finance.DriverAdvance",
        "finance.DriverSettlement",
        "finance.SupplierTripCost",

        # 9. Fleet Fuel & FASTag Operations
        "finance_fleet",
        "finance_fleet.FuelRecord",
        "finance_fleet.CorporatePetroAccount",
        "finance_fleet.CorporateFastagAccount",
        "finance_fleet.FastagTollDeduction",

        # 10. Corporate Accounts & Treasury
        "finance_treasury",
        "finance_treasury.Payment",
        "finance_treasury.VehicleLoan",
        "finance_treasury.LedgerAdjustment",
        "finance_treasury.TripProfitReport",

        # 11. Crew Payroll & Staff Accounts
        "finance_payroll",
        "finance_payroll.DriverSalaryProfile",
        "finance_payroll.DriverPayslip",
        "finance_payroll.EmployeePayment",

        # 12. Fleet Workshop & Technical Assets
        "maintenance",
        "maintenance.DefectTicket",
        "maintenance.ServiceReminder",
        "maintenance.ServiceRecord",
        "maintenance.PartInventory",
        "maintenance.VehicleAsset",

        # 13. Fleet Compliance & Legal
        "maintenance_compliance",
        "maintenance_compliance.ComplianceDocument",
        "maintenance_compliance.InsuranceClaim",

        # 14. Business Partners & Tariffs
        "core_partners",
        "core_partners.Client",
        "core_partners.Supplier",
        "core_partners.RateCard",

        # 15. Fleet Assets & Specifications
        "core",
        "core.Vehicle",
        "core.VehicleType",

        # 16. Crew & Driver Management
        "core_crew",
        "core_crew.Driver",
        "core_crew.Cleaner",
        "core_crew.LicenseClass",

        # 17. Partner Governance & Audit Logs
        "enterprise_governance",
        "enterprise_governance.SupplierContractProxy",
        "enterprise_governance.CommissionRuleProxy",
        "enterprise_governance.AuditLogEntryProxy",

        # 18. Statements & Reports
        "statements",

        # 19. Analytics
        "analytics",

        # 20. Auth
        "auth",
        "auth.User",
        "auth.Group",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core_partners.Client": "fas fa-building",
        "core_partners.Supplier": "fas fa-truck-loading",
        "core_partners.RateCard": "fas fa-tags",
        "core.Vehicle": "fas fa-bus",
        "core.VehicleType": "fas fa-car-side",
        "core_crew.Driver": "fas fa-user-tie",
        "core_crew.Cleaner": "fas fa-broom",
        "core_crew.LicenseClass": "fas fa-id-card",
        "core.Client": "fas fa-building",
        "core.Supplier": "fas fa-truck-loading",
        "core.Vehicle": "fas fa-bus",
        "core.VehicleType": "fas fa-car-side",
        "core.Driver": "fas fa-user-tie",
        "core.Cleaner": "fas fa-broom",
        "core.RateCard": "fas fa-tags",
        "core.LicenseClass": "fas fa-id-card",
        "core.Party": "fas fa-handshake",
        "core.Place": "fas fa-map-marker-alt",
        "core.Route": "fas fa-route",
        "operations.Booking": "fas fa-calendar-check",
        "operations.Trip": "fas fa-road",
        "operations.TrafficFine": "fas fa-ticket-alt",
        # Finance Segment 1: Cash Desk
        "finance.TripExpense": "fas fa-receipt",
        "finance.DriverAdvance": "fas fa-hand-holding-usd",
        "finance.DriverSettlement": "fas fa-file-invoice-dollar",
        "finance.SupplierTripCost": "fas fa-truck-loading",

        # Finance Segment 2: Fleet Fuel & FASTag
        "finance_fleet.FuelRecord": "fas fa-gas-pump",
        "finance_fleet.CorporatePetroAccount": "fas fa-credit-card",
        "finance_fleet.CorporateFastagAccount": "fas fa-id-card-alt",
        "finance_fleet.FastagTollDeduction": "fas fa-road",

        # Finance Segment 3: Payroll & HR
        "finance_payroll.DriverSalaryProfile": "fas fa-user-cog",
        "finance_payroll.DriverPayslip": "fas fa-file-invoice",
        "finance_payroll.EmployeePayment": "fas fa-money-check-alt",

        # Finance Segment 4: Treasury & Accounts
        "finance_treasury.Payment": "fas fa-money-bill-wave",
        "finance_treasury.VehicleLoan": "fas fa-university",
        "finance_treasury.LedgerAdjustment": "fas fa-balance-scale",
        "finance_treasury.TripProfitReport": "fas fa-chart-line",
        "maintenance.DefectTicket": "fas fa-exclamation-triangle",
        "maintenance.VehicleAsset": "fas fa-cogs",
        "maintenance.AssetRotationLog": "fas fa-sync",
        "maintenance.ServiceRecord": "fas fa-tools",
        "maintenance.ServiceReminder": "fas fa-bell",
        "maintenance.PartInventory": "fas fa-boxes",
        # Fleet Compliance & Legal
        "maintenance_compliance.ComplianceDocument": "fas fa-file-contract",
        "maintenance_compliance.InsuranceClaim": "fas fa-shield-alt",

        # Institutional Contracts & SLA Governance
        "fleet_contracts.TransportContract": "fas fa-file-contract",
        "fleet_contracts.ContractFleetRoster": "fas fa-clipboard-check",
        "fleet_contracts.ContractSLAPenalty": "fas fa-exclamation-triangle",
        "fleet_contracts.ContractMonthlyInvoice": "fas fa-file-invoice-dollar",

        # Commute Routes, Roster & Execution
        "fleet_commute.CommuteRoute": "fas fa-route",
        "fleet_commute.RouteStop": "fas fa-map-marker-alt",
        "fleet_commute.CommuteShift": "fas fa-clock",
        "fleet_commute.CommuterManifestProxy": "fas fa-user-friends",
        "fleet_commute.DailyTripLog": "fas fa-bus",
        "fleet_commute.NightSafetyEscort": "fas fa-user-shield",

        # CRM & Marketing
        "crm.Inquiry": "fas fa-funnel-dollar",
        "crm.CustomerPreference": "fas fa-sliders-h",
        "crm.CommunicationLog": "fas fa-comments",
        "crm.CouponProxy": "fas fa-ticket-alt",
        "crm.EmailCampaignProxy": "fas fa-paper-plane",
        "crm.UpsellRecommendationProxy": "fas fa-gem",

        # Digital Services
        "digital_services.InstallmentPlanProxy": "fas fa-calendar-alt",
        "digital_services.PaymentLinkProxy": "fas fa-link",
        "digital_services.PaymentWebhookEventProxy": "fas fa-satellite-dish",
        "digital_services.CustomerAccountProxy": "fas fa-user-circle",
        "digital_services.CustomerDocumentProxy": "fas fa-file-alt",

        # Enterprise Governance
        "enterprise_governance.SupplierContractProxy": "fas fa-file-contract",
        "enterprise_governance.CommissionRuleProxy": "fas fa-percent",
        "enterprise_governance.AuditLogEntryProxy": "fas fa-history",

        # Tour Packages & Itinerary Catalog
        "packages.Package": "fas fa-umbrella-beach",
        "packages.PackageTemplate": "fas fa-layer-group",
        "packages.PackageVehicleTariff": "fas fa-money-check-alt",
        "packages.TempleDarshanSlot": "fas fa-om",
        "packages.ItineraryDay": "fas fa-calendar-day",
        "packages.InternationalDocumentChecklist": "fas fa-passport",

        # College IV & Group Tour Departures
        "package_tours.CollegeIVProxy": "fas fa-graduation-cap",
        "package_tours.TourDepartureBatchProxy": "fas fa-bus-alt",
        "package_tours.PassengerManifestProxy": "fas fa-user-check",
        "package_tours.BoardingPointProxy": "fas fa-map-marked-alt",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "slate",
    "theme_color": "default",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_child_indent": True,
    "sidebar_fixed": True,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
}
