# Generated by Django 6.0.2 on 2026-09-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerAdjustment",
            fields=[],
            options={
                "verbose_name": "Party Ledger Adjustment",
                "verbose_name_plural": "Party Ledger Adjustments",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.ledgeradjustment",),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[],
            options={
                "verbose_name": "Payment & Voucher",
                "verbose_name_plural": "Payments & Vouchers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.payment",),
        ),
        migrations.CreateModel(
            name="TripProfitReport",
            fields=[],
            options={
                "verbose_name": "Trip P&L Report",
                "verbose_name_plural": "Trip P&L Reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.tripprofitreport",),
        ),
        migrations.CreateModel(
            name="VehicleLoan",
            fields=[],
            options={
                "verbose_name": "Vehicle Bank Loan",
                "verbose_name_plural": "Vehicle Bank Loans",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finance.vehicleloan",),
        ),
    ]
